KlimaDAO/klimadao

app/actions/app.ts
lib/constants/index.ts
lib/utils/getStakingAPY/index.ts

Increase estimated daily rebases per day to more accurately reflect APY

Merge staging

---

LICENSE

We need to a license for this repo, we're already using MIT for the contracts and Discord bots

Add open source MIT license

---

app/components/views/Bond/index.module.css
app/components/views/Bond/index.tsx
app/components/views/PKlima/index.tsx
app/components/views/Redeem/index.tsx
app/components/views/Stake/index.module.css
app/components/views/Stake/index.tsx
app/components/views/Wrap/index.tsx
app/next.config.js
app/package.json
lib/components/TextInfoTooltip/index.tsx
lib/components/TextInfoTooltip/styles.ts
lib/components/index.ts
lib/package.json
lib/theme/breakpoints.ts
lib/theme/typography.ts
package-lock.json

Closes #12
Closes #16 
Progress on #10

Add Animated tooltips to all views

---

app/components/views/Stake/index.tsx

Increase rounding precision of next rebase value

---

app/components/views/Home/index.tsx

test dapp auto-deployment

---

app/components/CheckURLBanner/index.module.css
app/components/CheckURLBanner/index.tsx
app/components/views/Home/index.tsx

give the people what they want

add "dont remind me" button for checkURLBanner

---

app/components/hooks/useENS.ts
app/components/views/Home/WalletAction/index.tsx
app/components/views/Home/constants.ts
app/components/views/Home/index.module.css
app/components/views/Home/index.tsx

add ens name and avatar support

feat: add ens name and avatar support

---

app/components/views/Stake/index.tsx
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po
lib/utils/prettifySeconds/index.ts

Update rebase label

---

app/actions/bonds.ts
app/actions/pklima.ts
app/actions/redeem.ts
app/actions/stake.ts
app/actions/utils.ts
app/actions/wrap.ts
app/components/NotificationModal/index.module.css
app/components/NotificationModal/index.tsx
app/components/views/Bond/index.tsx
app/components/views/Home/index.tsx
app/components/views/PKlima/ClaimExceededModal/index.tsx
app/components/views/PKlima/index.tsx
app/components/views/Redeem/index.tsx
app/components/views/Stake/index.tsx
app/components/views/Wrap/index.tsx
app/state/app/index.ts
app/state/selectors/index.ts

Integration of @borbesaur 's awesome work in  #92
setting up a modal which can be triggered from redux
and using it in place of our `onStatus()` callbacks and alert() calls.
Future enhancements:
- animations
- "add token to metamask" like sushiswap does
Closes #22

New notification & error modals

---

app/actions/bonds.ts
app/components/views/ChooseBond/index.tsx
app/components/views/Home/index.tsx
lib/constants/index.ts

Mco2 klima bonds

---

app/components/views/Bond/index.tsx
cms/schemas/blockContent.js
cms/schemas/post.js
lib/components/Text/index.tsx
lib/components/WebFonts/index.tsx
lib/theme/typography.ts
site/@types/block-content-to-react.d.ts
site/components/BlockContentRenderer/index.module.css
site/components/BlockContentRenderer/index.tsx
site/components/Card/index.tsx
site/components/Footer/styles.ts
site/components/pages/Blog/Post/index.module.css
site/components/pages/Blog/Post/index.tsx
site/components/pages/Blog/index.module.css
site/components/pages/Resources/Container/styles.ts
site/lib/queries.ts

*  this PR updates the layout of the blog so it is more human readable
*  remove h1 option from sanity schema
*  make the main image optional

Blog formatting updates

---

site/components/pages/Resources/Community/index.tsx
site/components/pages/Resources/Community/styles.ts
site/components/pages/Resources/Contact/index.tsx
site/components/pages/Resources/Contact/styles.ts

Minor missing pieces from this big piece: https://github.com/KlimaDAO/klimadao/pull/118

Fix Discord Invite Link and Contact Text alignment

---

site/components/pages/Resources/Community/index.tsx
site/components/pages/Resources/Community/styles.ts

Adding requested changes to the Community page Partners section to accommodate dark theme styles.
Partially resolves #131

131 cleanup partners section dark theme

---

lib/constants/index.ts

As requested this changes to a cleaner URL
None

refactor: change discord invite URL

---

app/components/views/Bond/index.tsx
app/components/views/ChooseBond/index.tsx

Redeem still works. Merge when you want

Disable bonds for bct_usdc_lp

---

app/components/views/Bond/index.tsx
app/components/views/ChooseBond/index.tsx
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po
app/package.json
package-lock.json
site/components/pages/Home/index.tsx
site/locale/en/messages.po
site/locale/fr/messages.po
site/locale/pseudo/messages.po
site/package.json

- upgrade nextjs
- fix a typo that happened during i18n work
- disable bonds (see staging)

Release staging to production - disable BCT/USDC LP bonds.

---

app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po
site/locale/en/messages.po
site/locale/fr/messages.po
site/locale/pseudo/messages.po

A lot of new text was added.
I ran `npm run compile-strings` and this is the result.

Extract translation strings

---

app/actions/app.ts
app/pages/api/block-rate/index.ts
lib/constants/index.ts
lib/utils/getBlockRate/index.ts
lib/utils/getStakingAPY/index.ts

- [ X ] Building the site with `npm run build-site` works without errors
- [ X ] Building the app with `npm run build-app` works without errors
- [ X ] I formatted JS and TS files with running `npm run format-all`

api endpoint for block rate

---

site/components/pages/Blog/index.tsx
site/components/pages/Home/index.tsx
site/lib/queries.ts
site/pages/index.tsx

Dynamically set the landing page news banner to link to the latest blog post.

feat: link to latest blog post on homepage

---

lib/utils/getKlimaSupply/index.ts
lib/utils/index.ts
site/pages/api/klima-supply/index.ts

Adds API endpoint for current KLIMA supply
Resolves #198

Add KLIMA supply API

---

app/components/NavMenu/index.tsx
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po

Added translation tags for navbar.

18n: First pass on Navbar

---

app/components/views/Bond/index.tsx
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po
site/locale/en/messages.po
site/locale/fr/messages.po
site/locale/pseudo/messages.po

To avoid misunderstand, just change the word to make it clearer.
Resolves #191 
|<img width="623" alt="before" src="https://user-images.githubusercontent.com/3491087/156188273-7b65a195-53f5-481c-91b7-c46afd00aedf.png">|<img width="537" alt="after" src="https://user-images.githubusercontent.com/3491087/156188329-18809802-8543-458e-95b3-442f5cdceb47.png">|

Pending wording

---

lib/utils/getBlockRate/index.ts

- [x ] Building the site with `npm run build-site` works without errors
- [x ] Building the app with `npm run build-app` works without errors
- [ x] I formatted JS and TS files with running `npm run format-all`

minor changes and variables rename in getBlockRate

---

app/actions/utils.ts
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po

Added translation status messages

i18n: Status messages

---

app/components/views/ChooseBond/index.tsx
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po

Added translation status messages

i18n: Choose bond

---

cms/config/.checksums
cms/config/@sanity/vision.json
cms/schemas/post.js
site/lib/queries.ts

Ability to preview blog posts on staging URL

---

site/lib/constants.ts
site/lib/getBlockRate.ts
site/pages/api/block-rate/index.ts

Just adds the API without actually integrating into the app so we will have a staging deployment to hit for testing

Add vienio's dynamic block rate API

---

app/components/NavMenu/index.tsx
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po

Added translation tags for nav menu

i18n: a1. NavMenu

---

app/components/BalancesCard/index.tsx
app/components/ImageCard/index.tsx
app/components/RebaseCard/index.tsx
app/components/views/Stake/index.tsx
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po

Added translation tags for stake page, balance card and image card

i18n: a3. Stake page

---

app/components/views/Bond/index.tsx
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po

Added translation to the bond/redeem page

i18n: a4. Bond

---

app/components/views/PKlima/index.tsx
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po

Added translation to the pklima page

i18n: a5. pKlima

---

app/components/views/Info/index.tsx
app/locale/en/messages.po
app/locale/fr/messages.po
app/locale/pseudo/messages.po

Added translation tags  to the info page

i18n: a6. Info

---

site/components/ChangeLanguageButton/styles.ts
site/components/Navigation/index.tsx

Added changeLanguageButton in site (dev mode only)

i18n: s1. Added changeLanguageButton in site (dev mode only)

---

app/components/ChangeLanguageButton/index.tsx
site/components/ChangeLanguageButton/index.tsx
site/components/Footer/index.tsx
site/components/Footer/styles.ts
site/components/Header/HeaderMobile.tsx
site/components/Header/styles.ts
site/components/Navigation/index.tsx
site/components/pages/Blog/Post/index.module.css
site/components/pages/Blog/Post/index.tsx
site/components/pages/Blog/Post/styles.ts

Link back to `/blog` from `/blog/post`
Other changes:
- Aligned post image banner to content width on larger viewports
- Fix post image banner spacing on small viewports
- Reduced y padding on mobile header nav
- Close language selector pop up when on clicking outside the element
- Align footer width to content width on smaller viewports
Resolves [#202](https://github.com/KlimaDAO/klimadao/issues/202)
|<img width="600" alt="image" src="https://user-images.githubusercontent.com/97446324/156947762-7c43a652-2f68-436c-af30-91611d08d6df.png">|<img width="600" alt="image" src="https://user-images.githubusercontent.com/97446324/156947779-623bb8bf-ee3a-4322-a220-a2a0d5c52642.png">|
|<img width="429" alt="image" …

feat: link to blog from post

---

cms/schemas/blockContent.js
cms/schemas/fileUpload.js
cms/schemas/pdf.js
cms/schemas/schema.js
site/components/BlockContentRenderer/index.tsx
site/lib/queries.ts

feature request that enables authors to upload inline PDFs in Sanity IO

Add ability to upload inline PDFs in blog

---

site/components/pages/Blog/index.tsx
site/components/pages/Buy/index.tsx
site/components/pages/Disclaimer/index.tsx
site/components/pages/Home/index.tsx
site/components/pages/Resources/Community/index.tsx
site/components/pages/Resources/Contact/index.tsx
site/locale/en/messages.po
site/locale/fr/messages.po
site/locale/pseudo/messages.po

Improved translation tags for page heads in site

i18n s6. site page heads

---

site/components/Footer/index.tsx
site/components/Navigation/index.tsx
site/components/pages/Resources/Community/index.tsx

Purged duplicate ids mostly for navigation items translation

site: deduplicating some translated text

---

cms/package.json
cms/schemas/post.js
package-lock.json
site/components/pages/Blog/Post/index.tsx
site/components/pages/Blog/Post/styles.ts
site/lib/queries.ts

#250 
* add disclaimer boolean to Sanity Post schema that will default to true for all new blog posts
*  this will make it so the authors wont have to keep copy and pasting it into the post

add disclaimer to sanity schema

---

app/components/views/Offset/index.tsx

Fix acronym to reflect proper name for NCT: https://blog.toucan.earth/announcing-nct-nature-carbon-tonne/

Fix NCT acronym

---

app/components/views/Stake/index.tsx
app/locale/en/messages.po

Whoops, somehow missed this tooltip when we switched to AKR

Switch outdated AKR tooltip

---

app/actions/offset.ts
app/components/DropdownWithModal/styles.ts
app/components/views/Offset/index.tsx
app/components/views/Offset/styles.ts

- Add Advanced dropdown and logic to offset tool for selecting specific carbon projects to retire
- Rearrange inputs for better user experience
#280

Selective Retirement

---

app/components/views/Offset/index.tsx

Thanks for the hint:
These strings have to be translatable too.

Make Offset Dropdown Modals translatable

---

app/components/ChangeLanguageButton/index.tsx
app/components/views/Home/index.tsx
app/lib/i18n.ts
site/components/ChangeLanguageButton/index.tsx
site/components/Navigation/index.tsx
site/lib/i18n.ts
site/next.config.js

This PR does this:
- Load and Render FR and DE translation on Production  🔥 
- Load and Render Russian and Chinese on Staging only
Closes https://github.com/KlimaDAO/klimadao/issues/329
Closes https://github.com/KlimaDAO/klimadao/issues/157

Release French and German Translations 🎉 

---

app/components/views/Buy/styles.ts

Resolves #349
- [ x ] Building the site with `npm run build-site` works without errors
- [ x ] Building the app with `npm run build-app` works without errors
- [ x ] I formatted JS and TS files with running `npm run format-all`

fixed padding on buy page

---

app/actions/offset.ts
app/components/views/Offset/index.tsx
app/types/offset.ts
lib/abi/KlimaRetirementStorage.json
lib/types/offset.ts
lib/utils/getRetirement/index.ts
lib/utils/index.ts
site/components/pages/Retirement/SingleRetirement/index.tsx
site/components/pages/Retirement/index.tsx
site/components/pages/Retirement/styles.ts
site/pages/retirement/[beneficiary_address]/[retirement_index].tsx
site/pages/retirement/[beneficiary_address]/index.tsx

This PR does:
- App: get the total retirement number of an address
- App: set the total retirement number to the offset state
- App: Show external Link to Site with the beneficiary address and total retirement number **(Staging only)**
- Site: Generate dynamic pages from URL `retirement/<ADDRESS>` **(Staging only)**
- Site: Generate dynamic pages from URL `retirement/<ADDRESS>/<INDEX>` **(Staging only)**
The implemented contract methods on Site are **placeholders** until we get the actual GraphQL queries working from subgraph. **See the list of further steps below.**
1. Do an Offset here:
https://klimadao-app-git-retirement-pages-klimadao.vercel.app/#/offset
2. Wait for the Success Modal
3. In the Success Modal at the bottom copy the URL from the link "Open retirement details on: LINK`
4. …

Pass Retirement from App to Site and generate dynamic Pages

---

site/components/pages/Resources/Contact/index.tsx
site/locale/en/messages.po

Resolves #356
- [ x ] Building the site with `npm run build-site` works without errors
- [ x ] Building the app with `npm run build-app` works without errors
- [ x ] I formatted JS and TS files with running `npm run format-all`

careers section pointing to new discord

---

app/components/PageHead.tsx
site/components/PageHead/index.tsx

Added OG media tags for twitter
Resolves #373
Not applicable

Added OG media tags for twitter

---

app/components/views/Offset/index.tsx
app/locale/en/messages.po
lib/components/Buttons/ButtonPrimary.tsx
lib/components/Buttons/styles.ts
site/components/pages/Retirements/Footer/index.tsx
site/components/pages/Retirements/SingleRetirement/RetirementHeader/index.tsx
site/components/pages/Retirements/SingleRetirement/RetirementHeader/styles.ts
site/components/pages/Retirements/SingleRetirement/RetirementValue/index.tsx
site/components/pages/Retirements/SingleRetirement/index.tsx
site/locale/en/messages.po

Updates to text, remove auto pop-up.
#345 
#404
#412
Resolves #412 
| ![image](https://user-images.githubusercontent.com/88635679/168703244-7bf58faf-eb9b-41ba-a37a-0c2231c2d3a5.png) | ![image](https://user-images.githubusercontent.com/88635679/168703184-398faa19-f4c5-4a20-857b-7ff917e830dc.png) |

Improve Retirement modal and tweak Retirement Pages

---

app/actions/user.ts

As per changes suggested by @Atmosfearful at Issue #396 to optimize network calls
Issue #396 
Resolves #396

Optimized loadAccountDetails to use promise.all

---

app/actions/app.ts
lib/constants/index.ts
lib/utils/getJsonRpcProvider/index.ts
lib/utils/getKlimaSupply/index.ts
lib/utils/getRetirement/index.ts
lib/utils/getStakingRewards/index.ts
lib/utils/getTreasuryBalance/index.ts
site/components/pages/Pledge/PledgeDashboard/Cards/AssetBalanceCard/index.tsx
site/lib/constants.ts
site/lib/getBlockRate.ts
site/pages/api/klima-supply/index.ts
site/pages/index.tsx
site/pages/retirements/[beneficiary_address]/[retirement_index].tsx
site/pages/retirements/[beneficiary_address]/index.tsx

New PR for this issue as previous one's commit history was a bit messed up
Old one PR no. #374
Resolves #231 
- [ x ] Building the site with `npm run build-site` works without errors
- [ x ] Building the app with `npm run build-app` works without errors
- [ x ] I formatted JS and TS files with running `npm run format-all`

New infura rpc requests

---

app/components/views/Home/index.tsx
app/locale/de/messages.po
app/locale/en-pseudo/messages.po
app/locale/es/messages.po
app/locale/fr/messages.po
app/locale/ko/messages.po
app/locale/ru/messages.po
app/locale/zh-CN/messages.po
app/package.json
package-lock.json
site/locale/de/messages.po
site/locale/en-pseudo/messages.po
site/locale/es/messages.po
site/locale/fr/messages.po
site/locale/ko/messages.po
site/locale/ru/messages.po
site/locale/zh-CN/messages.po

Incorporating the Torus wallet connection module to allow users without Metamask or other crypto wallets to use the app with only an email account.
Ideally we'd have some design help with the icon for the card on the web3modal. I've placed an email outline icon from our icon library for now.
Added the `"@toruslabs/torus-embed": "^1.22.1"` package via npm.
Resolves #306 
|<img width="1381" alt="Screen Shot 2022-05-09 at 3 48 48 PM" src="https://user-images.githubusercontent.com/978072/167511329-234d75bc-d1af-467f-809f-6e98cf436e1f.png"> |<img width="1375" alt="Screen Shot 2022-05-09 at 3 49 20 PM" src="https://user-images.githubusercontent.com/978072/167511344-a218e24a-87b2-43ec-8881-f46eb00e2822.png">|

306 add torus to web3modal

---

app/components/views/Stake/index.tsx
app/components/views/Stake/styles.ts
app/locale/en/messages.po
lib/constants/index.ts

add LI.FI to stake page

---

app/components/views/Offset/index.tsx

- don't pass empty strings down in specificAddress array, it causes ethers to throw an error.
Fasttracking this PR to get offsets working again.
none

Fix Offset tool

---

site/components/pages/Blog/index.tsx
site/components/pages/Disclaimer/index.tsx
site/components/pages/Resources/Community/index.tsx
site/components/pages/Resources/Contact/index.tsx
site/components/pages/errors/Custom404.tsx

Just some quick string changes

update metadescription strings

---

site/pages/pledge/[address].tsx
site/pages/pledge/index.tsx

Remove the feature-flags on production
#255

enable pledge dashboards on prod

---

cms/package.json
cms/yarn.lock
package-lock.json
site/package.json

- upgrade cli and run `sanity upgrade`
- regenerate lockfile to remove the cms from npm workspaces

Update CMS deps

---

app/components/views/Stake/index.tsx

Removes wsKlima from stake view
Resolves #497

Removed wsKlima from stake view

---

app/components/views/ChooseBond/index.tsx

1. merge to staging
2. activate contract
3. test on staging
4. merge staging to prod using actions -> schedule auto merge (staging)

enable inverse usdc

---

app/actions/bonds.ts
app/components/views/Bond/index.tsx
app/components/views/ChooseBond/index.tsx

1. init contracts
2. test on preview link below
3. when it's ready, merge this PR to staging
4. then deploy to prod: use github Actions -> schedule auto merge (staging to production)

enable inverse bonds

---

app/components/views/ChooseBond/index.tsx
app/locale/de/messages.po
app/locale/en/messages.po
app/locale/es/messages.po
app/locale/fr/messages.po
app/locale/ru/messages.po
app/locale/zh-CN/messages.po

Clarifies language since inverse bonds have 0 day vesting period

Update text to reflect inverse bonds 0 day vesting

---

app/actions/bonds.ts

market id from 8 to 9

---

app/actions/stake.ts
lib/constants/index.ts
lib/utils/getTransactionOptions/index.ts
lib/utils/index.ts

Adds logic to use polyscan api for gasPrice
Resolves #519
|Before|After|
|
|
|

Added logic to use polyscan api for gasPrice

---

app/components/ChangeLanguageButton/index.tsx
app/lib/i18n.ts
app/locale/hi/messages.po
lingui.config.js
site/components/ChangeLanguageButton/index.tsx
site/lib/i18n.ts
site/locale/hi/messages.po
site/next.config.js

After merge to staging => Hindi will be available on translation.io
Resolves https://github.com/KlimaDAO/klimadao/issues/514

Add Hindi to Site and App (Staging only)

---

site/lib/getBalances.ts

Correctly return `mco2` and `nct` balances from `getBalances`.
Also added `nbo` and `ubo` to the function :)

hotfix: fix getBalances

---

app/actions/offset.ts
app/actions/pklima.ts
app/actions/stake.ts
app/actions/utils.ts
app/actions/wrap.ts
app/components/views/Offset/index.tsx
app/components/views/PKlima/index.tsx
app/components/views/Stake/index.tsx
app/components/views/Wrap/index.tsx

This is another preparational PR for ticket #9 
This PR combines all "approval" actions into one as all use the same code.
Related to #9

Combine approval actions

---

lib/constants/index.ts

update sales and partnership urls

---

app/components/views/Offset/index.tsx
app/components/views/Offset/styles.ts
app/locale/en-pseudo/messages.po
app/locale/en/messages.po
site/locale/en-pseudo/messages.po

added lifi link to offset and updated copy

---

app/actions/wrap.ts
app/components/Modal/index.tsx
app/components/NotificationModal/index.tsx
app/components/TransactionModal/Approve.tsx
app/components/TransactionModal/HighlightValue.tsx
app/components/TransactionModal/Submit.tsx
app/components/TransactionModal/index.tsx
app/components/TransactionModal/styles.ts
app/components/views/Offset/index.tsx
app/components/views/Stake/index.tsx
app/components/views/Wrap/index.tsx
app/lib/getTokenInfo.ts
app/locale/en-pseudo/messages.po
app/locale/en/messages.po
lib/utils/getAllowance/index.ts
lib/utils/index.ts
site/locale/en-pseudo/messages.po

This PR replaces the current NotificationModal with a new Transaction Modal for the views **STAKE/UNSTAKE and OFFSET and WRAP**.
You can find the new modal under the preview link for **STAKE/UNSTAKE and OFFSET and WRAP**
You can reset your approvals here: https://polygonscan.com/tokenapprovalchecker for better testing.
- dynamic Modal title 
- show spender address
- show token icon and amount
- Fixed text for Approve and Submit (should match for all stake, wrap, offset)
- Views done: OFFSET, STAKE, WRAP ✅ 
- Views open: **PKLIMA** => no not maintained anymore, BONDS => follow-up PR
| APPROVE  | SUBMIT  |
|<img width="602" alt="" src="https://user-images.githubusercontent.com/95881624/182306203-88b45c4b-887e-4b07-a6f1-eb9c51a40f23.png">|<img width="582" alt="" …

New Transaction Modal

---

app/components/views/Info/index.tsx

Add UBO and NBO to /app info list
Resolves #589

app: add ubo and nbo to app info list

---

app/components/PageHead.tsx
site/components/PageHead/index.tsx

script tag updated. we still need to create a custom event goal in plausible for this to start tracking.
Resolves #565

add plausible script for outbound link tracking

---

site/components/pages/Retirements/SingleRetirement/DownloadCertificateButton/generateCertificate.ts

Link retirement transaction id to polygonscan
Resolves #623

Retirement Certificate: Link retirement tx to polygonscan

---

site/components/pages/Infinity/Cards/CardsSlider.tsx
site/components/pages/Resources/FeaturedArticles/Article.tsx
site/components/pages/Resources/FeaturedArticles/ArticlesSlider.tsx
site/components/pages/Resources/FeaturedArticles/styles.ts
site/components/pages/Resources/index.tsx
site/components/pages/Resources/styles.ts
site/hooks/useElementWidth/index.ts
site/lib/queries.ts
site/pages/resources/index.tsx

This is the next part of the new Resources page:
- build new slider for Resources Page
- query posts with flag "isFeaturedArticle"
- pass these articles to Slider
Part of https://github.com/KlimaDAO/klimadao/issues/534
See https://klimadao-site-git-resources-featured-articles-slider-klimadao.vercel.app/resources

Resources: Add Featured Articles slider

---

app/components/views/Offset/index.tsx
app/components/views/Stake/index.tsx
app/locale/en-pseudo/messages.po
app/locale/en/messages.po
lib/constants/index.ts
site/locale/en-pseudo/messages.po

added space and updated link sent in discord

adds space and updates lifi link

---

site/components/pages/Home/index.tsx
site/components/pages/Home/styles.ts

Adds the cta buttons for infinity and love letters
Resolves #597

add cta buttons on homepage

---

site/components/pages/Pledge/PledgeDashboard/Cards/AssetBalanceCard/TokenRow/styles.ts

add object-fit pledge token css

---

lib/theme/globals.css
lib/theme/variables.css
site/components/pages/Home/styles.ts
site/components/pages/Infinity/styles.ts

Pair programmed on this with @goatsOnDrugs 
Resolve some tough-to-debug issues related to how we use the --header-height variable on these views
Resolves #683
Resolves #680 (hopefully, I couldn't reproduce this one)
| ![image](https://user-images.githubusercontent.com/88635679/188993318-d28fea56-a451-474e-a59c-c9641b4295bc.png) | ![image](https://user-images.githubusercontent.com/88635679/188993278-9811b4b9-95ba-4637-8e53-8439dc1e188a.png) |
| ![image](https://user-images.githubusercontent.com/88635679/188993490-0b84d637-b8ce-4639-8450-4d30ecc78c05.png) | ![image](https://user-images.githubusercontent.com/88635679/188993565-f2b7ce98-b8aa-481b-8f64-1bbbe3ab168e.png) |
| ![image](https://user-images.githubusercontent.com/88635679/188993692-7b09e218-9 …

Home and Infinity layout fixes (header height issues)

---

site/components/pages/Infinity/index.tsx
site/components/pages/Infinity/styles.ts

add modal to cta section of infinity page

modal added to cta section of infinity

---

app/locale/en-pseudo/messages.po
site/components/Modal/index.tsx
site/components/Modal/styles.ts
site/components/pages/Infinity/GetStartedModal.tsx
site/locale/en-pseudo/messages.po
site/locale/en/messages.po

Modal bug fixes. Modal component title is no longer uppercase but capitalized and some copy updates.
Resolves #693

fix bugs in get started modal

---

app/components/ChangeLanguageButton/index.tsx
site/components/ChangeLanguageButton/index.tsx

Adds the Hindi langage menu item into app and site
Resolves #657
|![image](https://user-images.githubusercontent.com/11857992/190958883-cfcb236d-4993-4c75-bdd7-9e473bb7ea89.png)|![image](https://user-images.githubusercontent.com/11857992/190958785-62e5b44f-6ac6-4ea3-b6c0-484da0aae359.png)|
-->

Adds Hindi to languages

---

site/components/pages/Pledge/index.tsx
site/components/pages/Pledge/styles.ts
site/locale/en/messages.po

A couple of tweaks to the pledge landing page from @ShimonD-KlimaDAO's feedback.
Resolves #703
| Description | Screenshot |
| CTA buttons wrap on mobile | <img width="372" alt="image" src="https://user-images.githubusercontent.com/3889818/192144245-deb25d46-8574-4188-b798-5f2cfaf1318a.png"> |
| Search placeholder references KNS as an option | <img width="739" alt="image" src="https://user-images.githubusercontent.com/3889818/192144284-700b696a-fcac-416f-b6a1-83f247e7aa45.png"> |

Pledge landing page tweaks

---

app/components/ChangeLanguageButton/index.tsx
app/lib/i18n.ts
site/components/ChangeLanguageButton/index.tsx
site/lib/i18n.ts

Fixes hindi language menu button in production
Resolves #727
-->

Fixes hindi language menu button in production

---

lib/constants/index.ts

Update media request link url

---

lib/utils/useWeb3Modal/index.tsx

Fix an undocumented bug where the wallet disconnects on refresh -- I had disabled ccache because of a torus connect loop.
This adds caching back and fixes the loop by making sure to clear the cached provider *before* the disconnect event is fired. And use the Torus cleanUp() method.
Closes #649 (confirmed fixed)
Closes #723 (confirmed no)

Add wallet cache, fix torus loop

---

app/components/views/Offset/index.tsx

In the retirement message: this makes it easier to copy paste text.

[offset] use maxLength instead of returning void

---

site/components/pages/Pledge/PledgeDashboard/index.tsx
site/locale/en-pseudo/messages.po
site/locale/en/messages.po

[pledges] update pledge dashboard metatags

---

lib/theme/breakpoints.ts
lib/utils/getImageSizes/index.ts
site/components/pages/Buy/index.tsx
site/components/pages/Home/index.tsx
site/components/pages/Infinity/GetStartedModal.tsx
site/components/pages/Retirements/Footer/index.tsx
site/components/pages/Retirements/SingleRetirement/RetirementHeader/index.tsx
site/next.config.js

Image optimizations For Home, Buy, Retirements and Infinity getStarted Modal
Related to #696

Image optimizations

---

site/components/pages/About/Community/index.tsx
site/components/pages/About/Community/styles.ts

Image optimizations for community page
Adds a logo component to reduce code size
Very personal opinion: the discord image does not look good 
Related to #696

Image optimizations for community page

---

app/components/InvalidNetworkModal/index.tsx
app/components/InvalidNetworkModal/styles.ts
site/components/InvalidNetworkModal/index.tsx
site/components/InvalidNetworkModal/styles.ts

Resolves #794
| see ticket #794 | ![image](https://user-images.githubusercontent.com/88635679/202254567-39823f34-faa9-4dd3-82a9-24071d54cc07.png) |

fix lightmode color in InvalidNetworkModal

---

lib/utils/useWeb3Modal/index.tsx

add rpc to wallet connect. we can use infura id also

add rpc to wallet connect

---

lib/components/Web3Context/types.ts
lib/utils/useWeb3Modal/index.tsx

The bug was walletconnect expected `[chainId]: polygonRpcUrl` not just the url
Did some code cleanup as well. Reduced total lines of code, added some helpers for stronger typing plus don't need to assert `any` everywhere.

Fix WalletConnect, improve provider types

---

site/pages/pledge/[address].tsx

@ShimonD-KlimaDAO the retirements should show all of them added up now.
Resolves #870

fix retirements reducer

---

site/components/pages/Pledge/PledgeForm/index.tsx

add profileWebsiteUrl to form

---

app/components/views/Offset/index.tsx

hotfix: fix getAllowance

---

site/components/Header/styles.ts

quick fix for header height bug

---

lib/package.json
lib/utils/useProvider/index.tsx
package-lock.json
site/package.json

we broke the class constructer by destructuring like `{ makeWeb3Provider }` rather than saying `coinbaseWallet.makeWeb3Provider`
Resolves #702 and an undocumented coinbase bug

Fix coinbase

---

.prettierignore
cms/sanity.config.ts

Increase the speed of format-all

Add cms dist to prettier ignore

---

site/pages/api/pledge/index.ts

Use yup for pledges
Resolves #791

pledge enhancements

---

site/components/Header/styles.ts

revert the header height 100% css fix

revert header height 100

---

site/components/pages/Retirements/SingleRetirement/index.tsx

HOTFIX: tonnes formatting in retirement page

---

site/components/pages/Resources/ResourcesFilters/index.tsx
site/components/pages/Resources/ResourcesList/index.tsx
site/components/pages/Resources/SortyByDropDown/index.tsx
site/components/pages/Resources/lib/cmsDataMap.ts

I have no idea why this suddenly broke on both carbonmark and klimadao...

HOTFIX: fix strings

---

app/components/views/Home/index.tsx
app/lib/constants.ts
site/components/pages/Pledge/PledgeDashboard/index.tsx
site/components/pages/Pledge/PledgeForm/index.tsx
site/components/pages/Pledge/index.tsx
site/components/pages/Pledge/lib/formSchema.ts
site/components/pages/Pledge/lib/index.tsx
site/lib/constants.ts

HOTFIX: fix more strings

---

app/actions/redeem.ts
app/components/CarbonBalancesCard/index.tsx
app/components/CarbonBalancesCard/styles.ts
app/components/NavMenu/index.tsx
app/components/TransactionModal/Approve.tsx
app/components/TransactionModal/HighlightValue.tsx
app/components/TransactionModal/Submit.tsx
app/components/views/Home/index.tsx
app/components/views/Offset/SelectiveRetirement/index.tsx
app/components/views/Offset/SelectiveRetirementInput/index.tsx
app/components/views/Offset/SelectiveRetirementInput/styles.ts
app/components/views/Offset/index.tsx
app/components/views/Redeem/ProjectTokenDetails/index.tsx
app/components/views/Redeem/ProjectTokenDetails/styles.ts
app/components/views/Redeem/index.tsx
app/components/views/Redeem/styles.ts
app/lib/hooks/useRedeemParams.ts
app/locale/en-pseudo/messages.po
app/locale/en/messages.po
app/state/user/index.ts
lib/abi/KlimaRetirementAggregatorV2.json
lib/constants/index.ts
site/locale/en-pseudo/messages.po

Acquire carbon using USDC, KLIMA, or a pool token!
Closes #735

Selective redemption

---

app/components/Modal/styles.ts

max height and scroll for modal
Resolves #949

max height and scroll for modal

---

app/components/views/Offset/SelectiveRetirement/index.tsx
app/components/views/Offset/index.tsx

hotfix: fix projectAddress param and show project preview

---

lib/package.json
lib/utils/useProvider/index.tsx
package-lock.json

Hopefully fixes some RPC issues I'm seeing.

upgrade torus

---

app/components/views/Offset/SelectiveRetirement/index.tsx
app/components/views/Offset/index.tsx
app/components/views/Redeem/index.tsx
app/lib/hooks/useOffsetParams.ts
app/lib/hooks/useRedeemParams.ts

Offset & Redeem params improvements

---

app/components/views/Redeem/index.tsx

oops left a test button in there

remove test button

---

site/components/pages/Home/styles.ts

Improve CTO button alignment on mobile
Resolves #711
| Before | After |
|--------|-------|
|  ![image](https://user-images.githubusercontent.com/11857992/228782042-5a38958d-cec9-4d29-b7df-56e020d3800d.png)  |  ![image](https://user-images.githubusercontent.com/11857992/228781883-02650a49-4854-432e-8adb-fa5b39cd4f6b.png)  |

Improve CTO button alignment on mobile

---

carbonmark/lingui.config.js

woops! never set this up before merging repos.
Fix #1026

swap env vars for lingui

---

carbon-projects/sanity.cli.ts
carbon-projects/sanity.config.ts
carbon-projects/schemas/project.ts
carbonmark/components/pages/Project/index.tsx
carbonmark/components/pages/Project/styles.ts
carbonmark/lib/utils/functional.utils.ts
carbonmark/lib/utils/types.utils.ts
lib/constants/index.ts

Add a tag/pill for the registry in the project header
Resolves #991

Add registry tag to Project header (#991)

---

app/components/views/Info/index.tsx
app/components/views/Info/styles.ts

* add Icons
* add NCT
Resolves #350

add NCT and icons to info page

---

cms/schemas/post.js

change description on hideFromProduction schema

---

.github/workflows/update_translations.yml

Read the docs helps 😵‍💫 
Follow up on https://github.com/KlimaDAO/klimadao/issues/1058

Fix workflow value

---

carbonmark/components/pages/Users/Listing/index.tsx
carbonmark/components/pages/Users/Listing/styles.ts

Added links and key to profile page.  In the issue linking the activity projects is mentioned, but this is aspect addressed in PR #1067 
Resolves #996 
| <img width="648" alt="Screen Shot 2023-04-21 at 10 29 24 AM" src="https://user-images.githubusercontent.com/72105234/233665534-6e67cc0b-ff88-440c-88b6-241ae6480fd5.png"> | <img width="660" alt="Screen Shot 2023-04-21 at 10 29 32 AM" src="https://user-images.githubusercontent.com/72105234/233665444-ddc93fa8-de8c-4465-9ffd-b9a6776ea110.png"> |

Profile Enhancements #996

---

site/components/pages/Buy/index.tsx
site/locale/en-pseudo/messages.po
site/locale/en/messages.po

Test build: update a string and sync

---

README.md

Adds an architecture diagram to the README for easier orientation to KlimaDAO infrastructure
No changes to source code
Marked as draft until we review and make sure this diagram is clear and includes all important components

Add initial architecture diagram for KlimaDAO infra

---

carbonmark/components/LoginButton/index.tsx
carbonmark/components/pages/Project/BuyOptions/SellerListing.tsx
carbonmark/components/pages/Project/Purchase/PurchaseForm.tsx
carbonmark/lib/luckyOrange.ts

LuckyOrange Events 
LO.events.track('Login')
Note: Tracks only identified Carbonmark users
LO.visitor.identify('wallet', { user: 'username', name: 'Display Name' })
Note: Tracks only identified Carbonmark  users
LO.events.track('Purchase: Buy Clicked')
LO.events.track('Purchase: Continue Clicked')
Note: Triggers only if the form is valid.
LO.events.track('Purchase: Approve Clicked')
LO.events.track('Purchase: Submit Clicked')
LO.events.track('Purchase: Purchase Completed')
LO.events.track('Purchase: Purchase Modal Closed')
LO.events.track('Retire: Retire Button Clicked')
LO.events.track('Listing: Sell Clicked')
LO.events.track('Listing: Approve Clicked')
LO.events.track('Listing: Listing Created')
LO.events.track('Listing: Edit Clicked')
LO.events.track('Listing: Updated') …

Basic Lucky Orange tracking

---

app/components/views/Offset/index.tsx

Same mistake as made on the approval side in https://github.com/KlimaDAO/klimadao/commit/605b932d6513c3139b22fbfbed3cbe356e979fc2

Fix overflow math issue

---

carbonmark/components/LoginButton/index.tsx
carbonmark/components/UserTracker/index.tsx
carbonmark/components/pages/Portfolio/AssetProject/index.tsx
carbonmark/components/pages/Project/BuyOptions/PoolPrice.tsx
carbonmark/components/pages/Project/BuyOptions/SellerListing.tsx
carbonmark/components/pages/Project/Purchase/index.tsx
carbonmark/lib/luckyOrange.ts
carbonmark/pages/_app.tsx
lib/components/Buttons/ButtonBase.tsx

Luckyrange tracking features
- Fixes tracking of login when the login button is not present
- Completes tracking for the Purchase workflow
Resolves: #1086
|NA |NA|
-->

DRAFT: LuckyOrange login and purchase tracking bug fixes

---

carbonmark/components/UserTracker/index.tsx
carbonmark/lib/luckyOrange.ts

Fixes user identification in LuckyOrange
Resolves #1086 
NA

Luckyorange: Fix user identification

---

carbonmark/components/pages/Project/Purchase/TotalValues.tsx

See this comment https://github.com/KlimaDAO/klimadao/issues/1148#issuecomment-1557707708
Again
Closes https://github.com/KlimaDAO/klimadao/issues/1148

remove payment method label text

---

app/locale/en-pseudo/messages.po
carbonmark/locale/en-pseudo/messages.po
site/components/pages/Home/index.tsx
site/locale/en-pseudo/messages.po
site/locale/en/messages.po

Make content changes to website based on the comments in #1157.
Resolves #1157

0xMakka/1157 - make content changes to klimadao website

---

examples/nextjs-typescript-integration/README.md
examples/nextjs-typescript-integration/app/page.tsx
examples/nextjs-typescript-integration/package-lock.json

NextJS example: Update docs and package-lock

---

carbonmark/components/pages/Blog/Post/index.tsx
carbonmark/components/pages/Resources/BlogPostCard/index.tsx
carbonmark/components/pages/Resources/PortableTextRenderer/index.tsx
carbonmark/components/pages/Resources/PortableTextRenderer/styles.ts
package-lock.json
site/components/PodcastCard/index.tsx
site/components/pages/Blog/Post/index.tsx
site/components/pages/Resources/FeaturedArticles/Article.tsx

change date format and listItem font size

---

app/locale/en-pseudo/messages.po
carbonmark/components/pages/Retirements/SingleRetirement/ShareDetails/index.tsx
carbonmark/components/pages/Retirements/SingleRetirement/ShareDetails/styles.ts
carbonmark/locale/en-pseudo/messages.po
carbonmark/locale/en/messages.po
site/locale/en-pseudo/messages.po

Fixes an issue where "Download PDF" button isn't showing when there is no beneficiary. Also, based on previous feedback from @Atmosfearful, inlined the button as we no longer need to lazy load the button.
Resolves issue 1 mentioned in #1188 by @jabby09

fix issue where download pdf button not shown when no beneficiary

---

carbonmark/components/pages/Project/Retire/RetireInputs.tsx
carbonmark/lib/actions.retire.ts

Super tiny fix:
Better to validate if the beneficiary address is valid as this value is passed to the method "getTotalRetirements"
None

Small fixes: Validate beneficiary, better code

---

app/locale/en-pseudo/messages.po
carbonmark/components/pages/Home/index.tsx
carbonmark/components/pages/Project/index.tsx
carbonmark/components/pages/Project/styles.ts
carbonmark/components/pages/Projects/index.tsx
carbonmark/components/pages/Retirements/SingleRetirement/ProjectDetails/index.tsx
carbonmark/components/pages/Retirements/SingleRetirement/ProjectDetails/styles.ts
carbonmark/components/pages/Retirements/SingleRetirement/index.tsx
carbonmark/lib/types/carbonmark.ts
carbonmark/locale/en-pseudo/messages.po
carbonmark/locale/en/messages.po
site/locale/en-pseudo/messages.po

Replace the description field with short description on /projects view and long description on /projects/{projectId} views.
Resolves #1149

0xMakka - replace description with short/long_description

---

carbonmark-api/constants/constants.js
carbonmark-api/postman_collection.json
carbonmark-api/routes/projects.js

- add support for default tokens

Cherry from carbonmark-api and format-all

---

carbonmark/pages/index.tsx

Change one of the featured projects on the Carbonmark landing page.
Resolves #1229 
|<img width="1000" alt="Screenshot 2023-06-20 at 19 49 11" src="https://github.com/KlimaDAO/klimadao/assets/92357475/50b47191-cedd-4142-9d27-6c97d92ebb98">|<img width="1000" alt="Screenshot 2023-06-20 at 19 49 21" src="https://github.com/KlimaDAO/klimadao/assets/92357475/c0ec941f-b88b-4856-be12-fcbbdcdcbbeb">|

0xMakka - #1229 replace featured project on homepage

---

carbonmark/components/pages/Portfolio/AssetProject/index.tsx
carbonmark/components/pages/Users/SellerConnected/index.tsx

disable SELL and CREATE NEW LISTING with tooltip

---

app/locale/en-pseudo/messages.po
carbonmark/components/ChangeLanguageButton/index.tsx
carbonmark/components/ChangeLanguageButton/styles.ts
carbonmark/components/Layout/NavDrawer/index.tsx
carbonmark/components/LoginButton/index.tsx
carbonmark/components/pages/Home/index.tsx
carbonmark/components/pages/Project/ProjectsController/index.tsx
carbonmark/components/pages/Project/index.tsx
carbonmark/components/pages/Resources/BlogPostCard/index.tsx
carbonmark/components/pages/Resources/FeaturedArticles/Article.tsx
carbonmark/components/shared/Header/styles.ts
carbonmark/components/shared/Navigation/index.tsx
carbonmark/locale/en-pseudo/messages.po
carbonmark/locale/en/messages.po
carbonmark/next.config.js
carbonmark/pages/_app.tsx
site/locale/en-pseudo/messages.po

Adds a language switcher to the homepage header and the header in the carbonmark app.
Resolves #1183

0xMakka / #1183 language switcher

---

app/components/views/Offset/index.tsx

Fix #1252 Don't add slippage when retiring same token

---

carbonmark/components/Card/styles.ts
carbonmark/components/pages/Project/ProjectHeader/index.tsx
carbonmark/components/pages/Project/ProjectHeader/styles.ts
carbonmark/components/pages/Project/Purchase/styles.ts
carbonmark/components/pages/Project/Retire/styles.ts

Align project header images across all devices. Added some fixes for inconsistent styles based of the following figma styles - https://www.figma.com/file/0vb829fJKYWWKszeSOvTTN/Carbonmark-Design-System?node-id=877%3A760&mode=dev
Resolves #1217 
|<img width="1512" alt="Screenshot 2023-07-03 at 08 10 15" src="https://github.com/KlimaDAO/klimadao/assets/92357475/3149bb45-dd58-46fd-902a-5faaf365add3">|<img width="1512" alt="Screenshot 2023-07-03 at 08 08 36" src="https://github.com/KlimaDAO/klimadao/assets/92357475/95b9ad36-7948-4330-a514-55e2e4d4dbac">|
|<img width="365" alt="Screenshot 2023-07-03 at 08 11 06" src="https://github.com/KlimaDAO/klimadao/assets/92357475/abc99998-f9c2-4cc4-a6cf-a44ab5f99539">|<img width="364" alt="Screenshot 2023-07-03 …

0xMakka/1217 - align project header images

---

.github/workflows/deploy_carbonmark_api.yml

Fix an incorrect github secret label

chore: Update VERCEL_PROJECT_ID in deploy_carbonmark_api.yml

---

carbonmark-api/src/routes/projects/get.ts
carbonmark-api/src/utils/helpers/utils.ts
carbonmark/components/pages/Projects/index.tsx

Refactor how we fetch pool prices on the backend. Return formatted values. This code still needs a major refactor. But I did remove a large chunk of code as I was able to reuse a util from `getById`. This reduces total network requests, but removes caching.
Resolves #1259 
Resolves #1300
Related to #1325

[API] Fix and simplify pricing from /projects endpoint

---

carbonmark/components/ProjectCard/styles.ts
carbonmark/components/pages/Retire/FromPortfolio/index.tsx

See https://github.com/KlimaDAO/klimadao/issues/1346
Closes https://github.com/KlimaDAO/klimadao/issues/1346

Retire page improvements

---

carbonmark-api/src/routes/projects/get.ts

Quick hotfix to resolve missing project descriptions. A cleanup solution will follow.
Resolves #1395

hotfix:1395 quick fix to resolve missing descriptions in projects

---

lib/constants/index.ts
site/components/Navigation/index.tsx

remove loveletters

---

carbonmark-data/app/[locale]/layout.tsx
carbonmark-data/app/[locale]/overview/page.tsx
carbonmark-data/components/charts/DigitalCarbonPricingChart.tsx
carbonmark-data/components/charts/VerraCredits/Chart.tsx
carbonmark-data/lib/charts/getVerraCredits.ts
carbonmark-data/lib/charts/helpers.ts
carbonmark-data/lib/charts/queries.ts
carbonmark-data/lib/charts/types.ts
carbonmark-data/lib/constants.ts
carbonmark-data/theme/typography.ts

Fixes compile errors and improves data typing
NA
NA

Fixes compile errors and improves data typing

---

package-lock.json
package.json

Attempt to fix GHA issue on staging

add lingui CLI to root package.json

---

carbonmark/components/pages/Projects/ProjectView/GridView.tsx
carbonmark/components/pages/Projects/ProjectView/styles.ts

fix project cards once more 🙃

---

carbonmark-data/app/[locale]/details/verra-credits-over-time/page.tsx
carbonmark-data/components/cards/ChartCard/styles.ts
carbonmark-data/components/pages/DetailPage/index.tsx
carbonmark-data/components/pages/DetailPage/styles.module.scss
carbonmark-data/package.json
package-lock.json

DRAFT: implement details layout

---

carbonmark-data/README.md
carbonmark-data/lib/charts/helpers.ts
carbonmark-data/lib/charts/queries.ts
carbonmark-data/lib/constants.ts
carbonmark-data/theme/palette.ts

Prevents carbonmark-data from failing on network errors by catching errors and providing failsafe data
NA
NA

Prevent carbonmark-data from failing on network errors

---

carbonmark-data/app/[locale]/globals.css
carbonmark-data/components/ChangeLanguageButton/styles.module.scss
carbonmark-data/components/Layout/style.module.scss
carbonmark-data/components/OptionsSwitcher/styles.module.scss
carbonmark-data/components/Skeleton/styles.module.scss
carbonmark-data/components/cards/ChartCard/styles.module.scss
carbonmark-data/components/charts/DailyCreditsChart/Chart.tsx
carbonmark-data/components/charts/HistoricalPriceChart/Chart.tsx
carbonmark-data/components/charts/helpers/styles.module.scss
carbonmark-data/components/pages/DetailPage/styles.module.scss
carbonmark-data/theme/layout.module.scss

cleanup carbonmark-data css

---

carbonmark-data/package.json

purge emotion dependencies

---

carbonmark-api/src/.generated/types/marketplace.types.ts
carbonmark-api/src/.generated/types/marketplaceMumbai.types.ts
carbonmark-api/src/graphql/marketplace.gql
carbonmark-api/src/graphql/marketplaceMumbai.gql
carbonmark-api/src/utils/helpers/fetchMarketplaceListings.ts

Closes #1490 
Required before we can merge #1579

#1490 Refactor(/projects/:id) only fetch unexpired listings

---

carbonmark-api/package.json
carbonmark-api/src/routes/projects/[id]/get.schema.ts
carbonmark-api/src/routes/projects/[id]/get.ts
package-lock.json

Hacky fix going straight to staging. This issue will not appear when we get a mainnet graph url for marketplace. We will need to remove this hack fix though.
explanation: gql_sdk on polygon is pulling from mumbai's subgraph.

Hotfix #1604

---

carbonmark/.generated/carbonmark-api.schema.ts
carbonmark/lib/constants.ts

[carbonmark] chore: upgrade to v2.0.0-1

---

carbonmark/package.json
package-lock.json

ts-node was giving us problems, tsx works great.

Replace ts-node with tsx for generate-types

---

carbonmark-api/package.json
carbonmark-api/src/models/Purchase.model.ts
carbonmark-api/src/routes/purchases/[id]/get.ts
carbonmark-api/test/fixtures/marketplace.ts
carbonmark-api/test/routes/purchases/get.test.ts
package-lock.json

[api] Fix #1602 - Format bignumber strings for /purchases endpoint

---

carbonmark-api/src/routes/projects/get.schema.ts
carbonmark-api/src/routes/projects/get.ts
carbonmark-api/src/routes/users/get.schema.ts
carbonmark-api/test/routes/projects/get.test.ts

fix #1632 - remove expiresAfter default from get.schema.ts

---

carbonmark-api/package.json
carbonmark-api/src/routes/users/get.ts
package-lock.json

Related to #1631 
No issue ticket
increment v2.0.0-6

[api] hide mumbai activity from /users endpoint (temp fix)

---

carbon/components/Layout/Footer.tsx
lib/constants/index.ts

add link urls for footer

---

carbonmark-api/package.json
carbonmark-api/src/app.constants.ts
package-lock.json

To be released for FE consumption

Upgrade marketplace mumbai subgraph and increment api v2.0.0-7

---

carbonmark/components/pages/Users/Badge/index.tsx
carbonmark/components/pages/Users/Badge/styles.ts
carbonmark/components/pages/Users/Listing/index.tsx
carbonmark/components/pages/Users/Listing/styles.ts
carbonmark/components/pages/Users/SellerConnected/Forms/EditListing.tsx
carbonmark/components/pages/Users/SellerConnected/Forms/styles.ts
carbonmark/lib/actions.ts
carbonmark/lib/utils/listings.utils.ts
carbonmark/locale/en-pseudo/messages.po
carbonmark/locale/en/messages.po

Edit: Atmos came in and wired it up :) safe to merge now.
Resolves #1525

Makka / #1525 - add initial ui badges for invalid/expired listings

---

carbonmark-api/src/.generated/types/marketplace.types.ts
carbonmark-api/src/graphql/marketplace.gql

limit 10 most recent (5 are shown in the ui)

order and limit project.activities

---

README.md

Updates node requirements in README.md

Update node requirements in README.md

---

carbon/locale/en-pseudo/messages.po
carbon/locale/en/messages.po
carbonmark/components/CreateListing/index.tsx
carbonmark/components/pages/Users/SellerConnected/ListingEditable.tsx
carbonmark/locale/en-pseudo/messages.po
carbonmark/locale/en/messages.po

fix #1670 change amount label render

---

carbonmark/components/pages/Project/Purchase/Listing/PurchaseForm.tsx
carbonmark/lib/actions.ts
carbonmark/lib/networkAware/getTokenDecimals.ts
lib/utils/getAllowance/index.ts
lib/utils/getTokenDecimals/index.ts

Was not fetching the testnet approval (forgot to pass network label down)
Submit was not passing the correct singleUnitPrice down to the contract (Was passing complete price instead)
Fixes #1673 
Fixes #1672 (I hope)

Fix #1673 - listing purchase form bugs

---

carbonmark-api/package.json
carbonmark-api/src/.generated/types/marketplace.types.ts
carbonmark-api/src/graphql/marketplace.gql
carbonmark-api/src/models/Purchase.model.ts
carbonmark-api/src/routes/purchases/[id]/get.ts
carbonmark-api/test/fixtures/marketplace.ts
carbonmark-api/test/routes/purchases/get.test.ts
package-lock.json

Missing data made it impossible to ship #1660

[api] Release v2.0.0-9 and add data to `getPurchaseById` query

---

carbonmark/.generated/carbonmark-api.schema.ts
carbonmark/lib/api/client.ts
carbonmark/lib/constants.ts

increment api version and generate:types

chore(carbonmark): upgrade to consume v2.0.0-9

---

.github/workflows/update_translations.yml

`push_to_staging` is failing because of missing `TRANSLATIONIO_KEY_CARBON_DATA` secret https://github.com/KlimaDAO/klimadao/actions/runs/6522779737/job/17712703637

Attempt to fix push to staging

---

carbon/app/[locale]/registry.tsx
carbon/components/Layout/DesktopSidebarItem.tsx
carbon/components/Layout/LayoutClientWrapper.tsx
carbon/components/Layout/MobileBottomNavItem.tsx
carbon/components/Layout/index.tsx
carbon/components/PageHeader/BackButton.tsx
carbon/components/PageHeader/PageHeader.tsx
carbon/components/charts/helpers/ChartWrapper/index.tsx
carbon/components/charts/helpers/NoDataWrapper/index.tsx
carbon/components/charts/helpers/PolygonscanLink/styles.module.scss
carbon/components/charts/helpers/VerraProjectLink/styles.module.scss
carbon/hooks/useIsPathnameActive/index.ts
carbon/lib/charts/aggregators/getAggregatedCredits.ts

- Optimize SSR for the carbon module
- Leverage cache for time based queries
Resolves #1484 

Optimize SSR for the carbon dashboard app

---

carbonmark/.generated/carbonmark-api.schema.ts
carbonmark/lib/constants.ts

chore: upgrade to v2.0.0-10

---

carbon/components/PageHeader/PageHeader.tsx

This PR fixes the URL for the "Explore Marketplace" button.
Resolves #1703

carbon: fix url for explore marketplace button

---

carbonmark/components/pages/Home/index.tsx

Update href of create profile button on carbonmark homepage.
Resolves #1742

Makka / #1742 change location of create profile button

---

app/components/DisclaimerModal/index.tsx
app/components/DisclaimerModal/styles.ts
app/components/views/Buy/index.tsx
app/components/views/ChooseBond/index.tsx
app/components/views/Stake/index.tsx
app/components/views/Wrap/index.tsx
app/locale/en-pseudo/messages.po
app/locale/en/messages.po

Adds a disclaimer modal to Buy, Stake, Bonds & Wrap views. 
Resolves #1741

Makka / #1741 add disclaimer modal

---

carbonmark-api/package.json
carbonmark-api/src/app.constants.ts
package-lock.json

Update mumba subgraph URL and increment package.json version

[api] v2.0.0-11 new mumbai subgraph url

---

carbon/app/[locale]/details/verra-credits-retired-by-project-type/page.tsx
carbon/app/[locale]/details/verra-credits-retired-by-vintage-date/page.tsx
carbon/app/[locale]/details/verra-credits-retired-off-chain-over-time/page.tsx
carbon/app/[locale]/details/verra-credits-retired-on-chain-over-time/page.tsx

Fix Off vs On chain details cards for retired credits
Resolves #1736

[klima data] carbon: Fix Off vs On chain details cards for retired credits

---

carbon/app/[locale]/supply/page.tsx
carbon/theme/layout.module.scss

Fix supply page layout
Resolves #1744 
|![image](https://github.com/KlimaDAO/klimadao/assets/11857992/5860ce25-999c-4316-ba41-723e794f9dfe) |![image](https://github.com/KlimaDAO/klimadao/assets/11857992/834c007d-3340-4aa6-988b-244c2279184f)|

[klima data] Fix supply page layout

---

carbonmark/.generated/carbonmark-api.schema.ts
carbonmark/lib/constants.ts

Includes new subgraph version with fixes
Resolves #1655

chore(carbonmark): upgrade to v2.0.0-13

---

carbonmark-api/README.md

Updates `/carbonmark-api/README.md` with:
1. Release information
2. Type generation
3. Other stuff

Update carbonmark-api README

---

carbon/components/charts/helpers/DataTable/DataTableClientWrapper/index.tsx
carbon/components/charts/helpers/DataTable/DataTableClientWrapper/styles.module.scss
carbon/components/charts/helpers/DataTable/configurations/styles.module.scss

Resolves #1799
After and before adding scrolling support with fixed pagination controls:
After and before single column table rendering fixes:

make tables scrollable on mobile

---

carbonmark/components/pages/Home/index.tsx
carbonmark/locale/en-pseudo/messages.po
carbonmark/locale/en/messages.po
lib/constants/index.ts

Change text to `REQUEST DEMO` and link to an external form.
Resolves #1815

Makka / #1815 change text & link to external form

---

carbon/components/cards/overview/TokensPriceCard/index.tsx
carbon/components/cards/overview/TokensPriceCard/styles.module.scss
carbon/components/charts/helpers/CoinTiles/index.tsx
carbon/components/charts/helpers/CoinTiles/styles.module.scss

carbon: make the whole fact clickable

---

carbonmark/.generated/carbonmark-api.schema.ts
carbonmark/lib/constants.ts

Upgrade to v2.0.0-14

---

carbonmark-api/package.json
carbonmark-api/src/routes/projects/[id]/get.ts
carbonmark-api/src/routes/users/get.ts
carbonmark/components/CreateListing/index.tsx
carbonmark/components/pages/Users/SellerConnected/ListingEditable.tsx
package-lock.json

Remove the temporary hotfix that was hiding polygon listings & activities
Fix a mistake in the CreateListing and edit listing modal labels

Fixes for createListing modal & api/users

---

app/components/views/Home/index.tsx
carbonmark/components/Layout/index.tsx
lib/components/ConnectModal/index.tsx
lib/components/Web3Context/types.ts
site/components/pages/Pledge/PledgeDashboard/index.tsx
site/components/pages/Pledge/index.tsx

This PR removes the institutional login section from our login dialog.
Resolves #1822

remove institutional logins from dialog

---

carbonmark/lib/constants.ts

[carbonmark] Re-enable listings on production

---

carbon/app/[locale]/token-details/pool-volume-deposited-over-time/[bridge]/page.tsx
carbon/app/[locale]/token-details/pool-volume-redeemed-over-time/[bridge]/page.tsx
carbon/app/[locale]/token-details/pool-volume-retired-over-time/[bridge]/page.tsx
carbon/components/cards/tokenDetails/PoolVolumeOverTimeCard/index.tsx
carbon/components/cards/tokenDetails/helpers.ts
carbon/components/pages/TokenDetailsDetailPage/index.tsx
carbon/components/pages/props.ts
carbon/lib/pools.tsx
carbon/locale/de/messages.po
carbon/locale/en-pseudo/messages.po
carbon/locale/en/messages.po
carbon/locale/es/messages.po
carbon/locale/fr/messages.po
carbon/locale/hi/messages.po
carbon/locale/ko/messages.po
carbon/locale/ru/messages.po
carbon/locale/zh-CN/messages.po

Fixes details link for pool deposited, retired and redeemed cards
Resolves #1855

carbon: fix details link for pool deposited, retired and redeemed cards

---

carbon/app/[locale]/token-details/token-by-methodologies/[bridge]/page.tsx

Fix translations for token-by-methodologies page

carbon: Fix translations for token-by-methodologies page

---

.github/workflows/release_carbonmark_api.yml

Released versions of the api should be using prod variables

use prod vars for API releases

---

carbonmark-api/src/plugins/open-api.ts
carbonmark/.generated/carbonmark-api.schema.ts
carbonmark/lib/constants.ts

chore(carbonmark): upgrade api v2.0.0

---

.github/workflows/release_carbonmark_api.yml

This pr failed to resolve the issue #1871 to fix related ticket #1870

Fix: use vercel --prod for api releases

---

carbon/app/[locale]/layout.tsx
carbon/app/[locale]/page.tsx

Fix metadata generation for index page
Resolves #1868

[klima data]: fix metadata generation for index page

---

carbon/app/[locale]/overview/page.tsx

fix lower case digital carbon market

---

carbon/components/pages/retirementTrends/TwoColumnRetirementTrendsTab/index.tsx
carbon/theme/layout.module.scss

carbon: rightsize retirement trends page

---

carbonmark-api/README.md
carbonmark-api/package.json
carbonmark-api/src/routes/projects/get.constants.ts
carbonmark-api/src/utils/helpers/fetchAllPoolPrices.ts
carbonmark-api/src/utils/helpers/fetchPoolPricesAndStats.ts

Fix selective redemption price computation API side. Another PR will be needed to use these updated prices on the frontend
#1394

[API] Fix selective redemption price

---

carbonmark-api/test/fixtures/tokens.ts
carbonmark-api/test/routes/projects/[id]/get.test.ts

Add tests for fees calculation
Resolves #1394

API: Add tests for fees calculation

---

carbonmark/pages/users/[user].tsx

Prevent fetching carbonmark user from api from failing when rendering the profile page
Resolves #1911

Carbonmark: Prevent carbonmark user fetch from api from failing

---

carbonmark/components/shared/Header/styles.ts
carbonmark/components/shared/Navigation/ToggleNavButton.tsx
carbonmark/components/shared/Navigation/styles.ts
carbonmark/package.json
package-lock.json

This PR fixes the glitchy hamburger animation. It installs a new package so we should probably discuss if it's worth it or not.
Resolves #1445

[navigation] fix hamburger animation

---

carbonmark/components/pages/Users/SellerConnected/Forms/EditProfile.tsx

We were incorrectly accessing the error status code with the new kubb hooks

fix:1951 error.status -> error.data.statusCode

---

carbonmark-api/package.json
package-lock.json

Releases API version 2.0.2
Related to #1966
- 
- 
Other notes:
-

Increase API version to 2.0.2

---

carbonmark-api/README.md

Add some documentation as to how preview deployments of the API work and how to develop locally against a specific version

chore: document api deployment and preview process

---

carbon-projects/schemas/methodology.ts

Didn't realize this category was missing 😓

Add missing agriculture category to CMS

---

app/locale/en-pseudo/messages.po
app/locale/en/messages.po
carbon/locale/en-pseudo/messages.po
carbon/locale/en/messages.po
carbonmark/components/CreateListing/Transaction/Approve.tsx
carbonmark/locale/en-pseudo/messages.po
carbonmark/locale/en/messages.po
site/locale/en-pseudo/messages.po
site/locale/en/messages.po

Revises the approval modal text to add context regarding ICR tokens setApprovalForAll 
Closes #1989

revised approval modal copy for ICR tokens

---

carbonmark/components/pages/Project/Purchase/index.tsx
carbonmark/components/pages/Project/Purchase/styles.ts
carbonmark/components/pages/Project/Retire/index.tsx
carbonmark/components/pages/Project/Retire/styles.ts

This PR makes the full area of the "Back to Project" button clickable. It also aligns the arrow and the text.
Closes #2037

fix back to project button

---

carbonmark/components/Activities/Activity.tsx
carbonmark/components/Activities/styles.ts

This PR fixes general problems with the activity feed:
* Adds the `t` to quantities for quantity updates
* Makes the UI look more like the figma design in general
|Before|After|
|---|---|
|<img width="360" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/b08985cc-c191-4b73-a123-185d51d2661c">|<img width="346" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/782b0fef-b346-464e-92b7-b25db47eca31">|
|<img width="155" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/e63d4b58-4dad-4539-97e1-dfdf139244fb">|<img width="174" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/3959d4a8-7382-438e-a5fd-f1628df5ec94">|
Closes #2039

fix activity designs

---

lib/constants/index.ts

The current subgraph id is broken (indexing failed). Updating with new synced subgraph id with fix.
Related to https://github.com/KlimaDAO/klimadao/pull/2115

[APP] Update carbonmark subgraph id

---

carbonmark/components/pages/Retire/Activity/Overview.tsx
carbonmark/components/pages/Retirements/List/Item.tsx
carbonmark/components/pages/Retirements/SingleRetirement/index.tsx
carbonmark/lib/retirementDataQueries/retirementDataViaPolygonDigitalCarbon.ts
carbonmark/pages/api/certificates/[beneficiaryAddress]/[retirementIndex]/index.ts
carbonmark/pages/api/retirements/[beneficiary_address]/index.ts
carbonmark/pages/retirements/[beneficiary]/index.tsx

Fixes retirement quantities bug for overview and total carbon retired.
Creating issue to track improvements discovered by this issue.
Closes #2123

Fix Retirement Quantities

---

examples/nextjs-typescript-integration/abis/KlimaRetirementAggregatorV2.json
lib/abi/KlimaRetirementAggregatorV2.json

This PR applies the current ABI state to the json representation.
Closes #2170

Add missing functions to abi

---

carbonmark/lib/retirementCertificates/index.ts

Fixes Vintage in certificates
Closes #2190 
1. Go to https://carbonmark-git-biwano-fix2190-klimadao.vercel.app/retirements/0xd8bdc5a83c7587b66d36da8ed761184a91370fea/4
2. Click on Download PDF
3. Verify that vintage is correct
4. Try with other retirements
-

Fix vintage in certificates

---

carbon/components/cards/retirementTrends/RetirementsByChainChartCard/index.tsx
carbon/components/cards/retirementTrends/RetirementsByChainListCard/index.tsx

Just fixing some unclear copy that is causing confusion
Opened this as a one-off since it's a quick fix
Read
- Just the text on one page of the KlimaData Retirement Trends page
- 
Other notes:
-

Fix unclear copy

---

carbonmark/components/pages/Retirements/SingleRetirement/BeneficiaryDetails/index.tsx
carbonmark/components/pages/Retirements/SingleRetirement/BeneficiaryDetails/styles.ts
carbonmark/components/pages/Retirements/SingleRetirement/TransactionDetails/index.tsx
carbonmark/components/pages/Retirements/SingleRetirement/TransactionDetails/styles.ts

Fix css issues relating to text wrapping on mobile ticket #2133
Closes #2133

fix wrapping issues

---

app/locale/en-pseudo/messages.po
app/locale/en/messages.po
carbon/locale/en-pseudo/messages.po
carbon/locale/en/messages.po
carbonmark/components/Footer/index.tsx
carbonmark/components/Footer/styles.ts
carbonmark/components/Layout/styles.ts
carbonmark/locale/en-pseudo/messages.po
carbonmark/locale/en/messages.po

Add code of ethics link to the footer.
Closes #2268 
1. Verify the code of ethics link navigates to [carbonmark.com/blog/code-of-ethics](https://www.carbonmark.com/blog/code-of-ethics)
2. Verify it doesn't break the footer layout on mobile/desktop

[CM] Add code of ethics link to footer

---

carbonmark/components/pages/Retirements/SingleRetirement/BeneficiaryDetails/index.tsx
carbonmark/components/pages/Retirements/SingleRetirement/index.tsx

Closes #2241 
1. Visit https://carbonmark-git-biwano-fixbeneficiarydisplay-klimadao.vercel.app/retirements/0x061138CBfEA4531D9ae118e36B86e7CD27649523/5
2. Check that beneficiary name is 'beneficiary name'
3. Download the certificate.
4. Check that beneficiary name is 'beneficiary name'
- View single retirement

Fix beneficiary name

---

carbon-projects/schemas/methodology.ts

Whoops, forgot to include these new categories in the mapping

Add missing categories for carbon projects

---

carbon-projects/schemas/project.ts

So we can support J-Credit project data in CMS

Add registry for J-Credits to options

---

app/components/views/Info/index.tsx

This PR fixes the hardcoded & untyped paths and replaces them with proper imports so they work again.

fix pool icon paths for klima app

---

.github/actions/check-status/.eslintrc.json
.github/actions/check-status/__tests__/poll.test.ts
.github/actions/check-status/action.yml
.github/actions/check-status/jest.config.js
.github/actions/check-status/package-lock.json
.github/actions/check-status/package.json
.github/actions/check-status/src/main.ts
.github/actions/check-status/src/poll.ts
.github/actions/check-status/src/status-api.result.ts
.github/actions/check-status/src/wait.ts
.github/actions/check-status/tsconfig.json
.github/actions/scripts/merge_staging.sh
.github/workflows/schedule_auto_merge.yml
.github/workflows/wait_for_status_check.yml

These were removed in https://github.com/KlimaDAO/klimadao/pull/2343

Add auto-merge workflows and actions

---

base/components/pages/Home/styles.ts
base/styles/globals.css

This PR fixes width of the main container when viewed on mobile.

fix styles on mobile

---

app/middleware.ts
app/package.json
package-lock.json

Geoblock Rogue States

---

.github/workflows/check_formatting.yml

Prettier GH action is currently failing. This fix is based off a fix made in carbonmark for a similar issue.

fix prettier gh action

---

app/components/NavMenu/index.tsx
app/components/NavMenu/styles.ts
app/locale/en-pseudo/messages.po
app/locale/en/messages.po
base/components/pages/Home/index.tsx
base/components/pages/Home/styles.ts

This PR includes changes discussed in discord to base, i.e.
- Add a "Retire on base" button in the main KD dApp.
- Emphasise the "proof-of-concept" text

base updates

---

app/actions/pklima.ts
app/components/views/PKlima/index.tsx

Some views were missing a comparison to trigger the Approval flow.

Fix approvals

---

carbon-projects/schemas/objects/externalFile.ts

To facilitate rich document section on project detail pages
Simple addition of new fields, shouldn't be any impact downstream

Add new fields to externalFile type

---

carbon-projects/lib/categories.ts

Add new categories discussed in Discord to CMS

Add new categories

---

carbon-projects/lib/fileCategories.ts

After a discussion with @jabby09 - the file categories need to be aligned with the current[ figma designs ](https://www.figma.com/design/5GewbdVaM1Q06CwHmF7d3F/Projects?node-id=4191-40749&t=ExoFkw01gVPMFvEP-0)

[CM] align file categories with figma designs

---

carbon-projects/schemas/projectContent.ts

To support rich formatting for long descriptions

Add separate block-type long description field

---

base/lib/constants.ts
base/pages/_app.tsx

use jsonRpcUrl
create new quicknode rpc endpoint and add to env vars
it's whitelisted to only accept requests from base.klimadao.finance

fix: rate limit

---

base/.env.example
base/hooks/useBeefyVaultsData.ts
base/hooks/useLpPrices.ts
base/lib/constants.ts
base/pages/_app.tsx

Issue was not resolved in #2426 due to badly formatted ENV vars
In this PR I also played with multicall to see if it improves performance / reduced api calls.
I switched to alchemy as it wasn't clear that quicknode was supporting multicall (in hindsight I believe either works fine)

fix: use multicall and alchemy
