KlimaDAO/klimadao

app/components/views/Bond/index.tsx
Prevent the "you will get" field from changing after they click "Bond"
=> Fix #34 - Only reset bond quote quantity after bond txn success

app/components/CheckURLBanner/index.module.css, app/components/CheckURLBanner/index.tsx, app/components/views/Home/index.tsx
This PR adds a full-width top-page banner to DApp.
The banner is rendered by default on initial load.
The area below the banner is not clickable.
The button "Got it" closes the banner.
Closing the banner is not stored in a browser session cookie as mentioned [here](https://github.com/KlimaDAO/klimadao/issues/48#issuecomment-997192921).
Instead, the value is stored in the local React Component's state.
Therefore the banner is shown again as soon as the page is reloaded/revisited again.
I can imagine that this can be annoying for some users? WDYT?
As for the design, I went for a pretty catchy tone to grab the user's attention before they try to continue reading on the page. Let me know if there are any design guidelines I haven't seen yet.
See here some screenshots:
<p align="center">
</p> …
=> Add Check URL banner

README.md, package-lock.json, package.json
I saw that some files are not formatted yet with the bare VSCode formatting settings mentioned here: https://github.com/KlimaDAO/klimadao#requirements
Additionally, for people not using VSCode their code would probably be not formatted out-of-the-box when saving a file.
As it is recommended to run `prettier --write` on all files (see [this PR comment here](https://github.com/KlimaDAO/klimadao/pull/43#pullrequestreview-835702684)) I added a script on the root level which does exactly that.
~I also ran the script once and added all updated files.~
~Please take a closer look and let me know if this implementation can stay like that and I did not miss anything.~
If this script can stay like that it would make sense to add a default PR-template in which future devs are reminded to run this …
=> Add format-all with prettier script

site/components/pages/Blog/Post/index.module.css, site/components/pages/Blog/Post/index.tsx
Add a fallback UI when nextJS is still fetching props
https://nextjs.org/docs/api-reference/data-fetching/get-static-paths#fallback-true
#89
=> feat: Fallback page

README.md, app/.eslintrc.json, app/next.config.js, site/.eslintrc.json
Follow up on the previous PR.
[Next lint](https://nextjs.org/docs/basic-features/eslint#linting-custom-directories-and-files) will only run the linter against `pages/`, `components/` and `lib/` directories. 
Needed to specify `actions/` and `state/` for proper linting coverage. Something to bear in mind if we add new directories to the repos.
Also added the base eslint rulesets recommended by Next.js
Picked up on this when attempting to share common eslint config across all the repos as we discussed @Atmosfearful . Unfortunately, didn't have much luck with it. Shared config convention seems to be publishing a separate shared config module to npm, which seems overkill at this point in time 🤪
=> refactor: specify directories to lint

app/actions/bonds.ts, app/components/views/Bond/index.tsx
* change default bond quote to 0 so the "you will get" value starts at 0
* update step count ternary on the "number" input
=> Fix: change default bond quote

app/components/views/Stake/index.tsx
When I tried to stake, the input placeholder text is confusing. It seems like it should be switched. See #103 
https://github.com/KlimaDAO/klimadao/issues/103
Resolves #103 
- [ x] Building the app with `npm run build-app` works without errors
- [ x] I formatted JS and TS files with running `npm run format-all`
=> fix: correct text in staking input placeholder (#103)

site/components/Navigation/index.tsx, site/components/pages/Resources/ResourcesHeader/styles.ts
The widths of the nav buttons on mobile were bleeding off the right of the screen and creating a weird effect, as reported by @Atmosfearful. I've brought the buttons back in line with the design and I've hidden the Discord button on mobile.
Also changed the `Resources` button in the main nav to point to `/blog`. I had it pointing at `/resources` which redirected to `/resources/blog` but the directory structure changed and it looks like this didn't get updated.
=> Fix for rendering issue in Resources nav on mobile

cms/schemas/blockContent.js, lib/components/Text/index.tsx, lib/theme/typography.ts, lib/theme/variables.css, site/components/BlockContentRenderer/index.module.css, site/components/BlockContentRenderer/index.tsx, site/components/Card/index.module.css, site/components/Card/index.tsx, site/components/pages/Blog/Post/index.module.css, site/components/pages/Blog/Post/index.tsx, site/components/pages/Blog/index.module.css, site/components/pages/Blog/index.tsx, site/components/pages/Redesign/index.tsx, site/components/pages/Redesign/styles.ts, site/components/pages/Resources/Community/index.tsx, site/components/pages/Resources/Community/styles.ts, site/components/pages/Resources/Contact/index.tsx, site/components/pages/Resources/ResourcesHeader/index.tsx
*  update typography and colors of /blog and /post page to match designs
*  update join discord card styles to it doesn't get overlapped by the resources menu
*  remove h3 and h4 from sanity schema
*  add body3 to typography and --shadow-07, --surface-04, --surface-05 theme variables
*  add block quote styles to the blog
#124
=> Cleanup /blog and /[post] styles

lib/components/Buttons/styles.ts, lib/components/Header/styles.ts, lib/theme/variables.css, site/components/Card/index.module.css, site/components/Footer/styles.ts, site/components/pages/Resources/ResourcesHeader/styles.ts
This PR fixes the dark theme colors for Resources SubNavigation and the Blog headers.
Additionally this PR aligns the footer width with the main grid and gives the DesktopButtons a tiny shadow according to the designs.
part of https://github.com/KlimaDAO/klimadao/issues/131
=> Fix dark colors on resources nav, align Footer width

lib/components/Logos/LogoWithClaim.tsx, lib/components/Logos/styles.ts
Logo should be the same height as the "Enter App" button.
I made it _almost the same height_ as this felt better. The exact same height was too much.
I also added a tiny hover effect on the Logo.
Part of https://github.com/KlimaDAO/klimadao/issues/131
=> Better Logo size

site/components/pages/Redesign/index.tsx, site/components/pages/Redesign/styles.ts
When pressing "Learn More" on the LandingPage the viewport scrolls to the next section.
Part of https://github.com/KlimaDAO/klimadao/issues/131
=> Scroll to next section on click

app/components/InvalidNetworkModal/index.tsx
=> fix: colors in Wrong Network modal

lib/theme/common.ts
Icons should now be white on Safari. Didn't test on all other browsers, but seems like a safe fix to me.
Resolves #156
=> 156 d app nav icons broken safari

site/components/pages/Home/styles.ts
=> fix: carbon counter text for smaller screens

site/components/Footer/styles.ts
New Discord Icon in Footer plus the new Disclaimer page broke the alignment on medium screens.
Here is the fix.
=> Fix footer alignment with new icon and disclaimer

lib/components/TextInfoTooltip/styles.ts
Fixes position for _bottom_ caret in tooltip component
Resolves #178
=> fix caret position for bottom tooltip #178

app/components/CheckURLBanner/index.tsx
Requested by Reikuman since it's confusing to have a different URL in the banner than the user sees in their browser (i.e. without the `dapp.` subdomain)
https://discord.com/channels/897616018602618880/941171473366798346/943337491488981012
=> Switch URL check banner to proper Dapp URL

lib/constants/index.ts
We deployed the old Google partnerships form, just switches to the new Notion one
https://discord.com/channels/897616018602618880/941171473366798346/943384326752600075
=> Switch partnerships form to Notion

site/components/PageHead/index.tsx
add canonical tag to site Pagehead and make sure it doesn't contain query params or hash params or locale and also works for dynamic blog routes
=> Add canonical tag

lib/utils/getKlimaSupply/index.ts, site/pages/api/klima-supply/index.ts
Whoops totally forgot to format the returned supply value properly with decimals
=> Fix units for KLIMA supply API

lib/utils/getStakingRewards/index.ts, lib/utils/index.ts, site/components/pages/Home/index.tsx, site/pages/index.tsx
The `getStakingAPY` util is unused so I hijacked it and generalized it to support calculating staking rewards for a provided number of days - not sure if this should really be 7 day yield, went with 5 day for consistency with the Dapp
Resolves #188
=> Dynamic homepage staking rewards

app/components/views/Info/CopyAddressButton/index.tsx, package-lock.json, site/package.json
In order to finish the migration, last use of `@material-ui/icons` has been replaced for `@mui/icons-material`.
Also, all dependencies of `@material-ui/icons` have been removed.
Resolves #201
=> Remove material-ui/icons

app/components/CheckURLBanner/index.tsx, app/components/ConnectButton/index.tsx, app/components/NotificationModal/index.tsx, app/components/views/Loading/index.tsx, app/locale/en/messages.po, app/locale/fr/messages.po, app/locale/pseudo/messages.po
Added translation tags for home, loading, checkurlbanner, basic notifications components.
=> i18n: a2. home, loading, checkurlbanner, basic notifications

app/components/views/Wrap/index.tsx, app/locale/en/messages.po, app/locale/fr/messages.po, app/locale/pseudo/messages.po
Improved translation tags in the app/wrap page
=> i18n: a7. app/wrap

app/actions/bonds.ts, app/components/views/ChooseBond/index.tsx, app/state/bonds/index.ts
When bond prices drop below `1 + fee` carbon tonne per KLIMA minted the treasury refuses to issue them because they would be unprofitable for the protocol.
As such, we need to account for this when displaying bonds on the frontend so that people don't think there is a juicy discount when in fact the bond cannot be claimed
=> Show broken bonds as sold out

app/lib/i18n.ts, app/pages/index.tsx
Fixes the translations message id flashing by preloading the English language file into the HTML file produced by nextjs
=> Preload english translations in app

app/actions/app.ts, app/components/RebaseCard/index.tsx, app/components/views/Bond/index.tsx, app/state/app/index.ts, lib/constants/index.ts, lib/utils/fetchBlockRate/index.ts, lib/utils/getEstimatedDailyRebases/index.ts, lib/utils/getStakingRewards/index.ts, lib/utils/index.ts, lib/utils/secondsUntilBlock/index.ts, site/pages/index.tsx
I took the `dynamic-block-rate` branch, rebased in the latest changes, moved the API itself to `site` instead of `app` and added caching
Resolves #31
=> Rebased dynamic block rate

app/components/PageHead.tsx, site/components/PageHead/index.tsx
As reported from the Community the Favicon in Safari pinned tabs was not in the correct KlimaDAO green.
This is the fix.
| ![kl_before](https://user-images.githubusercontent.com/95881624/158352514-a10fd5a9-d164-48fc-97d1-8e78e835d920.png)|![kl_after](https://user-images.githubusercontent.com/95881624/158352460-3d81d569-98cb-4d87-aaca-be5d8b88ab57.png) |
=> Fix Safari pinned tabs favicon color

app/components/views/ChooseBond/index.tsx
Just until we can figure out the proper way to disable dynamically based on price for LP bonds
=> Temporarily disable KLIMA/MCO2 LP bonds

app/components/BalancesCard/styles.ts, app/components/BondBalancesCard/styles.ts, app/components/DropdownWithModal/styles.ts, app/components/ImageCard/styles.ts, app/components/MiniTokenDisplay/index.tsx, app/components/MiniTokenDisplay/styles.ts, app/components/NavMenu/index.tsx, app/components/RebaseCard/styles.ts, app/components/views/Bond/styles.ts, app/components/views/ChooseBond/index.tsx, app/components/views/ChooseBond/styles.ts, app/components/views/Home/index.module.css, app/components/views/Home/index.tsx, app/components/views/Offset/index.tsx, app/components/views/Offset/styles.ts, app/components/views/Stake/index.tsx, app/components/views/Stake/styles.ts, app/components/views/Wrap/index.tsx, app/locale/en/messages.po
Small styling changes to polish the offset ui ux:
- consistent gaps around all cards
- move offset nav item above info
- **full width cost and retiring fields to remove input resizing on user input**
- this change completely diverts from the original design, I can look into a solution if we wish to maintain the original design :)
- padding alignment on input and button elements
- standardised responsive styling across dapp
|<img width="1440" alt="image" src="https://user-images.githubusercontent.com/97446324/160029859-da8f3df2-2268-4e14-955c-a706202e4672.png">|<img width="1440" alt="image" src="https://user-images.githubusercontent.com/97446324/160030047-325a23ae-ba25-4e04-8a05-c239961cda6d.png">|
=> refactor: dapp offset ui polish

.github/workflows/schedule_auto_merge.yml
The first live release with github actions worked:
https://github.com/KlimaDAO/klimadao/actions/runs/2065669708
Let's change the schedule to daily at 16h UTC (9am PDT) from Monday through Thursday
Related https://github.com/KlimaDAO/klimadao/issues/206
=> Change workflow schedule to monday-thursday

app/package.json, site/package.json
Makes the `lingui:extract` command return an error if a file cannot be processed
=> Makes the `lingui:extract` command return an error if a file cannot be processed

site/components/BlockContentRenderer/styles.ts
https://www.klimadao.finance/blog/polygon-pos-emissions-analysis this blog was overflowing the container in mobile view because one of the addresses was such a long word so i added word-break break word so that long words that take up the whole container will break to next line
=> fix blog mobile container overflow

.github/workflows/schedule_auto_merge.yml
The scheduled cron job for the staging release workflow is not always triggered reliable.
In order to make it easier to trigger the workflow via Github UI this event is added: `workflow_dispatch`
You can then run the workflow from the actions tab.
See the docs: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
=> Run the workflow via UI

.github/workflows/schedule_auto_merge.yml, .github/workflows/update_translations.yml
As discussed the **Update Translation** job does not need to run `lingui compile` (=> see [line](https://github.com/KlimaDAO/klimadao/blob/staging/.github/workflows/update_translations.yml#L57))
The script only needs to extract the translations with `npm run extract-strings`
The compile command is done on postinstall on Vercel later.
Also changed the scheduled time to be 30 minutes earlier as Github seems to need ~30 minutes to run a scheduled cron job.
=> Change scheduled time and translation script for workflow

.github/workflows/push_to_staging.yml, .github/workflows/schedule_auto_merge.yml
With this new workflow **every merged PR and every other commit** on branch **staging** will trigger "Update Translations".
"Update Translations" checks out staging, installs all dependencies and runs `npm run extract-strings`.
`npm run extract-strings` extracts and syncs (!) all translations with translation.io when running on Github servers.
This will now ensure that if any translations changed/have been added in the repo they will be synced with translation.io immediately.
If no PRs / commits have been pushed to staging during a day => the daily staging release will run "Update Translations" too! Therefore at least once per day the translation are synced with translation.io.
=> Sync translations on every push to staging

app/package.json, site/package.json
Use --overwrite for lingui:extract command
This syncs back the translations made in the code into the `en/messages.po`
=> Use --overwrite for lingui:extract command

site/components/ChangeLanguageButton/styles.ts
Fixes Language Button not looking good in light theme on site
|![image](https://user-images.githubusercontent.com/63291640/162812655-ca8dc36d-4411-4612-b1c6-b410c37f3db6.png) |![image](https://user-images.githubusercontent.com/63291640/162812541-63e6d2cf-309f-4e5e-848d-792202cb0e91.png)|
-->
=> Fixes Language button not looking good in light theme on site

app/components/views/Offset/index.tsx, app/lib/hooks/useOffsetParams.ts
You can pre-fill the app offset tool using URL search parameters. This is useful for connecting your carbon calculator or other third-party app.
Every field can be pre-filled, including selective retirement.
```ts
quantity, // 1.23
inputToken, // "bct" | "nct" | "mco2" | "usdc" | "klima" | "sklima" | "wsklima";
retirementToken, // "bct" | "nct" | "mco2";
beneficiary, // John Doe
beneficiaryAddress, // 0x12345678912345678912345678912345678912345
message, // Hello world
projectTokens  // 0x12345678912345678912345678912345678912345
```
You can provide multiple arguments for `projectToken` and these will be automatically filled into the selective retirement fields (and the 'advanced' dropdown will open itself to reveal them)
Example URL with all fields filled, and 2 selective project tokens: …
=> Offset tool: Support query parameters

app/components/ChangeLanguageButton/index.tsx, app/components/ChangeLanguageButton/styles.ts, app/lib/i18n.ts, site/components/ChangeLanguageButton/index.tsx, site/components/ChangeLanguageButton/styles.ts, site/lib/i18n.ts, site/next.config.js, site/pages/_document.tsx
This PR adds german to both site and app.
It also includes minor refactorings:
- re-enable translations on Site again for NextJS (FOR STAGING ONLY)
- autodetect locale for Site (FOR STAGING ONLY)
- load PO files if on development in App (Site does the same, better developer experience for local testing)
- ensure Pseudo is only shown when not on production
- Make Menu translatable
- Highlight current active locale in Menu
- Better Styles for Menu in App
- Let NextJS set the HTML language tag by itself
Part of https://github.com/KlimaDAO/klimadao/issues/157
=> Add German Translation

app/components/BalancesCard/index.tsx, app/components/BondBalancesCard/index.tsx, app/components/RebaseCard/index.tsx, app/components/views/Bond/index.tsx, app/components/views/ChooseBond/index.tsx, app/components/views/PKlima/index.tsx, app/components/views/Stake/index.tsx, app/components/views/Wrap/index.tsx, app/lib/i18n.ts, app/state/selectors/index.ts, lib/utils/prettifySeconds/index.ts, lib/utils/trimWithPlaceholder/index.ts, site/components/pages/Home/index.tsx
This PR passes the current active locale to:
- toLocaleString
- trimWithPlaceholder
- Intl.RelativeTimeFormat
- prettifySeconds
**Please check the formatting for "en".**
=> All numbers changed from 8.888.88,88 to 8,888,88.88 (from points to commas) which seems to be the official formatting scheme for US and UK.
Part of https://github.com/KlimaDAO/klimadao/issues/157
=> Format numbers in current active locale

app/components/ChangeLanguageButton/index.tsx, app/lib/i18n.ts, site/components/ChangeLanguageButton/index.tsx, site/lib/i18n.ts, site/next.config.js
This PR fixes:
- do not translate Languages in Language Menu for Site
- show Russian and Chinese in Language Menu on Site 
- make Chinese work on Site and App properly with setting the correct Language Code "zh-CN" everywhere
Missing parts of https://github.com/KlimaDAO/klimadao/issues/324
=> Fix Site Language Toggle, Fix Chinese Set-Up

app/components/PageHead.tsx, app/components/views/Bond/index.tsx, app/pages/index.tsx, app/state/selectors/index.ts, lib/utils/prettifySeconds/index.ts, lib/utils/trimWithPlaceholder/index.ts, site/components/PageHead/index.tsx
This PR does:
Site:
- render meta locale according to the router locale
App:
- render meta locale according to the locale in redux state (Client only, Server will always be "en")
- refactor state selector and remove the "en" fallback
Resolves https://github.com/KlimaDAO/klimadao/issues/293
=> Render meta tags with current locale language tag

app/components/NavMenu/index.tsx, app/components/views/Home/index.tsx, app/lib/hooks/useLocaleFromParams.ts, app/lib/i18n.ts, site/components/Footer/index.tsx, site/components/Navigation/index.tsx, site/components/pages/Buy/index.tsx, site/components/pages/Home/index.tsx, site/lib/i18n.ts
This PR includes:
- All links from Site -> App have a locale param attached: `?locale=fr`
- App reads the locale params from the URL, validates the locale, removes the locales from URL and dispatches the locale to the state
- All links from App -> Site have the locale as a sub-path attached: `/fr`
- https://klimadao-app-git-pass-locale-as-queryparam-klimadao.vercel.app/#/stake?locale=de
=> should load german, remove query from URL, link to Site with `/de`
- https://klimadao-site-git-pass-locale-as-queryparam-klimadao.vercel.app/de
=> should load german, link to App with `?locale=de`
When linking to the Site with a sub-path and this sub-path does not exist the server responds with 404.
But there is no 404 page yet https://github.com/KlimaDAO/klimadao/issues/331
Resolves …
=> Pass and read selected locale between App and Site

app/components/views/Home/index.tsx
When the user navigates to the app, we redirect them to a default view (/#/stake)
https://github.com/KlimaDAO/klimadao/blob/31e19ec9b0a91ea81b1914a6aa70661cf1342673/app/components/views/Home/index.tsx#L170-L174
React router `navigate()` was making wacky urls like `app.klimadao.finance/?locale=de#/stake`
Fixed by ditching `navigate()` and using browser native APIs
=> Correctly pass params when redirecting to /stake

app/components/views/Stake/index.tsx, app/components/views/Wrap/index.tsx
This PR ensures that when switching the language in App the stake and wrap input placeholders do change too.
**Please test! Thanks**
**BEFORE:** https://staging-dapp.klimadao.finance/#/wrap
=> when changing the language **the input placeholder does not change**
**AFTER:** https://klimadao-app-git-fix-stake-input-placeholder-klimadao.vercel.app/#/wrap
---
**BEFORE:** https://staging-dapp.klimadao.finance/#/stake
=> when changing the language **the input placeholder does not change**
**AFTER:** https://klimadao-app-git-fix-stake-input-placeholder-klimadao.vercel.app/#/stake
=> App: Fix stake and wrap input placeholder language switch

lib/theme/variables.css, site/components/Footer/styles.ts, site/components/pages/errors/Custom404.tsx, site/components/pages/errors/Custom500.tsx, site/components/pages/errors/styles.ts, site/pages/404.tsx, site/pages/500.tsx
This PR does:
- add simple 404 page to Site => [Test URL](https://klimadao-site-git-add-error-pages-klimadao.vercel.app/asdasdasdasd)
- add simple 500 page to Site
- see https://nextjs.org/docs/advanced-features/custom-error-page
- **Small fix: let Footer icons break on small devices**
Resolves https://github.com/KlimaDAO/klimadao/issues/331
| ![footer_before](https://user-images.githubusercontent.com/95881624/165081487-6a9fb113-77c3-4256-96ad-91c15cd31ff1.png) | ![footer_after](https://user-images.githubusercontent.com/95881624/165081483-57fea4c8-7695-4183-9428-d55051a9a3ed.png) |
=> Site: Add 404 and 500 Error pages

app/components/BalancesCard/index.tsx, app/components/InfoButton/index.tsx, app/components/RebaseCard/index.tsx, app/components/views/Buy/index.tsx, app/components/views/PKlima/index.tsx, app/components/views/Stake/index.tsx, app/components/views/Wrap/index.tsx, lib/components/TextInfoTooltip/index.tsx
This PR replaces the lingui function `t` with the component `Trans` which handles the language change and the tooltip content is shown in the correct language.
Resolves https://github.com/KlimaDAO/klimadao/issues/340
=> App: Fix tooltip re-render on language change

app/components/views/Stake/index.tsx, app/components/views/Wrap/index.tsx, app/locale/en/messages.po
Dynamically loading message IDs is not working because: https://github.com/lingui/js-lingui/issues/1054#issuecomment-830687747
Therefore the message IDs have to exist before rendering the Translation.
If this is not the case, lingui does not find these messages. 
And **deletes the former ones** which happened here:
https://github.com/KlimaDAO/klimadao/commit/1633550d6de4a185b08bc9d5da8e2f19f0475d5d
This PR contains a fix with defining the possible messages beforehand and picking the correct one dynamically depending on the state value.
**Please note that on translation.io the new translation values have to be added again.**
=> Fix missing strings for input placeholders

README.md, app/package.json, package.json, site/package.json
This PR does:
- add a new script `npm run extract-strings:dev` which extracts the source translations for "en" only
- ~remove the error catch for "can not process files" as this script runs on GH servers only!~
- => let´s keep this one for now to at least stop the github action workflow run if an error happens
This new script should help developers for local development and extract the source language only.
And should **prevent developers from pushing other language files** as these are handled by Github actions anyways.
=> Script: Extract source "en" translations only for local development

app/components/BalancesCard/index.tsx, app/components/CarbonTonnesBreakdownCard/index.tsx, app/components/DropdownWithModal/index.tsx, app/components/Image/index.tsx, app/components/MiniTokenDisplay/index.tsx, app/components/views/Offset/index.tsx, app/components/views/Stake/index.tsx, app/components/views/Wrap/index.tsx, app/locale/de/messages.po, app/locale/en-pseudo/messages.po, app/locale/en/messages.po, app/locale/fr/messages.po, app/locale/ru/messages.po, app/locale/zh-CN/messages.po, app/state/user/index.ts, site/locale/de/messages.po, site/locale/en-pseudo/messages.po, site/locale/fr/messages.po, site/locale/ru/messages.po, site/locale/zh-CN/messages.po
Added wsKLIMA balance to BalancesCard if connected wallet has > 0 wsKLIMA. Also added an 'unwrapped' view while on the Wrap page.
Resolves #180
=> 180 add ws klima to balances

site/components/pages/Home/index.tsx, site/components/pages/Home/styles.ts
=> [site] Fix padding for german, fix z-index conflict for language menu

app/components/DropdownWithModal/index.tsx, app/components/views/Offset/index.tsx, app/locale/en/messages.po
Again another spot where the translation are not re-rendered when switching the language.
Replacing `t` with `<Trans>` fixes it.
=> Fix Drop Down label translation not re-rendered

app/locale/en/messages.po, site/components/pages/Retirement/SingleRetirement/index.tsx, site/components/pages/Retirement/index.tsx, site/locale/en/messages.po
See here that the latest GH actions are failing: https://github.com/KlimaDAO/klimadao/actions
Reason is [this PR](https://github.com/KlimaDAO/klimadao/pull/366) which introduced same translation message IDs in different places. In this case lingui "Cannot process file" which [is caught in the actual script](https://github.com/KlimaDAO/klimadao/blob/staging/site/package.json#L9) which runs on the GH servers and exits the action run.
This PR contains the fix for the same message IDs.
I ran `npm extract-strings:dev` too which we should include in a check for developers in general for the future.
=> see this [ticket](https://github.com/KlimaDAO/klimadao/issues/348)
=> Fix extract strings with same message ID

lib/types/offset.ts, lib/utils/getRetirement/index.ts, lib/utils/getTypeOfToken/index.ts, lib/utils/index.ts, site/components/pages/Retirement/SingleRetirement/index.tsx
[BigNumber.toNumber](https://docs.ethers.io/v5/api/utils/bignumber/#BigNumber--BigNumber--methods--conversion) method can not handle JavaScript numbers outside the safe range.
See the docs => https://docs.ethers.io/v5/troubleshooting/errors/#help-NUMERIC_FAULT-overflow
This the reason why the retirement pages can not be generated for some addresses.
Replacing `toNumber` with `ethers.utils.parseUnits` fixes the overflow error.
Thus, this PR introduces the correct formatting of the retirement amount according to the **type of token** too.
You need to have some retirements done first.
You can do these here: https://app.klimadao.finance/#/offset
Then open the preview URL of this Pull Request and add your address and number of the retirement to the URL:
- …
=> Fix BigNumber throws "overflow" error on Retirement pages

site/pages/pledge/[address].tsx, site/pages/pledge/index.tsx
The latest automated Release from Staging to Production failed because the pages can not be generated:
```TS
Error: Export encountered errors on following paths:
--
17:47:11.732 | /pledge: /de/pledge
17:47:11.735 | /pledge: /en/pledge
17:47:11.735 | /pledge: /fr/pledge
Error: `redirect` can not be returned from getStaticProps during prerendering (/pledge)
```
Here is the failing build: => [Link to Vercel](https://vercel.com/klimadao/klimadao-site/5zxyAfEbBztmPtcnxnh4JFnKSkfw)
This PR fixes it with:
- if on Production => Return any URL with `/pledge` or `/fr/pledge` or `/de/pledge` **with a 404-Not Found**
- If not on Production => render the Pledge pages
**=> Page generation changed from a redirect to a 404 !**
=> Fix Pledge Pages on Production

app/components/ChangeLanguageButton/index.tsx, app/lib/i18n.ts, site/components/ChangeLanguageButton/index.tsx, site/lib/i18n.ts, site/next.config.js
According to these tickets I assume that both languages are ready for production:
https://github.com/KlimaDAO/klimadao/issues/386
https://github.com/KlimaDAO/klimadao/issues/387
This PR will make both languages available on Production for both Site and App 
according to the **current state of translation on Staging**.
- SITE: https://staging-site.klimadao.finance/
- App: https://staging-dapp.klimadao.finance/
Closes #386 
Closes #387
=> Release Russian and Chinese translations

package-lock.json
This reverts commit bf7ea53383b91f83197f9416d19a6e851f87337a.
Test for failing GH actions
=> Revert "build(deps): bump cross-fetch from 2.2.5 to 2.2.6 (#375)"

site/components/Navigation/index.tsx
_Minor_ thing:
The main "Enter App" button does not link with the current chosen locale to the App.
This is the fix.
=> Main „Enter App“ button does not include locale

app/components/ChangeLanguageButton/index.tsx, app/lib/i18n.ts, app/locale/es/messages.po, app/locale/ko/messages.po, lingui.config.js, site/components/ChangeLanguageButton/index.tsx, site/lib/i18n.ts, site/locale/es/messages.po, site/locale/ko/messages.po, site/next.config.js
This PRs includes Korean and Spanish translations (Staging only).
With the next sync these will be available on Translation.io too.
Please note that there are tons of different Spanish country codes.
See the full list [here](http://www.lingoes.net/en/translator/langcode.htm).
I decided now for "es-ES" which is Spain. 
Let's keep that in mind when we see problems with timezones.
Closes https://github.com/KlimaDAO/klimadao/issues/394
=> Add Korean and Spanish

app/components/views/Offset/index.tsx, app/lib/i18n.ts, site/pages/retirements/[beneficiary_address]/[retirement_index].tsx
This PR removes the feature flag and enables:
- App: Offset Success Modal includes a Link to `https://www.klimadao.finance/retirements/0xs34..../1` 
- App: SuccessModal is shown for 1,5 seconds, then opens Retirement Page in a new window/tab (If the browser settings **do not block** new windows!))
- Site: Generates the corresponding page for `retirements/0xs34..../1`
- **Refactoring:** Pass the current **locale** between App to Site for **subpaths** too
Please note that maybe not all translations are available for these page yet?
=> Release Retirement Page 💚 

app/components/PageHead.tsx, app/pages/index.tsx, lib/constants/index.ts, site/components/PageHead/index.tsx, site/components/pages/Blog/Post/index.tsx, site/components/pages/Blog/index.tsx, site/components/pages/Disclaimer/index.tsx, site/components/pages/Home/index.tsx, site/components/pages/Resources/Community/index.tsx, site/components/pages/Resources/Contact/index.tsx, site/components/pages/Retirements/SingleRetirement/index.tsx, site/components/pages/Retirements/index.tsx
To solve ticket #373 I initially used recommendations from a web site that generates og meta tags. This was not a good idea.
This time I read the documentation from twitter https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image and made the following changes:
- Use name instead of property attribute for twitter OG tags
- Use Fully qualified name for twitter:image OG tag
Twitter also has recommendations for the image size:
```A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. Images for this Card support an aspect ratio of 2:1 with minimum dimensions of 300x157 or maximum of 4096x4096 pixels. Images must be less …
```
=> OG meta properties fix for twitter

app/components/views/Bond/index.tsx
I replaced the emoji with the code for the emoji to display on linux/ubuntu with brave. I have not tested this bc I dont run linux.
#384
Resolves #384 
#384
=> replaced emoji with utf8 code for emoji for linux bug

site/components/pages/Retirements/List/index.tsx, site/components/pages/Retirements/SingleRetirement/index.tsx, site/locale/en/messages.po, site/pages/retirements/[beneficiary_address]/index.tsx
This PR releases the totals retirement page for a beneficiary address on Production.
And links from the Single Retirement pages back to the totals page too.
Additionally, if the address does not exist => renders proper placeholder for empty states
E.g. https://klimadao-site-git-release-totals-klimadao.vercel.app/retirements/0x293ed38530005620e4b28600f196a97e1125daee
Related to #402
=> Release Totals Retirement page 🌳 

site/components/ChangeLanguageButton/index.tsx
Makes the language swither redirect to the same page in the other language
Resolves #420
NA
=> Makes the language swither redirect to the same page in the other language

site/components/Header/styles.ts
See the bug description in this ticket: https://github.com/KlimaDAO/klimadao/issues/410
With giving the HeaderDesktop an higher z-index (same as the HeaderMobile has btw), the opened Translation menu has enough z-index layers of space to render above any content which might have z-indexes too.
**BEFORE:**
https://staging-site.klimadao.finance/de/retirements/0x087a7afb6975a2837453be685eb6272576c0bc06/2
**AFTER**
https://klimadao-site-git-fix-z-index-klimadao.vercel.app/de/retirements/0x087a7afb6975a2837453be685eb6272576c0bc06/2
Resolves #410
=> Fix Translation menu z-index issue

lib/constants/index.ts, lib/types/subgraph.ts, lib/types/verra.ts, lib/utils/index.ts, lib/utils/subgraph/queryPolygonBridgedCarbon.ts, lib/utils/verra/getVerraProjects.ts, site/components/pages/Retirements/SingleRetirement/ProjectDetails/List/index.tsx, site/components/pages/Retirements/SingleRetirement/ProjectDetails/List/styles.ts, site/components/pages/Retirements/SingleRetirement/ProjectDetails/index.tsx, site/components/pages/Retirements/SingleRetirement/ProjectDetails/styles.ts, site/components/pages/Retirements/SingleRetirement/index.tsx, site/locale/en/messages.po, site/pages/retirements/[beneficiary_address]/[retirement_index].tsx
This PR does:
- extend the subgraph data to projectID and other offset data
- get information about a single VCS project ID from Verra
- render project details and link to Verra and Polygon
- render fallback for Moss offsets
**Preview URL:**
`https://klimadao-site-git-show-project-details-klimadao.vercel.app/retirements/<WALLET-ADDRESS>/<NUMBER-OF-RETIREMENT>`
Resolves https://github.com/KlimaDAO/klimadao/issues/438
=> Retirement: Show project details 🏷️ 

app/components/ChangeLanguageButton/index.tsx, app/lib/i18n.ts, site/components/ChangeLanguageButton/index.tsx, site/lib/i18n.ts, site/next.config.js
This PR releases Spanish "es-ES" to Production.
Spanish will appear at the last language in the translation menu.
Let me know if I should change the order.
Resolves https://github.com/KlimaDAO/klimadao/issues/454
=> Release Spanish to Production

site/components/ChangeLanguageButton/index.tsx
This PR is a fix for this PR: https://github.com/KlimaDAO/klimadao/pull/451
When changing the language on **_dynamic pages_** the `Link` component needs the query data too.
Otherwise the dynamic pages can not be created for the new language.
On production nothing happens when trying to change the language on dynamic pages.
On localhost this error appears:
https://nextjs.org/docs/messages/href-interpolation-failed
Test yourself the bug here and **try to change the language:**
- [Blog Subpage on Staging](https://staging-site.klimadao.finance/fr/blog/response-to-verra-comments-on-crypto-instruments-and-tokens)
- [Retirement Page on Staging](https://staging-site.klimadao.finance/de/retirements/0x087a7afb6975a2837453be685eb6272576c0bc06)
=> nothing happens, no routing is created
**Test the …
=> Fix language switch for dynamic pages

site/components/pages/Pledge/lib/putPledge.ts
Use relative path in next api call to avoid CORS related issues
=> use relative path to call api/pledge

site/pages/blog/[pid].tsx, site/pages/blog/index.tsx, site/pages/buy.tsx, site/pages/community.tsx, site/pages/contact.tsx, site/pages/disclaimer.tsx, site/pages/index.tsx
To stay within the Infura free tier I reduced the frequency at which the landing page refreshes itself. With all languages + dozens of contract calls, this was adding up quickly.
Also increased the blog revalidate time to reduce sanity.io bandwidth.
And removed `revalidate` from some static pages, to reduce vercel bandwidth.
Landing page: 1min -> 10min
Blog posts: 2min -> 4min
All static pages: remove revalidate and generate static pages at build time.
=> Increase page revalidation times

app/components/ChangeLanguageButton/index.tsx, app/lib/i18n.ts
The language button waits for the language to be loaded by lingui before commiting the change to the store.
Resolves #467
NA
=> dApp: Fix for the language button

site/components/Modal/styles.ts, site/components/pages/Pledge/PledgeDashboard/Cards/FootprintCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/index.tsx, site/components/pages/Pledge/PledgeForm/index.tsx, site/components/pages/Pledge/PledgeForm/styles.ts
- use overflow-y: auto on modal component
- methodology field placeholder text
- rounded total pledge tonnage to 2 decimal points
=> pledge dashboard v1 touchups

app/components/views/Offset/index.tsx, app/components/views/Offset/styles.ts
I used the ethers isAddress util to test the addresses and added an array of booleans to `specificAddresses` for conditional styles on the input. I left the :focused the same so it doesnt flash at the user while typing. One questio is for the button props what priority do we want thew address format error to be? before or after the "insufficient funds"and other errors?
#432 
Resolves #432
=> Fix #432 - add better form validation for selective retirements

lib/utils/ens/index.ts, lib/utils/getJsonRpcProvider/index.ts, lib/utils/index.ts, lib/utils/kns/index.ts, site/components/pages/Retirements/CopyAddressButton/index.tsx, site/components/pages/Retirements/CopyAddressButton/styles.ts, site/components/pages/Retirements/index.tsx, site/components/pages/Retirements/styles.ts, site/lib/getDomainByAddress.ts, site/pages/retirements/[beneficiary]/[retirement_index].tsx, site/pages/retirements/[beneficiary]/index.tsx
This PR does:
- take the beneficiary data from the url
- if the data is an address => check if a KNS or ENS domain exist for this address
- if a KNS or ENS address exists => redirect to new URL with this domain
- show beneficiaryAddress below nameserviceDomain
- some refactorings
ENS lookup does not work in local development  on the server if the `infura_id` is not present!
Therefore rendering retirement pages with an address which do not have KNS or ENS fails locally (404)!
Error:
```TS
{
reason: 'network does not support ENS',
code: 'UNSUPPORTED_OPERATION',
operation: 'lookupAddress',
network: 'matic'
}
```
**Solutions:**
Resolves https://github.com/KlimaDAO/klimadao/issues/483
=> Retirements: Redirect to KNS or ENS url, if exists

site/components/pages/Retirements/Breakdown/index.tsx, site/components/pages/Retirements/SingleRetirement/ProjectDetails/index.tsx, site/components/pages/Retirements/SingleRetirement/index.tsx, site/locale/en-pseudo/messages.po, site/locale/en/messages.po
This PR changes:
**Retirements Totals Page:**
- New title "Retirement Totals By Asset"
- Placeholder for empty Assets list "No retirement assets found"
**Retirements Single Page:**
- New Project Details subline "The tonne(s) retired originated from the following project(s). Click on the project title to learn more."
- If a Moss Project => Remove "Click on the project title to learn more." from Project Details subline
- If a Moss Project change link text to "Learn more about the projects that back the MCO2 pools"
Resolves https://github.com/KlimaDAO/klimadao/issues/481
<p align="center">
</p>
=> Retirements: Text improvements

app/components/PageHead.tsx, lib/utils/getOgImageSrc/index.ts, lib/utils/index.ts, site/components/PageHead/index.tsx
Sends an URL of a resized version of the CDN images for og image tags
I choose completly arbitrarily an height of 1000px 
Resolves #448
When tweeting a post
|![image](https://user-images.githubusercontent.com/11857992/173441110-f6774188-8f04-4aeb-bd23-93788f77d9bd.png) |![image](https://user-images.githubusercontent.com/11857992/173441188-28d1af64-d2ee-4097-b687-d31d47c575f6.png)|
=> Request resized images from the CDN for og image meta tags

app/actions/app.ts, app/actions/offset.ts, app/actions/pklima.ts, app/actions/stake.ts, app/actions/user.ts, app/actions/wrap.ts, lib/utils/getContract/index.ts, lib/utils/getKlimaSupply/index.ts, lib/utils/getRetirement/index.ts, lib/utils/getStakingRewards/index.ts, lib/utils/getTreasuryBalance/index.ts, lib/utils/index.ts, lib/utils/kns/index.ts, site/lib/getBalances.ts
This is another preparation PR for ticket #9 
- map all token contracts to their corresponding Abi JSON files
- replace all Contracts with the new `getContract` lib util
This will make it easier later to create contracts objects like
```TS
const allContracts = createContracts(["bct", "nbo", "klima"]);
const allBalances = getBalancesFromContracts(allContracts);
const allAllowances = getAllowancesFromContracts(allContracts);
...
```
**TODO**
- do the same for Bonds later in another PR
Part of #9
=> Refactor: Move Contracts and Abi to lib 🧹 

app/actions/app.ts, lib/utils/getContract/index.ts, lib/utils/getStakingRewards/index.ts
A tiny follow-up PR on https://github.com/KlimaDAO/klimadao/pull/503
- move the creation of the main sKlima contract to lib too
- improve types with letting TypeScript complain when a `contractName` does not exist in the `contractMap`
Now only the bonds contracts are the only ones left!
Will do this as soon as the Bonds views are done.
Preparation for #9
=> Refactor: Move main sklima contract to getContract 

app/package.json, site/package.json
`npm run postinstall` stopped working. I don't understand why or how this is possible. This is a **temporary workaround** that adds string compilation as a step to the main build script.
Track the underlying issue here #518
=> run lingui:compile in build script

lib/components/Icons/FacebookIcon.tsx, lib/components/ThemeToggle/styles.ts, lib/components/index.ts, site/components/FacebookButton/index.tsx, site/components/FacebookButton/styles.ts, site/components/LinkedInButton/index.tsx, site/components/LinkedInButton/styles.ts, site/components/TweetButton/index.tsx, site/components/TweetButton/styles.ts, site/components/pages/Retirements/CopyURLButton/index.tsx, site/components/pages/Retirements/CopyURLButton/styles.ts, site/components/pages/Retirements/Footer/styles.ts, site/components/pages/Retirements/SingleRetirement/ProjectDetails/styles.ts, site/components/pages/Retirements/SingleRetirement/index.tsx, site/components/pages/Retirements/SingleRetirement/styles.ts
This PR adds the Social Share Buttons on the Retirement Single Page:
- Twitter
- Facebook
- Linkedin
**Note:**
Only for Twitter it works **to add a custom text to the shared URL**
For Facebook and Linkedin it does not.
**Another Note:**
In order to make the sharing work properly
=> all meta data has to be correct !
Twitter, Facebook and Linkedin retrieve the data from the meta tags.
=> Twitter takes other meta tags than Facebook or LinkedIn, Try it out yourself.
**Please ensure that all translations are correct for the meta data too** ❗ ❗ 
Open the Preview URL and add the retirement page Data.
Like: `https://klimadao-site-git-add-social-share-on-retirement-klimadao.vercel.app/retirements/<YOUR-ADDRESS>/<YOU-NUMBER-OF-RETIREMENT>`
Examples:
- [With …
=> Add social share buttons on Single Retirement

app/actions/bonds.ts
INVERSE_USDC_MARKET_ID changed from 7 to 8 in bond actions
=> change market id from 7 to 8

app/components/views/Bond/index.tsx
the bond max was checking users wallet to calculate the max a user can spend. we need to multiply user klima balance by bond quote to get the right number and we were not.
=> fix bond max calc to check max klima to usdc in wallet instead of klima

site/components/pages/Pledge/PledgeDashboard/Cards/BaseCard/styles.ts, site/components/pages/Pledge/PledgeDashboard/Cards/FootprintCard/FootprintCharts.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/FootprintCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/FootprintCard/styles.ts, site/components/pages/Pledge/PledgeDashboard/Cards/MethodologyCard/index.tsx, site/components/pages/Pledge/lib/formSchema.ts
Addresses the majority of display related feedback raised through QA:
- Changes `methodology` character limit to 1000 (arbitrary number)
- Changes `description` character limit to 500.
- Update methodology card icon,
- Display footprint percent values to 2 decimal points (on chart tooltip and table)
- Footprint category:
- Made the call to remove text overflow and just wrap the text instead of showing tooltip on hover.
- Limit category naming to 32 characters, the equivalent of two rows on desktop view. We can revisit these character limit if the need arises.
https://github.com/KlimaDAO/klimadao/issues/489
|<img width="531" alt="image" src="https://user-images.githubusercontent.com/97446324/180168420-247ddd26-3d0c-4cd2-8b34-8f57e8878614.png">|<img …
=> pledge dashboard tweaks

site/components/pages/Infinity/Cards/Card.tsx, site/locale/en-pseudo/messages.po, site/locale/en/messages.po
The infinity card values are all hard coded.
No need to wrap them in translation tags.
=> fix: do not translate hard coded values

app/components/views/Offset/index.tsx, lib/constants/index.ts
I removed klima, sklima, and wsklima from the input tokens on the retirements page.
Resolves #569
=> remove UBO and NBO from klima retirements

lib/utils/subgraph/queryPolygonBridgedCarbon.ts, site/components/pages/Retirements/SingleRetirement/RetirementDate/index.tsx, site/components/pages/Retirements/SingleRetirement/index.tsx, site/components/pages/Retirements/index.tsx, site/pages/retirements/[beneficiary]/[retirement_index].tsx, site/pages/retirements/[beneficiary]/index.tsx
Users reported that the Retirement Receipt page returns a 404 after a successful Offset.
Under the assumption that this error occurs **when the subgraph is querying the data not fast enough**
this PR does the following:
- ensure that all queries return `false` on empty query results (Subgraph returns empty array on not found!)
- If the data is `false` => pass `null` to the Page props
- During rendering add fallback for empty data or render nothing
Closes https://github.com/KlimaDAO/klimadao/issues/568
Spot the difference 😄 
| With Subgraph Data  | Without Subgraph Data  |
|<img width="426" alt="" src="https://user-images.githubusercontent.com/95881624/182347260-5bad3177-ad6e-420f-8781-200a00994944.png"> | <img width="633" alt="" …
=> Retirements: Check for empty subgraph data

site/components/pages/Pledge/HeaderDesktop/index.tsx, site/components/pages/Pledge/HeaderMobile/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/AssetBalanceCard/TokenRow/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/AssetBalanceCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/FootprintCard/FootprintCharts.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/FootprintCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/MethodologyCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/PledgeCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/RetirementsCard/RetirementsChart.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/RetirementsCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/Profile/index.tsx, site/components/pages/Pledge/PledgeDashboard/index.tsx, site/components/pages/Pledge/PledgeForm/index.tsx, site/components/pages/Pledge/index.tsx, site/locale/en/messages.po
Extract strings from `/pledges/*` for translations.
Translating form error message strings is not as straight forward as utilising lingui macros so I'm going to pull that out into a separate ticket to be worked on :)
=> site/pledges: extract strings for i18n

cms/schemas/podcast.js, cms/schemas/post.js, cms/schemas/schema.js, cms/schemas/tag.js
This is the first step for the new filtering of blog content and does:
- add new document schema "tag" for sanity
- reference tags in posts and podcasts
This is not deployed yet! 🔥 
Still the Live project for sanity detected the new field "tags" from my local dev server when running sanity on localhost.
Is this intended?
**And who will deploy this now?**
Related to https://github.com/KlimaDAO/klimadao/issues/534
=> CMS: add tags for posts and podcasts

site/components/Form/InputField/index.tsx, site/components/Form/InputField/styles.ts, site/components/Form/TextareaField/index.tsx, site/components/Modal/index.tsx, site/components/Modal/styles.ts, site/components/pages/Pledge/PledgeDashboard/index.tsx, site/components/pages/Pledge/PledgeForm/index.tsx, site/components/pages/Pledge/lib/formSchema.ts, site/components/pages/Pledge/lib/index.tsx, site/locale/en/messages.po
Form error messages can not be directly translated where we define the form `yups` schema.
To work with this constraint, we return the translation id as the "error message", which is then mapped to a function that returns translated strings based on the id.
Resolves #606
=> Pledge form error translations

lib/types/subgraph.ts, lib/utils/subgraph/queryPolygonBridgedCarbon.ts, site/components/pages/Retirements/SingleRetirement/DownloadCertificateButton/generateCertificate.ts, site/components/pages/Retirements/SingleRetirement/DownloadCertificateButton/index.tsx, site/components/pages/Retirements/SingleRetirement/index.tsx, site/locale/en/messages.po, site/pages/retirements/[beneficiary]/[retirement_index].tsx
- Add type to retirement certificates
- update certificate filename to following pattern: `retirement_<index>_<beneficiary_address>`
- add loading components to mitigate layout shift on lazy loading
Resolves #605 #604
=> Retirement certificate enhancements

lib/components/Buttons/ButtonBase.tsx
A minor fix to remove the error warning from nextJS:
```
next-dev.js?878b:32 Warning: React does not recognize the `buttonStyle` prop on a DOM element. 
If you intentionally want it to appear in the DOM as a custom attribute, 
spell it as lowercase `buttonstyle` instead. 
If you accidentally passed it from a parent component, remove it from the DOM element.
at a
at BaseButton ....
```
=> fix: do not pass buttonStyle to anchor props

package-lock.json
Removing `node_modules` folder and do a fresh install with `npm install` these changes appear in package.lock.
- Is this correct?
- Does the same happen on your machine?
=> Root: Update package.lock

app/components/TransactionModal/index.tsx, app/components/views/Offset/index.tsx
As described in the ticket https://github.com/KlimaDAO/klimadao/issues/615 the price between approval and final transaction can change. To not create a bad user experience which would result in errors in metamask, let's rather increase the approval amount.
The TXN modal is extended now to accept `approvalValue` for the first screen. 
And falls back to the actual `value` if missing.
Resolves https://github.com/KlimaDAO/klimadao/issues/615
=> Add 1% to approval value for offset

site/components/pages/Retirements/SingleRetirement/DownloadCertificateButton/generateCertificate.ts
Retirement certificates for amounts less than <0.01 round to 0.
This change updates certificates to show "< 0.01 tonnes" instead of 0.
Resolves #612 
|<img width="804" alt="image" src="https://user-images.githubusercontent.com/97446324/185273425-aaf3fe01-ed2d-4032-aa51-1388b05333f5.png">|<img width="967" alt="image" src="https://user-images.githubusercontent.com/97446324/185271028-bc3cd904-af25-4885-bbf0-48883ce681e7.png">|
=> Retirement Certificate: Handle <0.01 carbon tonne retirements

site/components/pages/Infinity/Cards/Card.tsx, site/components/pages/Infinity/Cards/styles.ts
Updating the font size for cards on infinity page. I am over-riding the styles set in Text bc none of the `body` styles will work. They are too big on desktop and too small on mobile so thats why `!important` is used. I can also add another `body` var if that would be better.
=> card font update

app/components/views/Stake/index.tsx, app/components/views/Wrap/index.tsx
Small improvement on button props:
If `hasApproval` is true => show "APPROVE" on main button which triggers the TXN Modal.
This is now aligned with all views which render the TXN Modal
Part of Ticket https://github.com/KlimaDAO/klimadao/issues/625
=> fix: better button props if hasApproval is true

site/components/pages/Pledge/PledgeDashboard/Cards/MethodologyCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/PledgeCard/index.tsx, site/components/pages/Pledge/PledgeForm/index.tsx, site/components/pages/Pledge/lib/formSchema.ts
- Allow user to submit pledge form with invalid data and let form library to validate and display errors if input is invalid.
- Current pledges that were previously valid until the introduction of character limits may have issues updating their pledge. This ux pattern will surface invalid inputs for the user to correct.
- Support user entered new line characters in textarea fields
Resolves #634
Partial fix for #629(?)
|<img width="500" alt="image" src="https://user-images.githubusercontent.com/97446324/185878040-bcbb6512-988c-4186-8800-c1e28ace66e0.png">|<img width="500" alt="image" src="https://user-images.githubusercontent.com/97446324/185878074-bd5a5c93-5f44-4b38-8e00-bd2a91f87b84.png">|
=> Hotfix: pledge form inputs & new line character support

cms/schemas/post.js
This flag is needed for the new "Featured Articles" Slider. 
As soon as a post is flagged as "featured" => this Post will appear in the Slider later.
Will you do that later again, @Atmosfearful ?
Part of https://github.com/KlimaDAO/klimadao/issues/534
=> CMS: Add "Is Featured Article" to Post

app/locale/en-pseudo/messages.po, site/components/pages/Resources/index.tsx, site/components/pages/Resources/styles.ts, site/lib/queries.ts, site/locale/en-pseudo/messages.po, site/locale/en/messages.po, site/next.config.js, site/pages/resources/index.tsx
This is the first set-up for the new Resources Page:
- add NEXTJS page "Resources"
- hide this page on Production (keep redirect from "resources" -> "blog")
- show this page on Staging and Preview Links (remove redirect)
- add new query for all podcasts and posts, sorted desc, limit to 20
- add basic Page and render a list of podcasts and posts
- https://klimadao-site-git-resources-page-klimadao.vercel.app/resources
Part of https://github.com/KlimaDAO/klimadao/issues/534
=> Add Resources page (Staging only)

app/actions/bonds.ts, app/actions/user.ts, app/components/NotificationModal/index.tsx, app/components/views/Bond/index.tsx, app/components/views/Bond/styles.ts, app/components/views/ChooseBond/index.tsx, app/lib/getTokenInfo.ts, app/locale/en-pseudo/messages.po, app/locale/en/messages.po, lib/constants/index.ts, lib/utils/getContract/index.ts, site/locale/en-pseudo/messages.po
This PR replaces the former NotificationModal with the new TransactionModal for the following actions:
- approve bond amount for spender contract
- submit final bond action
- redeem pending amounts
This PR also includes these refactorings:
- use the same generic `changeApprovalAction` from utils (same as for Stake, Wrap, Offset)
- add bonds addresses and their matching ABIs to lib/getContract
- adjust all types accordingly
- use `getContract` lib wherever possible
**Please follow the [commit history](https://github.com/KlimaDAO/klimadao/pull/600/commits) to get along with all the changes 🔥** 
=> useful keyboard commands "n" and "p" to browse through the commits
Resolves https://github.com/KlimaDAO/klimadao/issues/579
=> Bonds: Use new TXN Modal for Approval & Bond & Redeem

site/components/Header/styles.ts, site/components/Navigation/index.tsx, site/components/pages/Infinity/index.tsx, site/locale/en/messages.po
- Fix white bar appearing above header on /infinity page
- Do not render `<ThemeToggle />` on /infinity
- useEffect in `<ThemeToggle />` will set the theme to what has been stored in the browsers local storage, overriding the page's theme override
- set site theme to light mode
- navigate to /infinity and refresh page
- /infinity page should not render with light mode
Resolves #669 
Resolves #670 
|<img width="400" alt="image" src="https://user-images.githubusercontent.com/97446324/187711809-95f493f5-510c-4f2e-a67d-dfee2e9edc6b.png">|<img width="400" alt="image" src="https://user-images.githubusercontent.com/97446324/187712217-34d0bbb0-9b95-4159-b4a6-9b9ace0bbdfd.png">|
=> Hotfix: Infinity pages

app/locale/en-pseudo/messages.po, lib/utils/getStakingRewards/index.ts, site/components/pages/Home/index.tsx, site/locale/en-pseudo/messages.po, site/locale/en/messages.po, site/pages/index.tsx
adds 2 decimal places to the staking rewards and change from weekly to monthly
I dont think so. smol change.
Resolves #661
=> add decimals to staking rewards displayed

lib/components/Buttons/ButtonBase.tsx, site/components/Form/InputField/index.tsx, site/components/pages/Resources/ResourcesList/index.tsx, site/components/pages/Resources/ResourcesList/styles.ts, site/components/pages/Resources/index.tsx, site/components/pages/Resources/lib/getResourcesListErrorTranslations.ts, site/components/pages/Resources/styles.ts, site/lib/queries.ts, site/locale/en-pseudo/messages.po, site/locale/en/messages.po, site/pages/resources/index.tsx
This PR is adding a Search Input field on top of the resources list.
The search results are sorted by their score value.
If no matching search result was found => a basic error message is shown.
The rendering for this will change later for sure when the other components are added to the page too.
https://preview-cms.vercel.app/resources
Part of https://github.com/KlimaDAO/klimadao/issues/534
=> Resources: Add Search Input

site/components/Form/InputField/index.tsx, site/components/Form/TextareaField/index.tsx, site/components/pages/Pledge/PledgeForm/index.tsx, site/components/pages/Pledge/lib/formSchema.ts, site/components/pages/Pledge/lib/index.tsx, site/components/pages/Resources/ResourcesList/index.tsx, site/components/pages/Resources/lib/getResourcesListErrorTranslations.ts
This PR is a side work while working on the new Resources page which will have some new input elements (checkboxes, selects).
Because this PR is touching **all inputs on the PLEDGE site**, I separated this PR from the other one.
- improve types for InputField and TextAreaField (=> see [review comment here](https://github.com/KlimaDAO/klimadao/pull/666#discussion_r960910080))
- improve input fiel error mapping types (=> see [review comment here](https://github.com/KlimaDAO/klimadao/pull/666#discussion_r960928853))
- simplify errors translation mappings for Form components
Preparation for https://github.com/KlimaDAO/klimadao/issues/534
=> Site: refactor Form Elements (Pledge)

app/actions/offset.ts, app/actions/stake.ts, lib/constants/index.ts, lib/utils/getTransactionOptions/index.ts, lib/utils/index.ts
Fetch transaction options from polyscanGasStation (maxFeePerGas & maxPriorityFeePerGas) for offset retirement transactions only.
From @Atmosfearful in https://github.com/KlimaDAO/klimadao/pull/541
Resolves #519
=> 519 better gas price estimations

app/components/views/Home/index.tsx, app/pages/_app.tsx, lib/utils/index.ts, lib/utils/useFocusTrap/index.tsx, lib/utils/useTabListener/index.tsx, site/components/Modal/index.tsx, site/components/pages/Infinity/Cards/styles.ts, site/pages/_app.tsx
Along the way I discovered that outlines werent working on any button, because we never brought over the `user-is-tabbing` logic from the `app`
useFocusTrap ended up being too painful to use on mobile menu, because we can only trap focus there when its open. But I think that's OK because I can still tab through the menu pretty easily.
Modals seem to be working great!
Resolves #684
=> useFocusTrap & fix button outlines while tabbing

app/package.json, lib/package.json, lib/utils/useWeb3Modal/index.tsx, package-lock.json, site/package.json
- migrate to the new Coinbase wallet repo instead of walletlink
- hacky fix for a bug related to coinbase default export being broken since we don't use Babel
- upgrade ethers, torus, coinbase, walletconnect
- force logout by explicitly calling `logout()` on torus accounts before clearing the cache
- disable caching for web3modal
In addition to fixing coinbase #659 this should _hopefully_ fix 3 rare bugs that don't have tickets:
1. `polygon` network modal was incorrectly shown for torus users sometimes
2. infinite re-connect loop would sometimes happen with torus
3. if you have two torus accounts, it wasn't possible to disconnect and log into your other account, because it would always use your previously cached login.
I confirmed that coinbase is working again:
Resolves #659
=> Fix Coinbase and Torus bugs, update web3 dependencies

app/actions/app.ts
It appears we were missing a `-1` to subtract the initial amount of KLIMA staked from the AKR calculation
|![image](https://user-images.githubusercontent.com/91024694/190935884-5d221b5b-2c7b-420e-9389-9a1343ccb640.png) |![image](https://user-images.githubusercontent.com/91024694/190935870-0a49e56c-ecc1-436c-a7f3-104b79a90423.png)|
=> Add missing -1 to AKR calc

site/components/Modal/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/BaseCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/index.tsx, site/components/pages/Pledge/PledgeForm/index.tsx, site/locale/en/messages.po
Iterating on ladytrekker's refactor of how we display i18n error strings.
Form field components conditionally display error strings when its present so we can delegate the responsibility there :)
```js
// InputField.tsx & TextareaField.tsx
{!!props.errorMessage && (
<Text t="caption" className={styles.errorMessage}>
{props.errorMessage}
</Text>
)}
```
=> pledge: form error message refactor

site/components/pages/Pledge/PledgeForm/index.tsx, site/components/pages/Pledge/lib/firebase.ts, site/components/pages/Pledge/lib/putPledge.ts, site/pages/api/pledge/index.ts
Implements on-demand revalidation users successfully updates their pledge.
Pages are cached globally and are regenerated at an interval configured in our app (for `/pledges/[address].tsx` it's approximately 4 mins).
This means an out of date page can be served until the page is regenerated.
Resolves #466
=> pledge: on-demand revalidation

app/components/views/Home/index.tsx, app/package.json, lib/theme/globals.css, package-lock.json, site/.babelrc, site/components/Header/HeaderMobile.tsx, site/package.json
Remove two libs `@emotion/react` and `@emotion/styled` that we don't need anymore
Replaces #583
=> Upgrade emotion, support sourcemaps in site

lib/components/Buttons/ButtonBase.tsx, lib/components/Buttons/ButtonPrimary.tsx, lib/components/Buttons/ButtonSecondary.tsx, lib/components/Buttons/styles.ts, site/components/pages/Pledge/PledgeDashboard/Cards/RetirementsCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/RetirementsCard/styles.ts, site/components/pages/Pledge/PledgeDashboard/index.tsx, site/components/pages/Pledge/PledgeDashboard/styles.ts, site/components/pages/Pledge/PledgeForm/index.tsx, site/components/pages/Pledge/PledgeForm/styles.ts, site/components/pages/Pledge/lib/formSchema.ts, site/components/pages/Pledge/lib/pledgeFormAdapter.ts, site/components/pages/Pledge/types/index.ts, site/locale/en-pseudo/messages.po, site/locale/en/messages.po
I used useFieldArray to add another dynamic list to the "edit pledge" form. No additional firebase work was needed for the api request to save or edit these fields. Right now we are not validating that the pasted address is a valid eth address because of limitations with custom validation in useFieldArray but I may be incorrect and it is possible. I dont like all the conditionals used so If there is a better way I'm all for it. 
We can QA the feature branch at the end. I think this will be easier than explaining what is test data or only stubbed out.
=> add form fields for multi wallet pledge

site/components/Navigation/index.tsx
As per #722 the Infinity nav item is now a multi option drop down containing links to `/infinity` and `/pledge`
Resolves [#722](https://github.com/KlimaDAO/klimadao/issues/722)
|![image](https://user-images.githubusercontent.com/7104689/194744117-d9272790-b99f-4992-a87f-6488f1459ae8.png)|![image](https://user-images.githubusercontent.com/7104689/194744090-31b1c7fb-c44a-4ef1-b548-7effc1a74f07.png)|
=> Update infinity nav to include pledge (#722)

site/components/pages/Retirements/SingleRetirement/DownloadCertificateButton/generateCertificate.ts
Generated retirement date on certificate did not account for month starting on 0 😓 
Resolves #753
=> [urgent] hotfix: retirement certificate showing wrong retirement month

app/components/ChangeLanguageButton/index.tsx, app/lib/i18n.ts, lib/constants/index.ts, lib/package.json, lib/utils/getLocales/index.ts, lib/utils/index.ts, package-lock.json, site/components/ChangeLanguageButton/index.tsx, site/lib/i18n.ts, site/next.config.js
Single source of truth for locale information
If we want to have the Opportunity to have differences between app and site we can make the getLocales function parametrized.
Resolves #nothing
It is related to @Atmosfearful comment here: https://github.com/KlimaDAO/klimadao/pull/728#pullrequestreview-1125566392
None
=> Single source of truth for locale information

site/components/pages/Pledge/PledgeDashboard/Cards/AssetBalanceCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/Cards/FootprintCard/index.tsx, site/components/pages/Pledge/PledgeDashboard/Profile/index.tsx, site/components/pages/Pledge/PledgeDashboard/index.tsx, site/components/pages/Pledge/lib/mockPledge.ts, site/locale/en-pseudo/messages.po, site/locale/en/messages.po
Complete the following tasks on the PledgeDashboard
^ **Since fetching transaction history per contract was not a simple task a compromise here was to only show assets with balance > 0**
**Note:**
* Please test with number of categories greater than 4 (for the FootprintCard and it's graph)
* @jabby09 font sizes seem larger in the app than in designs
Resolves #712 
|![image](https://user-images.githubusercontent.com/7104689/195721710-df1a4e9a-08ed-443a-86b9-84bc1e7fcd93.png)|![image](https://user-images.githubusercontent.com/7104689/195721766-8acc8e8d-a46b-40fe-bfc0-ff77baed4691.png)|
=> Remaining enhancements to complete beta (#712)

lib/utils/useWeb3Modal/index.tsx
torus triggers the `chainChanged` event when it loads, which causes a refresh, sometimes this becomes an infinite loop, othertimes it only loops 2-3 times before stopping.
This PR removes the chainChanged listener. If users switch away from polygon after the app is loaded, that is their problem now, we no longer show the warning modal. The warning modal still shows the first time the app loads though.
Also I was not cleaning up the disconnect listener in useEffect but this was not the cause of the problem. Fixed anyways.
=> Fix: torus refresh loop

site/pages/pledge/[address].tsx, site/pages/retirements/[beneficiary]/index.tsx
Redirect to lowercased url if uppercased address or domain is detected.
Also improves caching as caching is url case-sensitive.
Resolves #725
=> Enforce lowercased urls

site/components/pages/Pledge/lib/formSchema.ts, site/types/yup.d.ts
Extend `yup.string` validation methods to include custom `.isAddress()` method
Throws a validation error if string is not an ethereum address
```ts
// Using the name attribute as an example
yup.object({
name: yup
.string()
.isAddress("pledges.form.errors.name.isAddress")
})
```
| Invalid Address  | Valid address  |
|<img width="523" alt="image" src="https://user-images.githubusercontent.com/97446324/199631231-5056fe5d-d79d-4b12-b029-e5d3609f67b9.png">|<img width="540" alt="image" src="https://user-images.githubusercontent.com/97446324/199631151-6134781b-02ce-4b6f-bc4b-9ac192611dc0.png">|
=> [site] add yup.string.isAddress custom validation

app/actions/app.ts, app/actions/bonds.ts, app/actions/offset.ts, app/actions/pklima.ts, app/actions/stake.ts, app/actions/user.ts, app/actions/utils.ts, app/actions/wrap.ts, app/components/views/Wrap/index.tsx, app/lib/hooks/useENS.ts, lib/package.json, lib/utils/createLazyWeb3Modal/index.ts, lib/utils/formatUnits/index.ts, lib/utils/getAllowance/index.ts, lib/utils/getContract/index.ts, lib/utils/getInteger/index.ts, lib/utils/getIsValidAddress/index.ts, lib/utils/getTransactionOptions/index.ts, lib/utils/getWeb3Modal/index.ts, lib/utils/useWeb3Modal/index.tsx, package-lock.json, site/components/pages/Pledge/index.tsx, site/components/pages/Pledge/lib/verifyGnosisSafeMultisig.ts, site/components/pages/Pledge/lib/verifySignature.ts, site/lib/getAddressByDomain.ts, site/pages/api/event-demo/index.ts, site/pages/pledge/[address].tsx, site/pages/retirements/[beneficiary]/[retirement_index].tsx, site/pages/retirements/[beneficiary]/index.tsx
1. Lazyload `web3modal` and all wallet provider dependencies (`coinbase`, `torus-embed`, `wallet-connect`) only after page mount, and only on pages where the web3 hook is used. We should maintain this pattern for #660 
2. upgrade @torus-embed which does reduce the size of the lazy-loaded bundle by ~200kb
3. don't import entire ethers object (this did not end up reducing any kb)
4. remove @ethersproject import (this also had no impact)
Follow my commit history for easier review.
First Load JS shared by all 1.01 MB
First Load JS shared by all 221 kB
#720 
This will conflict with work on #660
=> Reduce _app bundle size -800kb

site/components/pages/Retirements/SingleRetirement/RetirementValue/index.tsx
Add `objectFit="contain"` to retirement token icon for app
@ShimonD-KlimaDAO  here is the PR
Resolves #769
=> object fit for icon

lib/constants/index.ts
Fix pledge url defined in `lib/constants`
=> hotfix: fix correct pledge url

app/components/NavMenu/index.tsx
Replace static string with CopyAddressButton in `app/components/NavMenu`
Resolves #824
|<img width="256" alt="image" src="https://user-images.githubusercontent.com/7104689/208531341-fdeeed2f-3061-4192-8bf9-e253a45157e5.png">|<img width="223" alt="image" src="https://user-images.githubusercontent.com/7104689/208531434-d99be00b-325e-4f0c-8a74-3494d39dd251.png">|
=> Copy Address Button in App Nav (#824)

lib/components/ConnectModal/index.tsx, site/components/pages/Pledge/HeaderDesktop/index.tsx, site/components/pages/Pledge/HeaderMobile/index.tsx, site/components/pages/Pledge/index.tsx
The blue connect modal button theming does not match the klima green in /app.
This seems like a regression. 
This PR extends `<ConnectModal />` to take a prop to configure button style variant.
Resolves #846 
|<img width="600" alt="image" src="https://user-images.githubusercontent.com/97446324/209342529-8fa2a829-f45c-4858-bc9b-2ba004aee9f0.png">|<img width="600" alt="image" src="https://user-images.githubusercontent.com/97446324/209342568-5db68b01-8487-4322-a23c-fca4ee6ce71e.png">|
=> fix: allow connect modal to set button style variant

site/components/pages/Retirements/SingleRetirement/ProjectDetails/List/index.tsx, site/components/pages/Retirements/SingleRetirement/ProjectDetails/List/styles.ts, site/components/pages/Retirements/SingleRetirement/ProjectDetails/index.tsx, site/components/pages/Retirements/SingleRetirement/ProjectDetails/styles.ts
For moss retirement project details:
- Point headline link to "https://mco2token.moss.earth/"
- Add secondary link to the mco2 carbon dashboard 
Resolves #821 
|<img width="600" alt="image" src="https://user-images.githubusercontent.com/97446324/209416049-c81778d3-a659-4ba0-ad4d-0a0d342b7a63.png">|<img width="600" alt="image" src="https://user-images.githubusercontent.com/97446324/209416057-9ac637ec-8efe-4a49-8d9c-92fdfdf913a7.png">|
=> [retirements] Update mco2 project details

app/components/views/Offset/ProjectSearch/ProjectSearchForm/index.tsx
Only allow projects with more than 1 tonnage remaining to be selected from the advanced selective retirement flow.
Resolves #819
=> [selective-retirements] Select from projects with more than 1 tonne remaining

lib/components/ConnectModal/index.tsx
The modal gets stuck in an error state if the user closes the modal in error state and re opens it. 
=> reset modal to connect state when opening

site/components/pages/Pledge/HeaderDesktop/index.tsx
Klima green making a comeback
Verification:
https://klimadao-site-git-change-pledge-connect-button-26162d-klimadao.vercel.app/pledge/markcuban.klima
Resolves #872
=> hotfix: revert pledge connect button to klima green

site/components/Form/InputField/index.tsx, site/components/Form/InputField/styles.ts, site/components/pages/Pledge/PledgeForm/index.tsx, site/components/pages/Resources/FeaturedArticles/Article.tsx, site/components/pages/Resources/FeaturedArticles/ArticlesSlider.tsx, site/components/pages/Resources/FeaturedArticles/styles.ts, site/components/pages/Resources/ResourcesList/index.tsx, site/components/pages/Resources/ResourcesList/styles.ts, site/components/pages/Resources/SortyByDropDown/index.tsx, site/components/pages/Resources/SortyByDropDown/styles.ts, site/components/pages/Resources/styles.ts, site/locale/en/messages.po
Noticed the resource centre was looking a bit off so went on a small rabbit hole of various enhancements.
Note the rounded button in the image below. I don't recall it being designed like that 🤔
Summary of changes:
- Resource search field updated to include focus styles & add icon to left of input
- Added padding to header on various viewports
- Add `scroll-snap-align: start` to featured articles so a full featured article is always in view
Regressions discovered:
- Buttons with icons automatically shaped as a circle => #861 
- Site modal no longer has a dimmed background overlay => #862
=> [resources] Resource centre ui enhancements

app/components/views/Offset/ProjectSearch/SelectProjectButton/index.tsx, app/components/views/Offset/ProjectSearch/SelectProjectButton/styles.ts
@theprofessora, I've made these further changes:
- "View project details" looked too wordy, "Project details" as an outbound link can be inferred from the iconography
- Made the font colour lighter to lower its visual heirarchy
Resolves #863 
|<img width="300" alt="image" src="https://user-images.githubusercontent.com/97446324/212527009-8762b041-fc34-4dfe-9ad0-97cdad319fc6.png">|<img width="300" alt="image" src="https://user-images.githubusercontent.com/97446324/212526995-54ef7e90-dd22-4d9b-b236-4a042eafbea5.png">|
=> [retirement_filters] add verra link to project details card

lib/abi/KlimaRetirementAggregatorV2.json, lib/utils/getContract/index.ts
Add `KlimaRetirementAggregatorV2` abi to lib.
[Contract documentation](https://docs.klimadao.finance/developers/contracts/retirement/v2-diamond)
[Contract explorer](https://louper.dev/diamond/0x8cE54d9625371fb2a068986d32C85De8E6e995f8?network=polygon)
=> [redemption] add v2 aggregator abi

app/components/DropdownWithModal/index.tsx, app/components/views/Offset/index.tsx, app/locale/en-pseudo/messages.po, app/locale/en/messages.po, site/locale/en-pseudo/messages.po
This PR fixes an issue where a user can enter a fractional quantity when inputting the tonnes of carbon to offset (when the "Credit Card" option is selected as the payment method.
Resolves #818
|<img width="600" alt="Screenshot 2023-01-13 at 23 11 21" src="https://user-images.githubusercontent.com/92357475/212435519-ec4a2ae8-d830-4e0d-a774-aac89c894059.png"> | <img width="600" alt="Screenshot 2023-01-13 at 23 11 56" src="https://user-images.githubusercontent.com/92357475/212435585-1d9e34eb-24ae-4e0c-947d-9afe5f1c7ec9.png">|
=> fix(app): don't allow fractional quantities when fiat

lib/components/Buttons/styles.ts, lib/components/ConnectModal/index.tsx, site/components/pages/Pledge/index.tsx
This was bothering me for months so I had to jump on it.
- add "connecting" label and disabled state (when connection is still pending)
- add "view your pledge" instead of "create pledge" when the user is already connected
- only show "create pledge" when not connected
- use modal onClose callback to detect when the user cancels the connect modal (reset button state)
- Fix a css issue where disabled button styles were not working for blue buttons,
- Fix a css issue where disabled buttons had an incorrect hover state (text should stay gray and not turn white on hover)
=> Better pledge redirect UX

app/actions/app.ts, app/actions/bonds.ts, app/actions/offset.ts, app/actions/user.ts, app/components/views/Bond/index.tsx, app/components/views/Home/index.tsx, app/components/views/Offset/index.tsx, lib/utils/getRetirement/index.ts, lib/utils/getStaticProvider/index.ts, lib/utils/getTreasuryBalance/index.ts, site/lib/getBalances.ts
This PR enhances `getStaticProvider` to support a `batchRequests` parameter which is `true` by default.
When `batchRequests` is `true`, we use `JsonRpcBatchProvider` instead of the normal `JsonRpcProvider`.
The BatchProvider does a single https request for multiple calls. Magic!
This pr also changes how default providers are instantiated to avoid unnecessary calls to mumbai and ethereum rpcs.
Based on these experiments I decided it is worth it to use `batchRequests: true` as the default setting, simply to reduce the number of requests (cost savings) with minimal change to actual page performance.
/#/offset page, while connected, full page refresh with cache disabled:
```
143 requests
522 kB transferred
1.5 MB resources
Finish: 2.04 s
DOMContentLoaded: 364 ms
Load: 592 ms
```
As an …
=> Use JsonRpcBatchProvider by default

lib/components/ConnectModal/index.tsx, lib/components/ConnectModal/styles.ts
If wallet is injected then that wallet is used. If this wallet is not metamask or brave then a generic wallet button is shown. If the wallet is coinbase then it will connect without using the sdk.
@ShimonD-KlimaDAO do you mind testing this one? Adding expected behavior shortly.
Resolves #881
=> add generic browser wallet button

cms/schemas/podcast.js
This PR adds a new field to the podcast schema called `rssId`. This is the first PR of 3 as suggested in #908 and will need to be deployed to sanity studio.
Resolves #908
=> add rss id to podcast schema

site/components/pages/Pledge/lib/pledgeAttributes.ts, site/pages/pledge/[address].tsx
The redirects were not working because they were case sensitive. We now force all secondary wallet addresses to be lowercase in putPledgeAttributes.
@ShimonD-KlimaDAO you will need to remove and re-add the secondary wallets but it should redirect now.
Resolves #850
=> fix redirect for parent pledge

site/components/pages/Resources/lib/queries.ts, site/lib/queries.ts
* add `isDomainKlimadao` filter to all Sanity queries
=> Add domain filter to queries

lib/components/ConnectModal/index.tsx, lib/components/ConnectModal/styles.ts
I added tab indexes to the modal content because the focus trap wasn't working. The tabbing is off on the error step and I cant figure out why the tab indexes are getting messed up. I also added a handler for enter button press when buttons are focused.
Resolves #830
=> fix focus trap for connect and enter key listeners

app/components/CarbonTonnesRetiredCard/index.tsx, app/components/CarbonTonnesRetiredCard/styles.ts, app/locale/en-pseudo/messages.po, app/locale/en/messages.po, site/locale/en-pseudo/messages.po
Adds a "View Retirements" button to the Carbon Tonnes retirement card when a user has 1 or more retirements. The card remains as is if a user has 0 retirements.
Resolves #864 
|<img width="650" alt="Screenshot 2023-01-31 at 21 56 16" src="https://user-images.githubusercontent.com/92357475/215893062-904a0045-c5c9-4a6c-8fe9-e2c3431dfae0.png">|<img width="650" alt="Screenshot 2023-01-31 at 21 55 51" src="https://user-images.githubusercontent.com/92357475/215893098-660fb278-c137-4c87-88c3-7f89e40e1bbb.png">|
=> add view retirements button to carbon tonnes retired card

cms/schemas/podcast.js, site/components/pages/Resources/lib/queries.ts, site/lib/queries.ts
Clean up of embed codes on podcasts which were replaced by rss id's in #908.
Resolves #908
=> cleanup embed codes

lib/utils/useProvider/index.tsx
If the users session expires on their wallet but the web3-wallet value is still in local storage then the app tries to reconnect them. This brings up the modal and when the user closes the rpc modal and triggers the refusal error the item is now cleared from storage.
Resolves #902 
Resolves #868
=> remove web3wallet from local storage on refusal

site/pages/_app.tsx
import vars before globals in site using a new line to tell auto sort to ignore it
Resolves #943
=> import vars before globals in site

app/components/views/Offset/index.tsx
We were doing unsafe math in getApproval in the Offset view.
=> Fix USDC decimals in Offset view

carbonmark/lib/networkAware/getTokenDecimals.ts, lib/utils/getAllowance/index.ts
I wasn't able to purchase a listing with testnet on localhost due to a wrong formatting of the fake USDCs
This is the fix.
Please review carefully 🙏
=> Fix allowances for testnet

app/components/views/Offset/index.tsx
Reduces the spending allowance of `retirementAggregatorV2` by the `cost` of the `paymentMethod` token after retirement.
Given that the spender is the V2 contract, this branch is a branch of the PR #960 . The relevant change to `staging`, separate from #960 is here -> [decrementAllowance](https://github.com/KlimaDAO/klimadao/compare/tufnel/fix-decrement-allowance-post-retirement?expand=1#diff-b68c42fa04a583195c0f40a15e663dcebdd59c469a31bac00a34e1848e2a6c06R382-R387)
@Atmosfearful
Resolves #964
=> (replaces #965) Tufnel/Decrement Allowance of Payment Token after retirement

carbonmark/components/pages/Project/index.tsx, carbonmark/hooks/useFetchProject.ts, carbonmark/pages/projects/[project_id]/index.tsx
Please test that the following works:
- Go to a Single Project page of the [preview link](https://carbonmark-git-lady-swr-for-cache-klimadao.vercel.app/projects)
- Click on "Buy" of a listing
- Purchase this Listing
- On the Purchase Receipt page => click on the link above "back to project details"
- The same former Single Project Page is rendered
- => The **activity** should contain your just bought listing purchase ✔️ 
- => The **listing** you bought should be gone on that Project page ✔️ 
Please keep in mind that the backend can still be slow !
We might want to integrate a refresh interval if a user is logged in for these pages.
Part of https://github.com/KlimaDAO/klimadao/issues/1019
=> Use SWR for Single Project

carbon-projects/sanity.cli.ts, carbon-projects/sanity.config.ts, carbon-projects/schemas/project.ts
=> format-all for carbon-projects CMS

carbonmark/components/Activities/Activity.tsx, carbonmark/components/Activities/index.tsx, carbonmark/components/pages/Home/index.tsx, carbonmark/components/pages/Project/BuyOptions/SellerListing.tsx, carbonmark/components/pages/Project/Purchase/PurchaseForm.tsx, carbonmark/components/pages/Project/Purchase/index.tsx, carbonmark/components/pages/Project/index.tsx, carbonmark/components/pages/Purchases/index.tsx, carbonmark/components/pages/Users/Listing/index.tsx, carbonmark/components/pages/Users/SellerConnected/Forms/EditListing.tsx, carbonmark/components/pages/Users/SellerConnected/ListingEditable.tsx, carbonmark/hooks/useFetchProjects.ts, carbonmark/lib/actions.ts, carbonmark/lib/getTokenInfo.ts, carbonmark/lib/listingsGetter.ts, carbonmark/lib/projectGetter.ts, carbonmark/lib/types/carbonmark.ts, carbonmark/pages/projects/[project_id]/purchase/[listing_id].ts, carbonmark/pages/projects/index.tsx
I looked at the real JSON data on prod and aligned the types.
I separated the activity types into UserActivity and ProjectActivity because they differ between these endpoints
I should have separated the Listing types as well, but it was faster to just use `Omit<Listing, "project">` where needed.
Then I addressed all the downstream issues that were exposed.
Some TODOs on the backend still, which I marked in the carbonmark types file, and will direct najadas attention to.
Closes #1007
=> Resolve type discrepancies

cms/schemas/post.js, site/components/pages/Resources/ResourcesList/index.tsx, site/components/pages/Resources/lib/queries.ts, site/lib/queries.ts, site/pages/blog/[pid].tsx, site/pages/index.tsx, site/pages/resources/index.tsx
=> Add translated blog posts

carbonmark/components/pages/Portfolio/CarbonmarkAssets.tsx, carbonmark/components/pages/Portfolio/PortfolioSidebar.tsx, carbonmark/components/pages/Portfolio/index.tsx, carbonmark/components/pages/Portfolio/styles.ts, carbonmark/hooks/useFetchUser.ts, carbonmark/lib/api.ts
Please test that the following works:
**Connect**
- Go to your Portfolio on the [preview link](https://carbonmark-git-lady-swr-portfolio-klimadao.vercel.app/portfolio)
- You should see the LoginCard ✔️ 
- When you connect your wallet, you should see a loading spinner ✔️ 
- When your wallet is connected, you see your assets correctly displayed ✔️ 
- If you do not have any assets, you should see an empty state message ✔️ 
**Create a Listing**
- Click on "Sell" of one your assets
- Create a Listing with one of your assets
- Wait until the success modal appears **=> CLOSE THIS MODAL !** (Going to the Profile is not in scope of this PR)
- You should see now two loadings spinners with "Loading your assets" ✔️ 
- The frontend polls the API to wait until the backend updated your user data with …
=> Update Portfolio data and cache with SWR

carbonmark/lib/projectGetter.ts
When running carbonmark locally with testnet => a lot of projects are hardcoded!
These projects do not have the `methodologies` array from which the category data is retrieved.
=> Page generation fails with "can not read ... of undefined"
This PR fixes that.
Again the same as in https://github.com/KlimaDAO/klimadao/pull/1023
=> Fix testnet project categories

carbonmark/components/pages/Project/index.tsx, carbonmark/components/pages/Project/styles.ts, carbonmark/components/pages/Projects/index.tsx, carbonmark/components/pages/Projects/styles.ts, carbonmark/lib/projectGetter.ts, carbonmark/lib/types/carbonmark.ts
This ticket adds support for multiple methodology tags on project cards and on the project header information.
Resolves #985
=> add support to cards for multiple methodologies

carbonmark/lib/projectGetter.ts
Null checks on projectGetter functions were failing on empty project arrays
|<img width="834" alt="image" src="https://user-images.githubusercontent.com/7104689/233520049-4a9e9c00-be1a-437e-9fe9-19bda8a58524.png">|<img width="834" alt="image" src="https://user-images.githubusercontent.com/7104689/233520217-8ff5194d-92a6-4f7b-93a1-f10d42450820.png">|
=> Fix null check on projectGetter.ts

carbonmark/components/Activities/Activity.tsx, carbonmark/components/Activities/styles.ts, carbonmark/components/ProjectKey/index.tsx, carbonmark/components/ProjectKey/styles.ts, carbonmark/components/pages/Portfolio/AssetProject/index.tsx, carbonmark/components/pages/Portfolio/AssetProject/styles.ts
On the portfolio page:
1) Added projectId-key
2) Image and project title link to project page
3) Hover styles applied to title
Activity feed:
1) Project title is links to project page and has hover styles applied
Reviewers: @Atmosfearful @ShimonD-KlimaDAO 
Resolves #997 
| <img width="1203" alt="portfolio before" src="https://user-images.githubusercontent.com/72105234/233521786-21f61782-dae6-457d-bb50-b8db33b26432.png"> | <img width="755" alt="portfolio after" src="https://user-images.githubusercontent.com/72105234/233521818-e0a9a1c1-0aa3-41bb-9234-06b834762d43.png"> |
| <img width="369" alt="Screen Shot 2023-04-20 at 9 35 36 PM" src="https://user-images.githubusercontent.com/72105234/233521864-bfb341bd-208 …
=> Links and key added to Portfolio page

.github/actions/check-status/jest.config.js, .github/actions/check-status/package-lock.json, .github/actions/check-status/package.json, .github/dependabot.yml, .github/workflows/update_translations.yml
See https://github.com/KlimaDAO/klimadao/issues/1058
The command set-output has to be replaced 🤞 
This PR also includes:
- update all packages for github-actions/check-status
- explicitly import ts-jest (test fail otherwise 🦐 )
- fix path to dependabot checks for npm actions
Closes #1058
=> Update github actions, replace set-output command

carbonmark/components/pages/Users/SellerConnected/index.tsx
Forces the view to scroll to the top after editing or creating a listing.
Resolves #987
=> force scroll to top after editing/creating listing

carbonmark/components/Activities/Activity.tsx, carbonmark/components/pages/Project/BuyOptions/SellerListing.tsx, carbonmark/lib/projectGetter.ts, carbonmark/pages/api/categories/index.ts, carbonmark/pages/api/countries/index.ts, carbonmark/pages/api/projects/[project_id].ts, carbonmark/pages/api/projects/index.ts, carbonmark/pages/api/users/[user].ts, carbonmark/pages/api/users/index.ts, carbonmark/pages/api/users/login/index.ts, carbonmark/pages/api/users/login/verify/index.ts, carbonmark/pages/api/vintages/index.ts
Shows user handle name where possible instead of the wallet address.
The only place this is currently not possible is where the type is UserActivity, which looks to be on the user page. There is a note from two days ago that this is being added to the api response, so sounds like this will be a quick fix to add once that is done. 
Also in this PR:
1) small chaining issue in Project Getter
2) fixed some error types so the linter is satisfied.
Reviewers:
@Atmosfearful 
@ShimonD-KlimaDAO 
Resolves #988 
|<img width="596" alt="before1" src="https://user-images.githubusercontent.com/72105234/233407421-6a0dc793-0f5e-4fc1-a2f5-5adbcdaa272a.png"> |<img width="636" alt="after1" src="https://user-images.githubusercontent.com/72105234/233407522-40b0943c-d044- …
=> #988 Show handle names

site/locale/de/messages.po, site/locale/es/messages.po, site/locale/fr/messages.po, site/locale/hi/messages.po, site/locale/ru/messages.po
This reverts commit 7c41481686c9381fac7ee42dbad1ab9b19ec2310.
This commit destroyed a lot of strings-- we had accidentally set carbonmark to the same translation.io project so it destroyed those strings remotely, and then pulled them in locally and committed the via github actions.
=> Revert "Extract translation strings"

carbonmark/components/pages/Portfolio/CarbonmarkAssets.tsx, carbonmark/components/pages/Portfolio/index.tsx, carbonmark/components/pages/Users/SellerConnected/index.tsx, carbonmark/lib/api.ts
As discusses in this ticket https://github.com/KlimaDAO/klimadao/issues/1100
we can not rely on the activity array length to check when the backend is done with updating the data.
Instead, we can check for the timeStamp in the latest activity. This is the refactoring for that.
Additionally, this PR contains these super tiny fixes:
- fix the check for empty assets which shows an empty state message
- better text for the success modal
Closes https://github.com/KlimaDAO/klimadao/issues/1100
| <img width="634" alt="Bildschirmfoto 2023-05-02 um 17 23 58" src="https://user-images.githubusercontent.com/95881624/235714027-009c84eb-1824-473e-b8ff-65b1fabe4d62.png"> | <img width="635" alt="Bildschirmfoto 2023-05-02 um 17 24 53" …
=> Poll until the latest activity timeStamp is new

carbon-projects/schemas/index.ts, carbon-projects/schemas/project.ts, carbon-projects/schemas/projectContent.ts
Adds a top-level document type called Project Content which is where any "unofficial" content should go, whether human or ai-generated.
Moves Image gallery and banner image fields to this new type.
Adds short description, long description, and meta fields
=> [carbon-projects] Add Project Content document type

.github/workflows/wait_for_status_check.yml
The latest workflows for "schedule auto merge" did fail. 
See https://github.com/KlimaDAO/klimadao/actions
The reason for this was that the status checks for the last commit on branch `staging` within the defined threshold of 240 seconds were still in the "pending" status. In this case the merge from `staging` to `main` is never executed.
I assume that since the update of several dependencies in this PR https://github.com/KlimaDAO/klimadao/pull/1070 Vercel needs longer to build all three sites (site, app, carbonmark).
Because since this upgrade commit the actions do fail on `staging`.
This PR increases the timeout for the check-status action with the assumption that this will help the workflow "schedule auto merge" to run successfully again.
=> Increase github action status check timeout

carbonmark/components/Layout/index.tsx, carbonmark/lib/constants.ts
The strings haven't been shown at all. This is the fix.
None
| ![Bildschirmfoto 2023-05-03 um 17 13 29](https://user-images.githubusercontent.com/95881624/236200297-7b15e97f-b336-4c37-98ae-d42f6b3a59e2.png) | <img width="469" alt="Bildschirmfoto 2023-05-04 um 14 10 33" src="https://user-images.githubusercontent.com/95881624/236200177-56f98458-bc51-4afd-b7df-60e79a296441.png"> |
=> Fix Connect Modal error strings

carbonmark/components/Activities/Activities.constants.ts, carbonmark/components/Activities/Activity.tsx, carbonmark/lib/formatWalletAddress.ts, carbonmark/lib/types/carbonmark.ts, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po
Backend sends down the handle for seller and buyer on the activity data.
These handles are shortened if the length is more than 11 characters.
However, if the current connected user is included in the activity data => "You" should be shown and not the user´s handle.
Same as for the wallet addresses.
None
| <img width="484" alt="Bildschirmfoto 2023-05-04 um 15 11 59" src="https://user-images.githubusercontent.com/95881624/236218196-06c1de78-f15a-45b7-82e6-ba2783db5b15.png"> | <img width="537" alt="Bildschirmfoto 2023-05-04 um 15 12 28" src="https://user-images.githubusercontent.com/95881624/236218246-4a3b3f29-72ba-4560-b9ba-7398b5895166.png"> |
=> Fix: handle should fallback to "You" on connected user

carbonmark/components/Footer/index.tsx, carbonmark/components/Layout/NavDrawer/index.tsx, carbonmark/components/Layout/NavDrawer/styles.ts, carbonmark/components/pages/Home/index.tsx, lib/constants/index.ts
Currently a WIP
Resolves #1040
=> make adjustments to footer

carbonmark/components/pages/Portfolio/AssetProject/index.tsx, carbonmark/components/pages/Portfolio/index.tsx, carbonmark/components/pages/Portfolio/styles.ts, carbonmark/components/pages/Retire/CustomizableModal/index.tsx, carbonmark/components/pages/Retire/CustomizableModal/styles.ts, carbonmark/components/pages/Retire/RetireForm/index.tsx, carbonmark/components/pages/Retire/RetireModal/index.tsx, carbonmark/components/pages/Retire/RetirementStatusModal/index.tsx, carbonmark/components/pages/Retire/RetirementStatusModal/styles.tsx, carbonmark/components/pages/Retire/index.tsx
Wired up buttons to new retirement flow and used next/link where previously omitted.
Fixed a `<p>` nesting error in the CustomizableModal to allow for formatted titles w/o nesting error
Included a spinner for while web3 is initializing. With the new wire-ups and using Link it was difficult to find a case where this spinner actually showed.
Resolves #1174
=> Connected buttons to new retirement flow and loading spinner

carbonmark/components/pages/Retire/CustomizableModal/index.tsx, carbonmark/components/shared/Header/HeaderMobile.tsx, carbonmark/components/shared/Modal/index.tsx, lib/components/ConnectModal/index.tsx, lib/utils/index.ts, lib/utils/useScrollLock/index.tsx, site/components/Header/HeaderMobile.tsx, site/components/Modal/index.tsx
We weren't properly cleaning up the scroll lock in many places.
I abstracted this to a reuseable hook so we don't make this mistake anymore.
Resolves #1199
=> add useScrollLock, fix 1199

carbonmark/components/pages/Project/Retire/AssetDetails.tsx, carbonmark/components/pages/Project/Retire/RetireForm.tsx, carbonmark/components/pages/Project/Retire/TotalValues.tsx, carbonmark/lib/actions.retire.ts, carbonmark/lib/getPoolData.ts, carbonmark/lib/types/carbonmark.ts
This PR updates the price types according to the updated API schema mentioned in this ticket: https://github.com/KlimaDAO/klimadao/issues/1160
Now, a retirement from a project's pool calculates and shows the total costs correctly.
If a pool token is the default project of a pool => Retire needs only the SushiSwap fee and 0,1% Aggregator fee
**NBO (default => less fees)** 
https://carbonmark-git-lady-prices-schema-klimadao.vercel.app/projects/VCS-981-2014/retire/pools/nbo
**NCT (calculate all fees)** 
https://carbonmark-git-lady-prices-schema-klimadao.vercel.app/projects/VCS-981-2014/retire/pools/nct
See here the **API response** for this project:
https://api.carbonmark.com/api/projects/VCS-981-2014
=> the prices array shows the pools which are rendered in the pages above
Ticket …
=> Retire default of specific from pool

carbon-projects/schemas/methodology.ts
Adding this link field so we can have a click-through on the tooltip for a project's methodology
This allows the user to learn more about the underlying methodology used by a project without having to dig around on the registry website
Subsequent work is required to surface this link field in the API, and integrate it into the user interface as a link on the tooltip for each project page and the project cards on the search page
=> Add link field to methodology type in carbon-projects CMS

carbonmark/components/Footer/index.tsx, carbonmark/components/pages/Home/index.tsx, carbonmark/components/shared/Navigation/index.tsx, carbonmark/lib/constants.ts
Replaces the help link to the carbonmark docs on the carbonmark homepage header/footer & app footer.
Resolves #1213
=> 0xMakka - update links to carbonmark docs

carbonmark/components/Layout/index.tsx, carbonmark/components/Layout/styles.ts, carbonmark/components/ProjectCard/index.tsx, carbonmark/components/ProjectCard/styles.ts, carbonmark/components/pages/Retire/index.tsx, carbonmark/components/pages/Retire/styles.ts, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po, carbonmark/pages/retire/index.tsx
~**🔥 ~MERGE IS BLOCKED BY THIS [PR](https://github.com/KlimaDAO/klimadao/pull/1224)~ 🔥** ~ ✔️ 
This PR adds hardcoded featured projects to the Retire view.
- The link "View all Projects" is moved to the right as it was hard to properly align this link with the main headline which breaks on smaller screens (and breaks into centered or left alignment depending on the browser size)
- The project description height is fixed which doesn't work well with the super long project title of the second project as now the description is cut off differently
- => maybe change/shorten the project title of the second project (in CMS??) 
Preview URL: https://carbonmark-git-lady-retire-featured-projects-klimadao.vercel.app/retire
Resolves https://github.com/KlimaDAO/klimadao/issues/1209
=> Retire: Add featured Projects

carbonmark/components/Stats/StatsBar.tsx, carbonmark/components/Stats/index.tsx, carbonmark/components/Stats/styles.ts, carbonmark/components/TextInfoTooltip/index.tsx, carbonmark/components/pages/Project/index.tsx, carbonmark/components/pages/Project/styles.ts
Added explanatory tooltips and link to project details page.
One style note where there was a discrepancy:
The figma tooltip design:
didn't match current tooltips already on the project page:
I matched the tooltip design to what currently exists on the project page for consistency. If that needs to be changed let me know.
Resolves #969 
|![Screen Shot 2023-06-19 at 12 44 05 PM](https://github.com/KlimaDAO/klimadao/assets/72105234/1bec8fa6-acf6-45f3-9047-d3d3aa602c52)
|![Screen Shot 2023-06-19 at 12 43 17 PM](https://github.com/KlimaDAO/klimadao/assets/72105234/bfa56c86-7f42-4c78-8152-62f679b19d07)|
=> tooltips and link added

carbonmark/components/pages/Project/BuyOptions/PoolPrice.tsx, carbonmark/components/pages/Project/Retire/TotalValues.tsx, carbonmark/lib/createUrls.ts
This PR links the "Retire now" button from a Project Pool Price to the correct page.
Still, this issue remains:
- A price for a project might not be correct, see [comment](https://github.com/KlimaDAO/klimadao/issues/1156#issuecomment-1581047026)
- This can result in the total costs for 1 tonne amount being lower than a single unit price per tonne.
- **Please double check** how the total costs are retrieved [here](https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark/lib/actions.retire.ts#L35-L70)
E.G.:
- https://carbonmark-git-lady-link-to-retire-klimadao.vercel.app/projects/VCS-191-2008/retire/pools/bct
- https://carbonmark-git-lady-link-to-retire-klimadao.vercel.app/projects/VCS-1140-2015/retire/pools/ubo
=> the total costs are lower than a single unit price (with 1 tonne amount) …
=> Link to Retire from Pool pages

carbonmark/components/pages/Project/BuyOptions/PoolPrice.tsx, carbonmark/lib/createUrls.ts
This PR links the "Buy" button from a Project Pool Price to the correct page.
Still, this issue remains:
- A price for a project might not be correct, see [comment](https://github.com/KlimaDAO/klimadao/issues/1156#issuecomment-1581047026)
- This can result in the total costs for 1 tonne amount being lower than a single unit price per tonne.
- **Please double check** how the total costs for redeem are retrieved [here](https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark/lib/actions.redeem.ts#L119-L160)
E.G.:
- https://carbonmark-git-lady-link-to-redeem-klimadao.vercel.app/projects/VCS-191-2008/purchase/pools/bct
- https://carbonmark-git-lady-link-to-redeem-klimadao.vercel.app/projects/VCS-1140-2015/purchase/pools/ubo
- https://carbonmark-git-lady-link-to-redeem-klimadao.vercel.app/p …
=> Link to Purchase from Pool pages

carbonmark/components/pages/Retire/FromPortfolio/AssetProject/index.tsx, carbonmark/components/pages/Retire/FromPortfolio/AssetProject/styles.ts, carbonmark/components/pages/Retire/FromPortfolio/index.tsx, carbonmark/components/pages/Retire/FromPortfolio/styles.ts, carbonmark/components/pages/Retire/index.tsx, carbonmark/components/pages/Retire/styles.ts, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po
This PR renders available assets a carbonmark user owns.
Including all states:
- hide when not connected
- loading spinner when connected
- empty state when no assets
- empty state when not a carbonmark user
- render assets with project data
- link to form
When clicking on an asset, the user is taken to the page "retire from portfolio".
This page is a subpage of the Portfolio page (not of the retire page). 
Preview link: https://carbonmark-git-lady-retire-portfolio-klimadao.vercel.app/retire
Resolves https://github.com/KlimaDAO/klimadao/issues/1210
---
=> Retire: Show Assets from Portfolio

app/locale/en-pseudo/messages.po, carbonmark/components/pages/Portfolio/AssetProject/index.tsx, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po, site/locale/en-pseudo/messages.po
Change the text to "Available tonnes:" and make the tonnes value bold.
Resolves #1276 
|<img width="1512" alt="Screenshot 2023-07-03 at 20 12 55" src="https://github.com/KlimaDAO/klimadao/assets/92357475/b5a5da6b-bda6-4e7c-97a8-3bf992cc5c2c">|<img width="1511" alt="Screenshot 2023-07-03 at 20 11 53" src="https://github.com/KlimaDAO/klimadao/assets/92357475/e39b6c7e-7eb1-44e8-9757-60edd1055673">|
=> change text & bold text

carbonmark-api/src/routes/projects/get.ts
Project listings with a price of "0" were previously filtered. This broke once listing.price was correctly typed to a number. This resulted in listings with 0 price being displayed on https://carbonmark.com/projects
=> fix: Correctly filter deleted listings from API

carbonmark/components/Layout/NavMenu/index.tsx, carbonmark/components/ProjectCard/styles.ts, carbonmark/components/pages/Retire/Activity/Quotes.tsx, carbonmark/components/pages/Retire/Activity/Table.tsx, carbonmark/components/pages/Retire/Activity/styles.ts, carbonmark/components/pages/Retire/FromPortfolio/index.tsx, carbonmark/components/pages/Retire/FromPortfolio/styles.ts, carbonmark/components/pages/Retire/index.tsx, carbonmark/components/pages/Retire/styles.ts, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po, carbonmark/pages/retire/index.tsx
This is the last step of the "Retire" epic: Add the menu link for the Retire page
The former closed PRs with discussions to each section have been:
- https://github.com/KlimaDAO/klimadao/pull/1224
- https://github.com/KlimaDAO/klimadao/pull/1238
- https://github.com/KlimaDAO/klimadao/pull/1241
- https://github.com/KlimaDAO/klimadao/pull/1244
Resolves https://github.com/KlimaDAO/klimadao/issues/1248
Preview Link: https://carbonmark-git-lady-link-retire-klimadao.vercel.app/retire
=> Retire: Add menu link

carbonmark/lib/constants.ts
Removes the configuration to point to the pr preview carbonmark api url by default.
This is a temporary solution until we can deploy carbonmark via github action and remove the race condition.
=> Remove automatic preview config

carbonmark-api/package.json, carbonmark-api/src/app.ts, carbonmark-api/src/routes/categories.ts, carbonmark-api/src/routes/countries.ts, carbonmark-api/src/routes/projects/get.ts, carbonmark-api/src/routes/projects/getById.ts, carbonmark-api/src/routes/purchases.ts, carbonmark-api/src/routes/users/get.ts, carbonmark-api/src/routes/users/login/login.ts, carbonmark-api/src/routes/users/login/verify.ts, carbonmark-api/src/routes/vintages.ts, carbonmark-api/src/utils/firebase.utils.ts, carbonmark-api/src/utils/gqlSdk.ts, carbonmark-api/src/utils/helpers/fetchAllPoolPrices.ts, carbonmark-api/src/utils/helpers/fetchMarketplaceListings.ts, carbonmark-api/src/utils/helpers/fetchProjectDetails/fetchVCSProject.ts, carbonmark-api/src/utils/helpers/fetchProjectPoolInfo.ts, carbonmark-api/src/utils/helpers/utils.ts, carbonmark-api/src/utils/marketplace.utils.ts, carbonmark-api/test/plugins/cors.test.ts, carbonmark-api/test/plugins/rate-limit.test.ts, carbonmark-api/test/routes/users/authentication.test.ts, carbonmark-api/tsconfig.json, package-lock.json
bb46856b introduced import aliases to carbonmark-api. These seemed to be working at the time but have since created package.json errors on deployment..
=> fix: revert bb46856b carbonmark-api import aliases

carbonmark-api/src/utils/helpers/utils.constants.ts, carbonmark-api/src/utils/helpers/utils.ts
Removes the check for PRODUCTION in order to use 1e6 decimals in all cases.
Resolves #1300
=> fix:1300 Token Pool Prices to use 1e6 decimals always

carbonmark-api/src/routes/projects/get.ts
This PR removes the truncating logic for project descriptions. It also adds short_descriptions to pooled products, which were missing that field before.
Resolves #967
=> stop truncating project descriptions

carbonmark/components/pages/Retirements/SingleRetirement/index.tsx, carbonmark/components/pages/Retirements/SingleRetirement/styles.ts, carbonmark/pages/retirements/[beneficiary]/[retirement_index].tsx
A quick fix to render a receipt page even though the subgraph can not find it.
Not beautiful, but something.
- Compare with this working [link](https://carbonmark-git-lady-fix-receipt-klimadao.vercel.app/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/28) with subgraph data
- How the page would look like without subgraph data:
Part of https://github.com/KlimaDAO/klimadao/issues/1290
=> Retirement: render receipt with fallback data

carbonmark/components/pages/Retirements/SingleRetirement/index.tsx
Fix:
The receipt page should enforce the browser to reload the page as soon as the subgraph data exists.
This PR and the [one before](https://github.com/KlimaDAO/klimadao/pull/1323) are just fixing the code which already exists.
The processing spinner as well as the browser reload must have been decided before hand.
**Suggestion:**
Instead of reloading the page => the data can also be added to the client. WDYT?
Part of https://github.com/KlimaDAO/klimadao/issues/1290
=> fix: reload receipt page on subgraph data

carbonmark/pages/retirements/[beneficiary]/[retirement_index].tsx, carbonmark/pages/retirements/[beneficiary]/index.tsx
`/retirements`:
Removed RPC calls for totalRetirements and totalCarbonRetired and using the return from the subgraph instead to get the necessary data. 
Promise.all w/ rpc calls: 800ms to 1.2s
Subgraph only: ~200ms
shortened revalidation to 30 seconds if not found.
`/retirements/[index]`
Removed RPC fallback for subgraph. If no subgraph data exists, directs to a 404.
Changed revalidation times. If the subgraph data exists, revalidates every 24 hours. If no subgraph data, revalidates every second.
Resolves #1018
=> Tufnel/Retirements enhancements # 1018

.gitignore, carbonmark-api/README.md, carbonmark-api/src/app.ts, carbonmark-api/src/utils/helpers/utils.constants.ts, package-lock.json
Updated readme for updating to the newest vercel version, linking to the carbonmark-api vercel project, pulling the env variables, upgrading from previous version and running carbonmark-api locally in dev mode.
Updated path to the folder and variables created by the newest vercel cli.
Resolves #1338
=> Fix local api setup and README instructions

carbonmark-api/src/routes/users/get.ts
Add missing `wallet` attribute from the GET `/user` requests.
Previously this was added in the middle of the route:
It seems to have been lost during refactor. Tests for response content will be added in forthcoming PR 
Resolves #13557
=> fix:1357 User wallet added to /GET response

app/locale/en-pseudo/messages.po, carbonmark/components/pages/Project/Purchase/Listing/PurchaseInputs.tsx, carbonmark/components/pages/Project/Purchase/Pool/PurchaseInputs.tsx, carbonmark/components/pages/Project/Retire/Pool/RetireInputs.tsx, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po, site/locale/en-pseudo/messages.po
On the Retire & Buy screens for pool listings, looking to update and standardize the user help message:
Resolves #1314
=> 0xMakka / 1314 - change message text to match figma on buy/retire screens

carbonmark/components/pages/Users/ProfileHeader/index.tsx, carbonmark/components/pages/Users/SellerConnected/index.tsx, carbonmark/components/pages/Users/SellerUnconnected/index.tsx, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po
**Better empty state texts**
Viewing someones profile URL who is not yet registered:
"This user has not yet created a carbonmark profile."
Viewing owns profile URL and still not registered:
"Click the 'create profile' button to customize this page and get started."
Resolves https://github.com/KlimaDAO/klimadao/issues/1164
| Logged In  | Not Logged In  |
|<img width="1245" alt="Bildschirmfoto 2023-07-21 um 13 51 00" src="https://github.com/KlimaDAO/klimadao/assets/95881624/4a081457-a5ab-4044-8ea2-1b6b44c8a5ce"> |<img width="1249" alt="Bildschirmfoto 2023-07-21 um 13 51 17" src="https://github.com/KlimaDAO/klimadao/assets/95881624/e2d8ced2-8a5f-45b6-9377-6676640b5384">|
=> Improve empty state for unconnected users

carbonmark-api/src/routes/projects/get.ts
Following a pickup by @psparacino the `/projects` endpoint was no longer removing duplicates..
This PR adds this functionality at the API level.
=> Remove duplicates from GET /projects

carbonmark-api/src/.generated/types/marketplace.types.ts, carbonmark-api/src/.generated/types/offsets.types.ts, carbonmark-api/src/graphql/codegen.ts, carbonmark-api/src/graphql/marketplace.gql, carbonmark-api/src/graphql/offsets.gql, carbonmark-api/src/routes/projects/projects.utils.ts, carbonmark-api/src/utils/helpers/utils.ts
Some countries were being missed when fetching all countries for each project. This is because the default response limit seems to be 100 and "Belize" was in the 100nth+ project.
Resolves #1372 
This is a temporary fix, this error could arise again until the gql resolver is updated to allow null values for searches on `findProjects` query.
See related ticket: https://github.com/KlimaDAO/klimadao/issues/1401
=> Add limit:1000 to all country, category, vintage queries

site/components/pages/Resources/lib/queries.ts, site/lib/queries.ts
1. Updated locale filters to fetch where locale === undefined || locale === "en" || locale === $locale
2. Updated ordering to include locale === $locale. When locale articles run out, then the "en" documents will fill in.
3. Changed the [0...20] slice to after ordering. Otherwise the first arbitrary 20 articles were selected  instead of the locale documents.
4. Updated filtering A-Z and newest/oldest filters in frontend to include locale === $locale. I did not modify the search by text function as that will be language specific anyway.
Resolves #1144 
**When this merged, #1373 can be closed as this proposed an alternate solution to this issue.**
=> Updated locale groq queries for resources

carbonmark/components/pages/Project/Purchase/Pool/PurchaseForm.tsx, carbonmark/components/pages/Project/Purchase/styles.ts
This PR makes the side panel for pool listings sticky on scroll.
fixes #1352
=> make more sidebars sticky

.github/workflows/check_formatting.yml
Runs prettier checks as separate GitHub Action workflow
Only checks files that have been modified (relative to staging for non-staging branches, relative to main for staging)
Resolves #1438
=> Add separate prettier checks

carbonmark/components/pages/Project/Retire/Pool/RetireForm.tsx, carbonmark/components/pages/Project/Retire/Pool/SuccessScreen.tsx, carbonmark/components/pages/Projects/ProjectView/GridView.tsx
We were using the wallet address of the current user for receipt URLs before. This PR makes it so that we use the beneficiary address if it is provided in the retirement form.
Resolves #1370
=> fix receipt urls for when retiring on behalf

carbonmark-api/package.json, carbonmark-api/postman_collection.json, carbonmark-api/postman_tests.sh, carbonmark-api/src/app.ts, carbonmark-api/src/plugins/open-api.ts, carbonmark-api/src/routes/openapi.ts, carbonmark-api/src/routes/root.ts, carbonmark-api/test/regression.test.ts, carbonmark-api/test/test.constants.ts, carbonmark-data/.env.example, carbonmark/lib/constants.ts, examples/nextjs-typescript-integration/utils/fetchProjectInfo.ts
- Removes the `/api` prefix for all routes
- moves extra routes out of `app.ts`
=> chore: Remove /api prefix from api

carbonmark/components/Dropdown/index.tsx, carbonmark/components/Dropdown/styles.ts, carbonmark/components/pages/Resources/ResourcesList/index.tsx, carbonmark/components/pages/Resources/ResourcesList/styles.ts
- Align resources search input field styles to the marketplace input field styles
- Fix dropdown box alignment with parent element (marketplace sort by filters)
- Also bumps font size
Resolves #1403 
|![image](https://github.com/KlimaDAO/klimadao/assets/97446324/b26e0467-8e1a-450e-8957-103347e14a38)|![image](https://github.com/KlimaDAO/klimadao/assets/97446324/ca93f758-59d4-4625-a713-6ab982379f78)|
|![image](https://github.com/KlimaDAO/klimadao/assets/97446324/647affe9-2fff-48ac-b380-f335f380cc67)|![image](https://github.com/KlimaDAO/klimadao/assets/97446324/639a687c-4293-410e-b8da-239a8016b992)|
=> fix: align search input field styles

carbonmark/components/pages/Resources/SortyByDropDown/index.tsx, carbonmark/components/pages/Resources/SortyByDropDown/styles.ts
Realign resources sort dropdown styling to match intended design. 
Fixes:
- Removes black background around dropdown content
- Bumps the font size to match page
Half of #1403 
| ![image](https://github.com/KlimaDAO/klimadao/assets/97446324/3738d194-1a49-4f4f-80fb-9bbce061e401) |![image](https://github.com/KlimaDAO/klimadao/assets/97446324/fd98f083-746b-492f-8e0f-c353817bd1be) |
=> fix: resource sort by tippy dropdown styling

carbonmark/lib/types/carbonmark.guard.ts
Frontend regression; type guard was checking the wrong properties causing Listing cards to be rendered instead of PoolPrice cards
=> hotfix: correct isTokenPrice guard

carbonmark/components/pages/Project/Retire/Pool/CreditCardModal.tsx, carbonmark/components/pages/Project/Retire/Pool/RetireForm.tsx, carbonmark/components/pages/Project/Retire/Pool/RetireInputs.tsx, carbonmark/components/pages/Project/Retire/Pool/TotalValues.tsx, carbonmark/lib/fiat/fiatInfo.ts, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po
**NOTE: this PR is dependent on the fiat api PR merge.**
Handles the MinPurchaseRequired error from the api.
If retirement amount is below the minimum purchase required, the modal informs the user and only gives the option to go back. It also clears the quantity in the retire inputs so that they are forced to enter in another number, as the Retire Carbon button will be disabled until they do.
**NOTE: until the fix on the fiat repo is merged there will still be quote error on the one ton. This error is due to slippage being rounded off inexpensive tons.**
Resolves #1536 
|
|<img width="737" alt="Screen Shot 2023-09-14 at 1 09 30 PM" src="https://github.com/KlimaDAO/klimadao/assets/72105234/fc0ba616-2c9a-4fd6-a8ca-d3082e2c7364">|
=> handles MinPurchaseRequired Error

carbonmark/components/pages/Retire/Activity/Table.tsx
Format quantity value with decimals. Requirements are as follows:
- If < 1 tonne, show up to 3 decimals 
- If > 1 tonne, show up to 2 decimals
Resolves #1434
=> Makka / #1434 format qty value with decimals

carbonmark-api/package.json, package-lock.json
`npm version premajor`
Prerelease because it does not support mainnet Carbonmark data
=> [api] premajor release v2.0.0-0

carbonmark-data/components/pages/offVsOnChain/OffVsOnChainClientWrapper/index.tsx, carbonmark-data/components/pages/offVsOnChain/OffVsOnChainClientWrapper/styles.module.scss
This PR centers the segmented button on the off-vs-on chain carbon page
=> fix button layout on off-vs-on page

carbonmark/components/pages/Project/Retire/Pool/RetireForm.tsx
`paymentMethod` on Retire Form was recently changed to `usdc`; should be `fiat`.
=> Fixed incorrect payment method on CC checkout

carbonmark/components/pages/Users/SellerConnected/Forms/EditProfile.tsx, carbonmark/lib/constants.ts, carbonmark/pages/users/[user].tsx
The user page generation created an infinite redirect loop if the user did not have a handle, because it kept redirecting to `/users/undefined`
This was hard to debug because the getStaticProps logic is difficult to reason with & page requirements were not clear.
So I refactored the whole handler to be a bit more verbose, but much more explicit about the requirements, and easier to follow the happy/sad paths.
Resolves #1617
=> fix #1617 - refactor User page handler

carbonmark-data/app/[locale]/overview/page.tsx, carbonmark-data/components/ChangeLanguageButton/index.tsx, carbonmark-data/components/ChangeLanguageButton/styles.module.scss, carbonmark-data/components/cards/ChartCard/index.tsx, carbonmark-data/components/cards/ChartCard/styles.module.scss, carbonmark-data/components/cards/offVsOnChain/VerraCreditsBreakdownCard/issuedvsRetiredCreditsChart.tsx, carbonmark-data/components/charts/helpers/KAreaChart/index.tsx, carbonmark-data/components/charts/helpers/KBarChart/index.tsx, carbonmark-data/components/charts/helpers/KLineChart/index.tsx, carbonmark-data/components/charts/helpers/KPieChart/index.tsx, carbonmark-data/components/charts/helpers/KlimaAxis.tsx, carbonmark-data/components/charts/helpers/props.ts, carbonmark-data/lib/charts/helpers.ts
Small UI Fixes:
- Enforce US format for prices
- Fixes ticks for XAxes representing months (No ticket)
- Adds proper behaviours for language button
- Fix bottom options position on small cards
Should be reviewed after https://github.com/KlimaDAO/klimadao/pull/1583 is merged
Resolves #1504
Resolves #1467 
Resolves #1521  
=> Carbonmark values format fixes

carbonmark-api/src/.generated/types/marketplace.types.ts, carbonmark-api/src/graphql/marketplace.fragments.gql, carbonmark-api/src/models/Listing.model.ts, carbonmark-api/src/routes/projects/get.utils.ts, carbonmark-api/src/routes/users/get.ts, carbonmark-api/src/routes/users/get.utils.ts, carbonmark-api/src/utils/helpers/fetchMarketplaceListings.ts, carbonmark-api/src/utils/marketplace.utils.ts, carbonmark-api/test/fixtures/marketplace.ts, carbonmark-api/test/routes/projects/get.test.ts
Brings back the marketplace project query as a temporary workaround, passes this data down to the listing.project entity. Changes affect /projects, /projects/:id, and /users/:id
Eliminates more bignumber strings from API responses.
Creates a shared formatting util for formatting Listings.
=> [api] include project data in Listings model

carbonmark-api/package.json, carbonmark-api/src/routes/users/get.ts, package-lock.json
Until we have a mainnet graph
Increment to v2.0.0-5
No ticket, I just noticed this.
=> [api] hide mumbai listings from /users endpoint (temp fix)

carbonmark/.generated/carbonmark-api.schema.ts, carbonmark/components/CreateListing/Form/index.tsx, carbonmark/components/CreateListing/index.tsx, carbonmark/components/CreateListing/styles.ts, carbonmark/components/Transaction/index.tsx, carbonmark/components/pages/Portfolio/AssetProject/index.tsx, carbonmark/components/pages/Purchases/index.tsx, carbonmark/components/pages/Users/Listing/index.tsx, carbonmark/components/pages/Users/SellerConnected/Forms/EditListing.tsx, carbonmark/components/pages/Users/SellerConnected/ListingEditable.tsx, carbonmark/components/pages/Users/SellerConnected/index.tsx, carbonmark/components/pages/Users/SellerUnconnected/index.tsx, carbonmark/lib/actions.ts, carbonmark/lib/constants.ts, carbonmark/lib/formatNumbers.ts, carbonmark/lib/getFeatureFlag.ts
- Add featureFlags to app config object
- Add createListing as a feature flag, disabled on production
- The Create Listing buttons on /portfolio and /user pages both respect the feature flag.
- Fix createListing plumbing in the frontend to support testnet and use the new ABI. I successfully created a testnet listing from my portfolio 🚀 🎉 
- Change some variable names in CreateListing modal to match those defined in the Carbonmark v2 ABI.json spec
- Update modal text to be more concise.
- Remove "price" from the "approve" step because price has nothing to do with approval.
Part of #1494
=> [carbonmark] Enable create listing buttons

carbonmark-api/src/plugins/open-api.ts
The open api spec can return a "servers" attribute that specifies the available urls for the api. This can be necessary for code generation
=> servers attribute on open-api response

carbonmark-api/src/routes/users/get.utils.ts
Fix #1663
For the hardcoded testnet assets that we track, don't show them if the balance is zero
=> fix #1663 don't show zero balance testnet tokens

carbonmark/components/pages/Users/SellerConnected/index.tsx, carbonmark/lib/utils/listings.utils.ts
Fix #1661 
It was actually fixed in a different PR but this disables the button unless listable assets are present to prevent this from recurring.
=> fix(profile): disable create new listing button if no listable assets

carbonmark/components/pages/Users/SellerConnected/Forms/EditProfile.tsx, carbonmark/lib/api/client.ts
`fetchIsNewHandle` was using the error message returned rather than the error status. 
* Added FetchError
*Check for error status 404 instead of string compare
=> fetchIsNewHandle to use response status instead of error message

carbon/app/[locale]/details/price-of-digital-carbon/page.tsx, carbon/components/cards/overview/TokensPriceCard/index.tsx, carbon/components/cards/overview/TokensPriceCard/styles.module.scss, carbon/lib/tokens.tsx
- Rename selective fee into selective cost
- Render selective cost tooltip using material UI
Resolves #1700
|![image](https://github.com/KlimaDAO/klimadao/assets/11857992/d342d194-162c-448a-82eb-6955315e35d9)|![image](https://github.com/KlimaDAO/klimadao/assets/11857992/a6aacec7-2439-41b2-8fe1-ae86ce0ad7d9)|
=> Carbon: Improve selective fee presentation

carbonmark/components/Activities/Activity.tsx
This PR removes the amounts from activities if they describe deletion events.
Resolves #1671
=> improve activity info for deletions

carbonmark/components/pages/Retire/FromPortfolio/styles.ts, carbonmark/components/pages/Retire/styles.ts
Fixes alignment issues on mobile for /retire screen based on [figma](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?node-id=672%3A7165&mode=dev) file
Resolves #1692
=> Makka / 1692 add alignment fixes for mobile on retire screen

carbon/components/PageHeader/styles.module.scss
This PR makes the "What is digital carbon?" link blue.
Resolves #1699
=> carbon: fix what is digital carbon link color

carbon/components/cards/overview/TokenizedCreditsByBridgeCard/index.tsx
This PR moves the detail link for the tokenized credits pie chart up like with the other cards
Resolves #1701
=> carbon: move detail link up for pie chart

carbonmark/components/CreateListing/index.tsx, carbonmark/components/pages/Users/SellerConnected/ListingEditable.tsx, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po
Add the following text in bold to the create listing modal
> The Confirm amount below reflects the sum of all your listings for this specific token.
Resolves #1711
=> Makka / 1711 add confirm text to create listing modal

carbonmark-api/src/.generated/types/marketplace.types.ts, carbonmark-api/src/graphql/marketplace.gql, carbonmark-api/src/routes/users/get.utils.ts, carbonmark/lib/api.ts
Addresses missing activities and redundancy. Purchases by Atmos now up on Shimon's activities.
Resolves #1680 #1682
=> revised query for listings and activities

.github/workflows/release_carbonmark_api.yml
Removes the test branch from the `release_crabonmark_api` workflow
=> Remove test branch from api release workflow

carbonmark/components/pages/Projects/GridView/GridView.tsx, carbonmark/components/pages/Projects/ListView/ListView.tsx, carbonmark/components/pages/Projects/MapView/LazyLoadingMapView.tsx, carbonmark/components/pages/Projects/MapView/MapView.tsx, carbonmark/components/pages/Projects/MapView/carbonmark-map.ts, carbonmark/components/pages/Projects/index.tsx, carbonmark/components/pages/Projects/props.ts
Lazy loading of projects page map view
Resolves #1636 
|/projects                                                 300 kB          693 kB |/projects                                                 22 kB           419 kB|
=> Lazy loading of projects page map view

carbon/components/cards/overview/TokensPriceCard/index.tsx, carbon/components/charts/helpers/CoinTiles/index.tsx, carbon/components/charts/helpers/CoinTiles/styles.module.scss
Makes Digital carbon pricing card respect design on larger screens
Resolves #1730
|![image](https://github.com/KlimaDAO/klimadao/assets/11857992/8331bd63-d7f1-4c52-8a40-307300ea77a0) |![image](https://github.com/KlimaDAO/klimadao/assets/11857992/10861794-edb8-49c1-a50c-57b18228789c)|
-->
=> [klima data] Makes Digital carbon pricing card respect design on larger screens

carbon/components/cards/supply/CarbonSupplyQuickFactsCard/index.tsx, carbon/components/cards/supply/CarbonSupplyQuickFactsCard/styles.module.scss
Better scale fonts for digital carbon supply detail page
Resolves #1745 
|![image](https://github.com/KlimaDAO/klimadao/assets/11857992/37909c5d-335a-4877-b08a-b6b8a7353ef3) |![image](https://github.com/KlimaDAO/klimadao/assets/11857992/85892f43-e915-4e24-8b99-591965a11364)|
=> [klima data] carbon: Better scale fonts for digital carbon supply detail page

carbon/components/charts/helpers/DataTable/DataTableClientWrapper/index.tsx, carbon/components/charts/helpers/DataTable/configurations/TokenOriginsListConfiguration.tsx
Fixes origin of credits card
- Properly name country code column
- Makes the table reactive to the selection widgets
Resolves #1760
=> [carbon] Fixes origin of credits card

carbonmark-api/src/.generated/types/marketplace.types.ts, carbonmark-api/src/graphql/marketplace.gql, carbonmark/.generated/carbonmark-api.schema.ts, carbonmark/components/CreateListing/index.tsx, carbonmark/components/pages/Users/SellerConnected/ListingEditable.tsx, carbonmark/lib/constants.ts, carbonmark/lib/listingsGetter.ts, carbonmark/lib/utils/listings.utils.ts
Converting a decimal with .toString() was creating strings with exponent syntax `1.12e10`which would cause the ethers parseUnits to fail.
Now we do all the math with strings and convert to number at the end.
Also snuck in a change to the gql query to not return deleted listings related to #1750
=> [carbonmark] fix safemath

carbonmark/.generated/carbonmark-api.schema.ts, carbonmark/lib/constants.ts
Builds are broken because a prior subgraph URL expired (see #1652 )
=> [carbonmark] Upgrade to v2.0.0-12

carbon/components/pages/PageWithTabs/index.tsx, carbon/components/pages/PageWithTabs/styles.module.scss, carbon/theme/layout.module.scss
This PR fixes the top padding on tabbed pages as well as tweaking the padding between the cards to match the figma design.
Resolves #1746 
Resolves #1758
=> fix paddings and spacings

carbon/components/ChangeLanguageButton/styles.module.scss
This PR fixes the background color of the language menu button on mobile.
Resolves #1767
=> fix button background on mobile

carbon/components/MobileTabSelector/index.tsx, carbon/components/MobileTabSelector/styles.module.scss
This PR fixes the background color as well as the arrow icon for the mobile tab selector.
Resolves #1765
=> fix select & arrow design

carbon/components/OptionsSwitcher/index.tsx, carbon/components/pages/offVsOnChain/OffVsOnChainClientWrapper/styles.module.scss
This PR force-centers the issued/retired switch on screen.
Resolves #1734
=> center switch on screen

carbon/components/cards/ChartCard/index.tsx, carbon/components/cards/ChartCard/styles.module.scss
Enables card titles to wrap on mobile devices
Resolves #1798
=> carbon: enable card titles to wrap on mobile

carbon/components/Layout/styles.module.scss
The change language button background color was wrong on desktop layouts since it was changed to appear on the mobile header. This PR makes uses the figma colors on both layouts.
=> fix desktop colors for header buttons

carbon/components/MobileTabSelector/index.tsx, carbon/components/MobileTabSelector/styles.module.scss, carbon/components/pages/PageWithTabs/index.tsx, carbon/components/pages/PageWithTabs/styles.module.scss
This PR makes the mobile tab selector as well as the chart options sticky.
Resolves #1763
=> carbon: make tabs and options sticky on mobile

carbon/components/charts/helpers/KAreaChart/index.tsx, carbon/components/charts/helpers/KBarChart/index.tsx, carbon/components/charts/helpers/KLineChart/index.tsx, carbon/components/charts/helpers/styles.module.scss
This PR centers the chart legends on mobile screens for:
* Line charts
* Bar charts
* Area charts 
Resolves #1766
=> center chart legend on mobile

carbon/app/[locale]/off-chain-vs-on-chain/page.tsx, carbon/app/[locale]/off-chain-vs-on-chain/styles.module.scss, carbon/app/[locale]/off-chain-vs-on-chain/verra-credits-breakdown/page.tsx, carbon/components/Layout/styles.module.scss, carbon/components/cards/ChartCard/index.tsx, carbon/components/cards/ChartCard/styles.module.scss, carbon/components/cards/offVsOnChain/VerraCreditsBreakdownCard/index.tsx, carbon/components/cards/offVsOnChain/VerraCreditsBreakdownCard/styles.module.scss, carbon/components/pages/PageWithTabs/index.tsx, carbon/components/pages/PageWithTabs/styles.module.scss, carbon/theme/layout.module.scss
fix Verra credits breakdown cards css
Resolves #1841
=> [klima data] fix Verra credits breakdown cards css

carbon/components/Layout/Footer/index.tsx, carbon/components/Layout/MobileMenuButton/index.tsx, carbon/components/Layout/NavItems/index.tsx, carbon/components/PercentageChange/index.tsx, carbon/components/cards/overview/TokensPriceCard/index.tsx, carbon/components/charts/helpers/DataTable/Pagination/index.tsx, carbon/components/charts/helpers/DataTable/VerticalTableHeader/index.tsx, carbon/components/charts/helpers/TableLink/index.tsx, carbonmark/components/CopyAddressButton/index.tsx, carbonmark/components/Stats/StatsBar.tsx, carbonmark/components/ViewWalletButton/index.tsx, carbonmark/components/pages/Portfolio/Retire/RetirementStatusModal/index.tsx, carbonmark/components/pages/Projects/ProjectFilters/index.tsx, carbonmark/components/pages/Projects/ProjectsController/index.tsx, carbonmark/components/pages/Users/Badge/index.tsx, lib/components/CopyValueButton/index.tsx
This PR updates all imports for material icons so that only the components are imported.
Resolves #1381
=> update icon imports

carbon/app/[locale]/globals.css, carbon/components/PageHeader/styles.module.scss
This PR updates the style of the "Explore Marketplace" button to look like this:
Resolves #1875
=> carbon: update font and border-radius of cta button

lib/components/CopyValueButton/index.tsx
Material UI icon imports are breaking inside the `lib` folder. I've reverted these as currently `app` and `carbonmark` are breaking when using the `CopyValueButton` component. 
They were changed in the following PR so adding @sprrwhwk for context - https://github.com/KlimaDAO/klimadao/pull/1851/files#diff-507100aff726f7ba477b1c5b048c00bf862de1f1da681c3a04b9c1e01c7207d8
I haven't pinned down what the exact issue is, but it seems like they get imported as an object inside `lib` and not exported correctly. Opening this PR to revert and provide a quick fix to `carbonmark` and `app` until I can pinpoint what is causing the issue.
Related issue on material-ui github - 
- https://github.com/mui/material-ui/issues/35233
Resolves #1862
=> Makka / 1862 revert icon imports in lib

lib/components/Web3Context/index.tsx, lib/utils/useProvider/index.tsx
@Atmosfearful There has been reports of wallet connect issues. I ran into this issue myself and done some investigation. It looks on first login with wallet connect, everything works as expected, but if the user reloads, the `walletConnectProjectId` never gets passed along to the connect function. 
It needs to be passed into the useProvider hook as I tried passing it into `Web3Context.Provider` as a value, but because the useProvider hook is called first, the value never gets passed along. 
=> Makka / address issue with wallet connect loading

carbonmark/components/pages/Portfolio/AssetProject/index.tsx, carbonmark/components/pages/Portfolio/AssetProject/styles.ts, carbonmark/components/pages/Portfolio/Retire/RetireForm/index.tsx, carbonmark/components/pages/Portfolio/Retire/index.tsx, carbonmark/lib/actions.ts, carbonmark/lib/formatNumbers.ts, carbonmark/lib/types/carbonmark.types.ts, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po
Prevents users from being able to retire already listed tonnes, using the unlistedBalance util.
Resolves #1791
=> Makka / 1791 prevent users from retiring listed tonnes

carbon/components/ExploreMarketplaceButton/index.tsx, carbon/components/ExploreMarketplaceButton/styles.module.scss, carbon/components/Layout/MobileMenuButton/index.tsx, carbon/components/Layout/MobileMenuButton/styles.module.scss, carbon/components/PageHeader/PageHeader.tsx, carbon/components/PageHeader/styles.module.scss
This PR adds the "Explore Marketplace" button to the mobile menu.
Resolves #1896
=> carbon: add explore button to mobile menu

carbon/lib/tokens.tsx
Currently the selective fee amount is represented in decimal form (2.25% = 0.0225).
Adjust for this before creating the display text on the pricing sidebar.
Current:
Preview:
=> Carbon Dashboard - Adjust display text for percentage as a decimal

carbon/components/Layout/Footer/index.tsx
This PR adds footer links for KlimaDAO and Carbonmark. 
Resolves #1892
=> carbon: add carbonmark and klimadao footer links

carbon/lib/charts/helpers.ts
- Replace KT by k
- Replace MT by m
- Remove the space between value and unit
Resolves #1902
=> Rename units for tons

.github/CODEOWNERS
Sets @Atmosfearful @0xemc @0xMakka @biwano @psparacino @sprrwhwk as code owners of the carbonmark and carbonmark-api directories.
This will help us set automatic reviewers on PRs to hopefully keep them moving
=> chore: Set code owners

carbonmark/pages/retirements/[beneficiary]/[retirement_index].tsx
The FE is already equipped to handle a `null` project incl. mco2, somewhere a regression happened where we always fetch the project even if the subgraph didn't give us an id etc.
Closes #1927
=> fix #1927 only fetch project if id is present

carbonmark/components/pages/Users/SellerConnected/Forms/EditProfile.tsx, carbonmark/components/pages/Users/SellerConnected/index.tsx, carbonmark/components/pages/Users/SellerUnconnected/index.tsx
In some instances the `address` value from `useWeb3` was being used in place of the provided URL address param to determine if the useFetchUser hook should fire or not... Whoops..
The EditProfile modal is also secretly the "CreateProfile" modal. Removed the check for `isCarbonmarkUser` before opening this modal... Whoops again :(
Closes #1940
=> fix:1940 Use corrrect address for fetch check

carbonmark-api/src/.generated/types/digitalCarbon.types.ts, carbonmark-api/src/graphql/digitalCarbon.fragments.gql, carbonmark-api/src/graphql/digitalCarbon.gql, carbonmark-api/src/models/Project.model.ts, carbonmark-api/src/routes/projects/get.constants.ts, carbonmark-api/src/routes/projects/get.ts, carbonmark-api/src/routes/projects/get.utils.ts, carbonmark-api/src/utils/helpers/utils.ts, carbonmark-api/test/fixtures/digitalCarbon.ts, carbonmark-api/test/plugins/rate-limit.test.ts, carbonmark-api/test/routes/categories/get.test.ts, carbonmark-api/test/routes/countries/get.test.ts, carbonmark-api/test/routes/projects/[id]/get.test.ts, carbonmark-api/test/routes/projects/get.test.ts, carbonmark-api/test/routes/vintages/get.test.ts
Integrates the `digital-carbon` subgraph into `get.ts`, so the `/projects` endpoint uses the new subgraph.
One question [HERE](https://github.com/KlimaDAO/klimadao/compare/tufnel/digital-carbon-subgraph-in-fetchPoolPrices-1168...tufnel/integrate-digital-carbon-graph-into-get.ts?expand=1#diff-cc0d13d9fea158c1b9164a577fc190aaf13ee604e8eacf9e5e30e910f6a8890dR142). 
--> Should this compare the project token balance or the pool balance?
This replaces all the instances of the bridged-carbon subgraph that are used.
Update: This PR incorporates all the changes from #1543, so that can PR can almost definitely be closed
Resolves #1168
=> Tufnel/integrate digital carbon graph into get.ts

app/components/RebaseCard/index.tsx, app/components/views/Stake/index.tsx
Increased decimal places on AKR values to fix the issue of it rounding to 0
Resolves #1954
=> Add more decimals staking UI to solve AKR rounding to 0

carbonmark-api/src/utils/helpers/fetchProjectPoolInfo.ts
Fixes projects default pool detection
It seems this got broken during the migration to the `polygon-digital-carbon` graph
Closes #1964
- all projects pages
- https://www.carbonmark.com/fr/retire
Other notes:
-
=> Fix projects default pool detection

carbonmark/components/pages/Retirements/SingleRetirement/ProjectDetails/index.tsx, carbonmark/components/pages/Retirements/SingleRetirement/index.tsx, carbonmark/components/pages/Retirements/SingleRetirement/styles.ts, carbonmark/pages/retirements/[beneficiary]/[retirement_index].tsx, examples/nextjs-typescript-integration/utils/fetchGasPrices.ts, lib/constants/index.ts, lib/types/subgraph.ts, site/pages/retirements/[beneficiary]/[retirement_index].tsx
I was doing some demo testing and ran into a 404 after retirement. There is no ticket for this.
I take back my prior recommendations in #1018 -- this was dumb of me, we need fallbacks for API users. By fallbacks I mean, the page itself should handle cases where the data is on-chain but not yet indexed in the subgraph.
The code for fallbacks was already present, it just wasn't wired correctly.
With this pr:
- Only 404 when both subgraph AND on-chain data is not present for the given retirement
- If the on-chain data is present, return `null`, but render the page
- Show this updated message:
- /retirement/[beneficiary]/[index]
Creating a new retirement from anywhere in the ecosystem, then navigating to the retirement page URL immediately.
This is a hard one to test because the fallback is …
=> Retirement page fallback improvements

carbonmark/components/pages/Users/SellerConnected/Forms/EditListing.tsx, carbonmark/lib/actions.ts
Ethers throws an error when a user enters more than the maximum allowed decimals on the listing price. This PR limits the max decimals to 6 decimal places.
Resolves #1801
=> Makka / #1801 - set a max allowed decimals on edit listing price

carbonmark-api/src/routes/projects/get.ts, carbonmark/components/pages/Project/index.tsx, carbonmark/components/pages/Projects/index.tsx, carbonmark/components/pages/Users/index.tsx, carbonmark/lib/constants.ts
SSR fetched project and projects data were not being passed to SWR hook because of incorrect keys in the SWRConfig prop.
/Projects & /Project should render with initial data correctly now.
Closes #1967
Please confirm that project loading behaves as expected
`/projects` & `/projects/VCS-1190`
Other notes:
-
=> fix: use correct fetch keys for swr preloading

carbonmark/lib/constants.ts
Makes carbonmark use the version 2.0.2 of the API
Also related to #1966
- 
- 
Other notes:
-
=> Makes carbonmark use the version 2.0.2 of the API

carbonmark-api/src/routes/projects/get.ts, carbonmark-api/src/routes/projects/get.utils.ts, carbonmark/components/pages/Project/index.tsx, carbonmark/lib/types/carbonmark.guard.ts, package-lock.json
Because the API made an assumption of a one to one mapping of credits to projects (old technical debt)  only the first credit of any project was returning a project. This has been resolved by creating a new "Project" object per credit and adding it to the response.
Between v2.0.0 and v2.0.3 (the current version) the underlying subgraph has changed from 
https://api.thegraph.com/subgraphs/name/klimadao/polygon-bridged-carbon/
to
https://api.thegraph.com/subgraphs/name/klimadao/polygon-digital-carbon
The underlying data appears to be equivalent however the data structures are different with credits nested within projects. (@note we should really use the 'credits' graphql interface in the new subgraph)
v2.0.0.api.carbonmark.com ->  314
**this pr** ->  331
**Projects in V2.0.0 only**:  
[ …
=> fix: Resolve v2.0.0 and v2.0.3 api differences

carbonmark-api/package.json, carbonmark-api/src/routes/projects/[id]/get.ts, carbonmark-api/src/routes/projects/get.utils.ts
The Industrial Processing category was being returned as "Industrial Processing ". The additional space at the end of string caused it to fail when matching hardcoded categories.
I've sanitised categories with `trim` on the API side going forward.
https://github.com/KlimaDAO/klimadao/issues/1987#issuecomment-1847170247
=> fix:1987 trim Category strings in [id]/get and projects/get

carbonmark-api/package.json, package-lock.json
Because all tags and releases after 4.x were merged we need to revert the package.json version in carbonmark-api
=> Revert package.json version in carbonmark-api to v4.0.0

carbonmark/lib/waitForApi.ts, carbonmark/pages/index.tsx
Small quality of life PR.
This makes carbonmark FE wait for the preview API if it is configured to use it.
This prevents vercel builds to crash because queries fail.
NA
=> Wait for the API to come online on preview environments

app/components/views/Offset/index.tsx, carbonmark-api/postman_collection.json, lib/constants/index.ts
Adds a link to legacy app for carbon offsets
Closes #2035 
- https://klimadao-app-git-2035offsetpagelink-klimadao.vercel.app/#/offset
Other notes:
- I used the link to https://klimadao-3rkq7ymia-klimadao.vercel.app/#/offset instead of https://legacy-app.klimadao.finance/#/offsets because the offset page is not available on the latest.
- I hesitated to put a link that opens in another tab, LMK what you prefer.
=> Add link to legacy app for carbon offsets

carbonmark/components/pages/Project/Purchase/Pool/PurchaseForm.tsx, carbonmark/lib/actions.redeem.ts
Bad inputs. Unclear how this did not get noticed. I think an API regression meant we were never using pool default pricing, so this chunk of code was never accessed.
Expediting to get in morning release.
Closes #2043
=> Fix inputs for default retirements

.github/workflows/deploy_carbonmark_api.yml
Updates the deploy action that confirms that the "Version" in `carbonmark-api` is incremented whenever changes are made to the project (in order to create a release)
=> chore: GH Action to ensure that versions are incremented when carbonmark-api is modified

carbonmark/components/Transaction/Approve.tsx
Closes #2058 
See ticket, USDC icon should only appear when approving/paying USDC
Icon should not appear when retiring own carbon or creating a listing
This only touches the icon in the Approval view of the Transaction modal, which appears in 4 places:
- Purchase from listing
- Purchase from pool
- Retire Now from pool
- Retire Now from portfolio
Other checkout flows use a different modal.
=> Hide USDC icon for carbon approvals

carbon-projects/README.md, carbon-projects/schemas/externalFile.ts, carbon-projects/schemas/index.ts, carbon-projects/schemas/objects/externalFile.ts, carbon-projects/schemas/project.ts
Supports additional registries (including ICR) in the CMS, plus adds subcategories for projects and methodology links
Should not have any breaking impact on the frontend's API as only new fields were added (existing fields untouched)
=> Rejigger CMS entities to support ICR projects and add subcategories and methodology links

carbonmark-api/package.json, carbonmark-api/src/.generated/types/digitalCarbon.types.ts, carbonmark-api/src/app.constants.ts, carbonmark-api/src/graphql/digitalCarbon.gql, package-lock.json
Filters credits on currentsupply > 0 and exAnte=false  for polygon-digital-carbon subgraph for vintage discovery
See https://discord.com/channels/1135827610434289727/1135829064465264650/1196817534675066950
I could add these filters to the projects filters queries but I prefered to be cautious.
Also related to #2129 
-
=> Fix Filters credits for vintage discovery for polygon-digital-carbon subgraph

app/locale/en-pseudo/messages.po, app/locale/en/messages.po, carbon/locale/en-pseudo/messages.po, carbon/locale/en/messages.po, carbonmark/components/FeatureBanner/index.tsx, carbonmark/components/FeatureBanner/styles.ts, carbonmark/components/Layout/index.tsx, carbonmark/components/Layout/styles.ts, carbonmark/components/pages/Projects/Banners/BankTransfer.tsx, carbonmark/components/pages/Projects/index.tsx, carbonmark/components/pages/Projects/styles.ts, carbonmark/lib/constants.ts, carbonmark/locale/en-pseudo/messages.po, carbonmark/locale/en/messages.po, site/locale/en-pseudo/messages.po, site/locale/en/messages.po
This PR introduces a new feature banner which should only be visible on the marketplace homepage - `/projects`. The main functionality is described in the main #1993 ticket.
Closes #1993 
- QA should test that the banner matches the figma designs
- QA should test that clicking "Let's Go" brings the user to the retire via bank transfer form.
- QA should test that clicking on "Learn More" brings the user to the following blog [post](https://carbonmark-git-makka-1993-new-feature-banner-klimadao.vercel.app/blog/carbonmark-now-accepts-bank-transfer-as-a-payment-method)
- QA should test that clicking on the close (x) button should show the updated banner i.e. the banner containing the text and two buttons - "Sure" and "Don't Remind Me".
- QA should test that when clicking "Sure" the banner …
=> Makka / #1993 new feature banner for bank transfer feature

carbonmark/.generated/carbonmark-api-sdk/clients/getListingsId.ts, carbonmark/.generated/carbonmark-api-sdk/clients/getPurchases.ts, carbonmark/.generated/carbonmark-api-sdk/clients/index.ts, carbonmark/.generated/carbonmark-api-sdk/clients/operations.ts, carbonmark/.generated/carbonmark-api-sdk/hooks/index.ts, carbonmark/.generated/carbonmark-api-sdk/hooks/useGetListingsId.ts, carbonmark/.generated/carbonmark-api-sdk/hooks/useGetPurchases.ts, carbonmark/.generated/carbonmark-api-sdk/schemas/Listing.json, carbonmark/.generated/carbonmark-api-sdk/schemas/Project.json, carbonmark/.generated/carbonmark-api-sdk/schemas/User.json, carbonmark/.generated/carbonmark-api-sdk/types/GetListingsId.ts, carbonmark/.generated/carbonmark-api-sdk/types/GetProjects.ts, carbonmark/.generated/carbonmark-api-sdk/types/GetProjectsId.ts, carbonmark/.generated/carbonmark-api-sdk/types/GetPurchases.ts, carbonmark/.generated/carbonmark-api-sdk/types/GetUsersWalletorhandle.ts, carbonmark/.generated/carbonmark-api-sdk/types/Project.ts, carbonmark/.generated/carbonmark-api-sdk/types/User.ts, carbonmark/.generated/carbonmark-api-sdk/types/index.ts, carbonmark/.generated/carbonmark-api.schema.json, carbonmark/lib/constants.ts
Makes the carbonmark use API version 5.2.1
Partialy solves
#2129
- Search the marketplace for projects by vintage
- https://carbonmark-git-biwano-carbonmarkuseapi521-klimadao.vercel.app/fr/projects?layout=grid&sort=recently-updated
=> Make the carbonmark use API version 5.2.1

carbonmark-api/package.json, carbonmark-api/src/.generated/types/cms.types.ts, carbonmark-api/src/graphql/cms.fragments.gql, carbonmark-api/src/routes/projects/get.utils.ts
Project media can appear in two different sources from the cms. 
In order of preference, from `images` on the allProject query. 
The second option is from `externalMedia` on allProjectContent. This PR fetches from both in that order of preference. 
**This PR also filters out any youtube or video links as CM does currently not support them.**
ICR project page with images:
- Individual project pages
=> [api] Support both images and externalMedia media from cms projects

.github/workflows/release_carbonmark_api.yml, .vscode/settings.json
There is a `staging` tag being created sporadically which is causing conflicts when git is looking up the `staging` branch.
I believe it is being cause by teh `deploy-carbonmark-api.yml` workflow.
Possible explanation:
1. introduced the ability to create releases by incrementing package.json version
2. the release action was setup assuming that it was always triggered by creation of a tag
3. it was using ${{ github.ref }} to identify the tag, which in the case of changing the package.json it was just staging
This PR uses the RELEASE_VERSION rather than github.ref
Last PR that created a `staging` tag: https://github.com/KlimaDAO/klimadao/actions/runs/7612748363/job/20731019927
=> Explicitly set the tag on creation of a release

carbonmark-api/package.json, carbonmark-api/src/.generated/types/icr.types.ts, carbonmark-api/src/graphql/icr.gql, carbonmark-api/src/models/Project.model.ts, carbonmark-api/src/models/Purchase.model.ts
In the original version of the ICR integration, ICR's project credit`serialization` was the only reliable way to query the ICR api for a specific project.
After the refactor to use the cms for project data, the serialization is only needed to create the `registry-registryProjectID` format to identify the project when querying the ICR subgraph for ICR holdings. The serialization can be removed everywhere else.
In the app, besides generated files, the serialization only exists as a prop in carbonmark/lib/createUrls and will be deleted there for the APP PR for this api version. 
The end goal is not to use the serialization anywhere in the CM codebase. Once we can query ICR holdings from a CM subgraph this last requirement can be removed.
related to …
=> [api] Remove ICR artifacts 

carbonmark-api/package.json, carbonmark-api/src/utils/helpers/listings.utils.ts
Fixes listings endpoint for ICR listings.
The core issue is that the listings endpoint queried the `digital-carbon` subgraph for the token symbol on `Token` entity. Currently no ICR tokens are listed in the subgraph as `Tokens`. Ideally, unless ICR token don't qualify as `Tokens`, these should be added so there is no conditional logic in the endpoint.
Closes #2177
https://carbonmark-api-git-fix-listings-endpoint-fetche-c1b9ef-klimadao.vercel.app/listings/0xe2d23df10da8679d3a0af644a4778d66c7d78c5c9c1540805ae1b3c6bf208e09
=> [api] Fix `listings` endpoint for ICR

carbonmark-api/package.json, package-lock.json
Release version 5.3.6 of the API. This is because my last update went through without a PR and did not trigger a release
- 
- 
Other notes:
-
=> API release 5.3.6

carbonmark-api/package.json, carbonmark-api/src/routes/projects/get.constants.ts, carbonmark/lib/api/client.ts, package-lock.json
- Changes NBO default pool project in the API
- Also adds logging on fetch errors to troubleshoot Vercel deployment issues
Related to #2091 
Related to #2224
1.  curl https://carbonmark-api-git-biwano-fix2091apipoolproject-klimadao.vercel.app/projects/VCS-875-2015
2. Check isPoolDefault is true for nbo
=> Fix NBO default pool project in the API

carbonmark-api/package.json, carbonmark-api/src/app.constants.ts, carbonmark-api/src/routes/purchases/get.utils.ts, carbonmark-api/src/routes/users/[walletOrHandle]/get.ts, carbonmark-api/src/utils/helpers/activities.utils.ts, carbonmark-api/src/utils/marketplace.utils.ts, carbonmark-api/test/fixtures/marketplace.ts, carbonmark-api/test/routes/projects/[id]/get.test.ts, carbonmark-api/test/routes/projects/get.test.mocks.ts
Clean up from the ICR integration: 
ICR handles their quantities in regular integers (0 decimals). This was handled in the previous integration by ternaries where applicable. This PR uses a util function for that purpose instead to increase maintainability (ICR is considering going to the standard 18 decimals).
Addresses one half of this issue. The FE needs this cleanup as well: [2136](https://github.com/KlimaDAO/klimadao/issues/2136)
1.  Any buy/sell/retirement quotes
2. `purchases/`
3. `activities/`
There should be no change in behavior from the current staging; this clean-up refactoring only
=> [api] Standardize quantity/amount handling

carbonmark/components/CreateListing/Transaction/Approve.tsx, carbonmark/components/CreateListing/Transaction/index.tsx, carbonmark/components/CreateListing/index.tsx, carbonmark/components/pages/Users/SellerConnected/ListingEditable.tsx
Approvals for 1155 tokens work on an all-or-nothing basis, all tokens and balances or none.  The copy for approvals now reflects this. It does not show for ERC20 approvals.
Closes #1989 
Create a listing with an ICR credit
The previous copy was actually incorrect. It's not the sum of your ICR credit listings, it's the max allowance for all tokens.
=> Conditional Copy for 1155 Approvals

carbonmark/components/pages/Retirements/RetirementProvenance/RetirementCard/index.tsx
Noticed while working on another issue, the profile logo was placed inside a `<Text>` component which caused a hydration error
=> Fix/Hydration Error with Profile Logo

carbonmark/lib/actions.ts
The updateListing function was parsing the default min fill amount (1) for every update. This is correct for ERC20s but incorrect for ICR credits. 
This issue has now been addressed on the contract level as well and breaking minFillAmounts (if a min fill is > than the actual amount) will revert.  To correct this issue on the frontend so that the correct params are passed the default min fill needs to be adjusted for different decimal amounts.
The next iteration will format these amounts by registry similar to #2237 for the api versus using ternaries.
1. Update an ICR credit listing with either a price or quantity change
2. The update transaction should successfully update without any contract errors or reverts
=> [ICR listing] Fix update listing minFillAmount for different decimals

carbonmark/components/pages/Retirements/RetirementProvenance/ProvenanceComponent/index.tsx, carbonmark/components/pages/Retirements/RetirementProvenance/ProvenanceTimeline/styles.ts, carbonmark/components/pages/Retirements/RetirementProvenance/index.tsx, carbonmark/components/pages/Retirements/RetirementProvenance/styles.ts, carbonmark/components/pages/Retirements/SingleRetirement/index.tsx, carbonmark/components/pages/Retirements/SingleRetirement/styles.ts, carbonmark/components/pages/Retirements/index.tsx, carbonmark/components/pages/Retirements/styles.ts
`GridContainer` is used for the page layouts and after the recent navigation changes, the page layout has changed. Grid container by default is setting `display: grid`, in this instance using `display: unset` resolves the page issues. 
Note: I'd like to relook at these pages that use GridContainer in a follow up ticket and see can they now be replaced with the `Container` component from material-ui. I've briefly checked if it works, it does apart from the footer needs some work to  span the full screen.
Closes #2273
1. Ensure the layout isn't breaking on desktop/mobile.
2. Ensure the retirements page layout is also working as expected.
=> [provenance] fix layout issues with GridContainer

carbon/components/charts/helpers/DataTable/VerticalTableHeader/index.tsx, carbon/components/charts/helpers/DataTable/VerticalTableHeader/styles.module.scss
This PR makes the sort icons in the table headers on klima data visible.
Closes #2196 
See https://carbon-git-2196-make-sort-icons-visible-klimadao.vercel.app/de/retirement-trends
=> [klima data] make sort icons visible

.github/workflows/block_cm_cm_api.yml
The Carbonmark, Carbonmark API & CMS projects have been migrated to:
https://github.com/Carbonmark/monorepo
We will keep the projects in this repo as a safety precaution but development work should all be directed to the new repo.
=> chore: block PRs to CM, CM-API & CMS

carbon-projects/schemas/country.ts, carbon-projects/schemas/index.ts, carbon-projects/schemas/methodology.ts, carbon-projects/schemas/project.ts
Needed because Puro projects only have a country not a geolocation
Will need fallback logic to read from this new `countryDetails` field if the project location is missing
=> Add country type to carbon projects CMS for tracking centroids

app/components/NavMenu/index.tsx, app/components/views/Offset/index.tsx
=> Update copy and remove outdated navbar links

.github/pull_request_template.md, app/pages/api/supply.ts
This pull request will re-introduce the /supply API URL for KlimaDAO. 
This end-point can then be used in platforms like CoinMarketCap/Coingecko
Closes 2377
1. Open terminal 
2. Run `npm run dev-app` from root dir
3. Open a new terminal
4. Run the following commands to test all cases & update port-no before testing 
port-no. can be seen as an output of step(2) 
```
curl -X "GET" "localhost:<port-no>/api/supply?type=total-supply&token=<klima|bct>"
curl -X "GET" "localhost:<port-no>/api/supply?type=circulating-supply&token=<klima|bct>"
```
Screenshot below
=> must-be-carbon/feat/2377 add supply endpoint for KLIMA & BCT

carbon-projects/lib/categories.ts, carbon-projects/schemas/methodology.ts, carbon-projects/schemas/projectContent.ts
After discussion with Drew it has become apparent that we will need to override the name and also the category for projects in some cases
For instance an ICR project with an awkwardly formatted name, that uses a generic ISO methodology (so category defaults to "Other") 
Easiest way to handle this is to have some override logic, but we will need the frontend to respect these overrides and the filtering logic to be aware of them (Esp for methodology category)
This PR simply adds the new fields to the CMS, subsequent work is required to implement FE and filtering changes
=> Add fields for name and category override to ProjectContent

carbon-projects/schemas/index.ts, carbon-projects/schemas/indexContent.ts, carbon-projects/schemas/objects/captionImage.ts, carbon-projects/schemas/project.ts, carbon-projects/schemas/projectContent.ts
Captions are not showing up in GraphQL because they are defined inline
Defining a custom type resolves this
=> Restructure schema to catch captions in GraphQL

base/components/AppLayout/index.tsx, base/components/DisclaimerModal/index.tsx, base/components/DisclaimerModal/styles.ts
Adds a disclaimer modal with the same functionality as the current Klima dApp.
Closes #2402
=> [base] add disclaimer modal

.github/workflows/build_cms.yml, .github/workflows/update_translations.yml, carbon-projects/lib/fileCategories.ts, carbon-projects/lib/sectors.ts, carbon-projects/schemas/accreditation.ts, carbon-projects/schemas/assessor.ts, carbon-projects/schemas/developer.ts, carbon-projects/schemas/index.ts, carbon-projects/schemas/methodology.ts, carbon-projects/schemas/objects/hostedFile.ts, carbon-projects/schemas/project.ts, carbon-projects/schemas/standard.ts
To support direct issuance documents being uploaded directly rather than referencing externally hosted documents from e.g. a registry
We may need other additional fields as the design solidifies so going to hold off on merging/deploying this
=> Add additional fields for direct issuance projects

carbon-projects/lib/fileCategories.ts
Per request from @0xMakka to make FE work simpler
=> Fix file category values

carbon-projects/lib/sectors.ts, carbon-projects/schemas/project.ts
We need the labels to be readable on the front end so this front end aligns the value property following the same format as categories etc...
=> fix various label values

base/lib/submitCrossChain.ts, lib/abi/InterchainTokenService.json
Currently retire on base with Axelar is reverting. This is due to an update on the Axelar side where the main function we call was removed in the following PR - https://github.com/axelarnetwork/interchain-token-service/commit/9ada6d42eb58849aa71063c086f3e9d26e59840a/
This PR updates the abi to the latest and calls the `interchainTransfer` instead of the removed function `callContractWithInterchainToken`
=> fix: update axelar interchain abi and function call

base/components/AutoCompounder/NavLinks/styles.tsx, base/lib/constants.ts
This PR, checks the chain id matches rather than the full chain object. I noticed, the lps load correctly when a user isn't logged in, but as soon as you log in, you are just shown the spinner which never resolves.
After digging around, it seems that when return the liquidity pools, we check `chain === base`, but the rpc url is different in chain vs base when logged in, so returns false empty results. I've made the change to just compare the chain id to the base network id. 
I also made a change to a css element, as I was seeing an error about anchor tags cannot be a descendant of another anchor tag.
=> fix lp check
